apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bossnyumba-staging

resources:
  - ../../base

images:
  - name: ghcr.io/bossnyumba/document-render
    newTag: staging

patches:
  - target:
      kind: Deployment
      name: document-render
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "1500m"
            memory: "2Gi"
  - target:
      kind: HorizontalPodAutoscaler
      name: document-render
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 3
  - target:
      kind: ExternalSecret
      name: document-render-secrets
    patch: |-
      - op: replace
        path: /spec/dataFrom/0/extract/key
        value: bossnyumba/staging/document-render
