{{- $w := .Values.apps.ownerPortal -}}
{{- if $w.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $w.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bossnyumba.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $w.name }}
spec:
  type: ClusterIP
  selector:
    {{- include "bossnyumba.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $w.name }}
  ports:
    - { name: http, port: 80, targetPort: http, protocol: TCP }
{{- end }}
