/**
 * Generate a `.github/CODEOWNERS` file body from a typed config.
 *
 * Rules are emitted in declaration order (later rules win, per GitHub
 * spec). We also enforce a sane header so reviewers know the file is
 * machine-generated.
 */

import {
  codeownersConfigSchema,
  type CodeownersConfig,
  type RequiredReviewerRuleset,
} from './types.js';

const HEADER = [
  '# CODEOWNERS — generated by @bossnyumba/self-codegen.',
  '# Source of truth: bossnyumba.codeowners.yml',
  '# Do not edit by hand. The brain re-generates this file on each',
  '# tenant-config change. The .claude/** rule guards the brain itself.',
  '',
].join('\n');

export function generateCodeownersFile(config: CodeownersConfig): string {
  const parsed = codeownersConfigSchema.parse(config);
  const lines: string[] = [HEADER];

  if (parsed.defaultOwners.length > 0) {
    lines.push(`* ${parsed.defaultOwners.join(' ')}`);
    lines.push('');
  }

  for (const [name, rs] of Object.entries(parsed.ruleSets)) {
    lines.push(`# === ${name} ===`);
    for (const path of rs.paths) {
      const normalized = normalizeCodeownerPath(path);
      lines.push(`${normalized} ${rs.owners.join(' ')}`);
    }
    lines.push('');
  }

  return lines.join('\n').trimEnd() + '\n';
}

function normalizeCodeownerPath(path: string): string {
  // CODEOWNERS uses fnmatch-style globs. Normalize leading ./ off.
  let p = path.replace(/^\.\//, '');
  // Anchor leading-slash paths to the repo root.
  if (!p.startsWith('/') && !p.startsWith('*')) {
    p = `/${p}`;
  }
  return p;
}

/**
 * Build the GitHub required-reviewer-ruleset JSON. The agent NEVER counts
 * toward the dual-human approval, so we exclude its login.
 */
export function generateRequiredReviewerRuleset(args: {
  config: CodeownersConfig;
  protectedBranches: readonly string[];
  agentLogin: string;
}): RequiredReviewerRuleset {
  const { config, protectedBranches, agentLogin } = args;
  const parsed = codeownersConfigSchema.parse(config);
  const patterns = new Set<string>();
  for (const rs of Object.values(parsed.ruleSets)) {
    for (const p of rs.paths) patterns.add(p);
  }
  return Object.freeze<RequiredReviewerRuleset>({
    enabled: true,
    target: 'branch',
    conditions: {
      refName: {
        include: Object.freeze([...protectedBranches]),
      },
    },
    rules: Object.freeze(
      [...patterns].map((pattern) =>
        Object.freeze({
          pattern,
          minApprovals: 1,
          excludeUsers: Object.freeze([agentLogin]),
        }),
      ),
    ),
  });
}
