import { describe, expect, it } from 'vitest';

import {
  generateCodeownersFile,
  generateRequiredReviewerRuleset,
} from './generate-codeowners.js';
import {
  DEFAULT_BOSSNYUMBA_CODEOWNERS_YML,
  loadCodeownersConfigFromYml,
} from './load-yml.js';
import { type CodeownersConfig } from './types.js';

const validConfig: CodeownersConfig = {
  defaultOwners: ['@platform-admin'],
  ruleSets: {
    finance: {
      paths: [
        'services/payments-ledger/**',
        'packages/connectors/m-pesa/**',
      ],
      owners: ['@finance-lead', '@finance-deputy'],
    },
    database: {
      paths: ['packages/database/src/migrations/**'],
      owners: ['@db-lead'],
    },
    selfPolicy: {
      paths: [
        '.claude/**',
        '.github/workflows/**',
        'packages/self-codegen/**',
      ],
      owners: ['@platform-admin', '@security-lead'],
    },
  },
};

describe('codeowners-templating — loadCodeownersConfigFromYml', () => {
  it('loads the default skeleton', () => {
    const cfg = loadCodeownersConfigFromYml(DEFAULT_BOSSNYUMBA_CODEOWNERS_YML);
    expect(cfg.defaultOwners).toContain('@platform-admin');
    expect(cfg.ruleSets.finance?.owners).toContain('@finance-lead');
    expect(cfg.ruleSets.selfPolicy?.paths).toContain('.claude/**');
  });

  it('throws on empty input', () => {
    expect(() => loadCodeownersConfigFromYml('')).toThrow();
  });

  it('rejects non-@ owners (zod schema)', () => {
    expect(() =>
      loadCodeownersConfigFromYml(`defaultOwners: [foo]\nruleSets: {}`),
    ).toThrow();
  });
});

describe('codeowners-templating — generateCodeownersFile', () => {
  it('renders the expected header + default owners + rulesets in declaration order', () => {
    const out = generateCodeownersFile(validConfig);
    expect(out).toContain('# CODEOWNERS — generated by @bossnyumba/self-codegen.');
    expect(out).toContain('* @platform-admin');
    expect(out).toMatch(/# === finance ===\n\/services\/payments-ledger\/\*\* @finance-lead @finance-deputy/);
    expect(out).toContain('/.claude/** @platform-admin @security-lead');
  });

  it('anchors paths to repo root with leading slash unless they start with *', () => {
    const out = generateCodeownersFile({
      defaultOwners: [],
      ruleSets: {
        x: {
          paths: ['packages/x/**', '*.md'],
          owners: ['@owner'],
        },
      },
    });
    expect(out).toContain('/packages/x/** @owner');
    expect(out).toContain('*.md @owner');
  });

  it('zod schema rejects rulesets with no paths', () => {
    expect(() =>
      generateCodeownersFile({
        defaultOwners: [],
        ruleSets: { bad: { paths: [], owners: ['@x'] } },
      } as unknown as CodeownersConfig),
    ).toThrow();
  });

  it('always renders selfPolicy guarding .claude/** so the brain cannot rewrite itself', () => {
    const out = generateCodeownersFile(validConfig);
    expect(out).toContain('# === selfPolicy ===');
    expect(out).toContain('/.claude/**');
    expect(out).toContain('/packages/self-codegen/**');
  });
});

describe('codeowners-templating — generateRequiredReviewerRuleset', () => {
  it('emits a rule per unique path, excludes the agent', () => {
    const ruleset = generateRequiredReviewerRuleset({
      config: validConfig,
      protectedBranches: ['main', 'release/**'],
      agentLogin: 'bossnyumba-brain[bot]',
    });
    expect(ruleset.enabled).toBe(true);
    expect(ruleset.target).toBe('branch');
    expect(ruleset.conditions.refName.include).toEqual(['main', 'release/**']);
    expect(ruleset.rules.length).toBeGreaterThanOrEqual(6);
    for (const r of ruleset.rules) {
      expect(r.excludeUsers).toContain('bossnyumba-brain[bot]');
      expect(r.minApprovals).toBeGreaterThanOrEqual(1);
    }
  });
});
