apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bossnyumba-staging

resources:
  - ../../base

images:
  - name: ghcr.io/bossnyumba/scientific-discovery-sidecar
    newTag: staging

patches:
  - target:
      kind: Deployment
      name: scientific-discovery-sidecar
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "500m"
            memory: "1.5Gi"
          limits:
            cpu: "2"
            memory: "3Gi"
  - target:
      kind: HorizontalPodAutoscaler
      name: scientific-discovery-sidecar
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 2
  - target:
      kind: ExternalSecret
      name: scientific-discovery-sidecar-secrets
    patch: |-
      - op: replace
        path: /spec/dataFrom/0/extract/key
        value: bossnyumba/staging/scientific-discovery-sidecar
