apiVersion: v1
kind: Service
metadata:
  name: outcomes-metering
  labels:
    app.kubernetes.io/name: outcomes-metering
    app.kubernetes.io/part-of: bossnyumba
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: outcomes-metering
  ports:
    - name: http
      port: 80
      targetPort: 3018
      protocol: TCP
    - name: metrics
      port: 9464
      targetPort: 9464
      protocol: TCP
