apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bossnyumba-staging

resources:
  - ../../base

images:
  - name: ghcr.io/georgemwiki/bossnyumba-mcp-server-opay
    newTag: staging

patches:
  - target:
      kind: Deployment
      name: mcp-server-opay
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "50m"
            memory: "96Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
  - target:
      kind: ExternalSecret
      name: mcp-server-opay-secrets
    patch: |-
      - op: replace
        path: /spec/dataFrom/0/extract/key
        value: bossnyumba/staging/mcp-server-opay
