apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bossnyumba-app

commonLabels:
  app.kubernetes.io/part-of: bossnyumba
  app.kubernetes.io/managed-by: kustomize

resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml
  - servicemonitor.yaml
  - externalsecret.yaml

images:
  - name: ghcr.io/georgemwiki/bossnyumba-voice-agent
    newTag: latest
