export {
  DEFAULT_AUTO_TRIP_THRESHOLDS,
  evaluateAutoTrip,
  getKillSwitchStatus,
  globalKillSwitch,
  InMemoryKillSwitchStore,
  killAgent,
  pauseAgent,
  resumeAgent,
  type AutoTripInput,
  type AutoTripThresholds,
  type AutoTripVerdict,
  type GetKillSwitchStatusArgs,
  type GlobalKillArgs,
  type KillAgentArgs,
  type KillSwitchStore,
  type PauseAgentArgs,
  type ResumeAgentArgs,
} from './kill-switch.js';
