/**
 * Green-finance catalog — 20+ instruments active in 2026.
 *
 * Pure data. No I/O.
 *
 * Reference: `.audit/sota-2026-05-24/05-green-angle-advisor.md` §2.
 */

import type { FinancingInstrument } from '../types.js';

export const GREEN_FINANCE_CATALOG: readonly FinancingInstrument[] = [
  // ICMA principle-aligned issuances
  {
    id: 'icma-green-bond',
    name: 'ICMA Green Bond (GBP)',
    type: 'green-bond',
    sponsor: 'Issuer',
    authority: 'ICMA Green Bond Principles (Jun 2025)',
    regions: ['KE', 'TZ', 'UG', 'RW', 'ZA', 'NG', 'GH', 'EG', 'EU', 'UK', 'US'],
    eligibleProjectTypes: [
      'residential',
      'commercial-office',
      'retail',
      'industrial',
      'infrastructure-rail',
      'infrastructure-port',
      'infrastructure-airport',
      'infrastructure-highway',
      'energy',
      'water',
      'agriculture',
    ],
    eligibleCategories: [
      'renewable-energy',
      'energy-efficiency',
      'pollution-prevention',
      'water',
      'biodiversity',
      'land-use',
      'transport-emissions',
    ],
    indicativeTerms: '5-30 yr tenor, 10 ICMA-eligible categories, third-party SPO',
    reference: 'https://www.icmagroup.org/sustainable-finance/the-principles-guidelines-and-handbooks/',
  },
  {
    id: 'icma-social-bond',
    name: 'ICMA Social Bond (SBP)',
    type: 'social-bond',
    sponsor: 'Issuer',
    authority: 'ICMA Social Bond Principles',
    regions: ['KE', 'TZ', 'UG', 'RW', 'ZA', 'NG', 'GH', 'EG', 'EU', 'UK', 'US'],
    eligibleProjectTypes: ['residential', 'water', 'telecom'],
    eligibleCategories: ['community', 'water'],
    indicativeTerms: 'Affordable basic infrastructure, access to essential services, affordable housing',
    reference: 'https://www.icmagroup.org/sustainable-finance/the-principles-guidelines-and-handbooks/',
  },
  {
    id: 'icma-sustainability-bond',
    name: 'ICMA Sustainability Bond (SBG)',
    type: 'sustainability-bond',
    sponsor: 'Issuer',
    authority: 'ICMA Sustainability Bond Guidelines',
    regions: ['KE', 'TZ', 'UG', 'RW', 'ZA', 'NG', 'GH', 'EG', 'EU', 'UK', 'US'],
    eligibleProjectTypes: [
      'residential',
      'commercial-office',
      'water',
      'infrastructure-rail',
      'energy',
    ],
    eligibleCategories: ['renewable-energy', 'water', 'community'],
    indicativeTerms: 'Hybrid green + social use-of-proceeds; same SPO regime',
    reference: 'https://www.icmagroup.org/sustainable-finance/the-principles-guidelines-and-handbooks/',
  },
  {
    id: 'icma-slb',
    name: 'ICMA Sustainability-Linked Bond (SLB)',
    type: 'sustainability-linked-bond',
    sponsor: 'Issuer',
    authority: 'ICMA Sustainability-Linked Bond Principles',
    regions: ['KE', 'TZ', 'UG', 'RW', 'ZA', 'NG', 'GH', 'EG', 'EU', 'UK', 'US'],
    eligibleProjectTypes: [
      'industrial',
      'energy',
      'infrastructure-rail',
      'infrastructure-port',
      'mining',
      'agriculture',
    ],
    eligibleCategories: [
      'transport-emissions',
      'energy-efficiency',
      'pollution-prevention',
      'climate-adaptation',
    ],
    indicativeTerms: 'KPI + SPT step-up coupon typ. 25 bps if SPT missed',
    reference: 'https://www.icmagroup.org/sustainable-finance/the-principles-guidelines-and-handbooks/',
  },
  // LMA loan products
  {
    id: 'lma-green-loan',
    name: 'LMA Green Loan (GLP)',
    type: 'green-loan',
    sponsor: 'Lender syndicate',
    authority: 'LMA/APLMA/LSTA Green Loan Principles (Feb 2024)',
    regions: ['KE', 'TZ', 'UG', 'RW', 'ZA', 'NG', 'GH', 'EG', 'EU', 'UK', 'US'],
    eligibleProjectTypes: [
      'residential',
      'commercial-office',
      'retail',
      'industrial',
      'energy',
      'infrastructure-rail',
      'infrastructure-port',
      'water',
    ],
    eligibleCategories: ['renewable-energy', 'energy-efficiency', 'water', 'biodiversity'],
    indicativeTerms: '5-15 yr tenor, eligible-use covenants',
    reference: 'https://www.lma.eu.com/sustainable-lending',
  },
  {
    id: 'lma-sll',
    name: 'LMA Sustainability-Linked Loan (SLL)',
    type: 'sustainability-linked-loan',
    sponsor: 'Lender syndicate',
    authority: 'LMA/APLMA/LSTA Sustainability-Linked Loan Principles (May 2025)',
    regions: ['KE', 'TZ', 'UG', 'RW', 'ZA', 'NG', 'GH', 'EG', 'EU', 'UK', 'US'],
    eligibleProjectTypes: [
      'commercial-office',
      'industrial',
      'energy',
      'infrastructure-rail',
      'infrastructure-port',
      'mining',
      'agriculture',
    ],
    eligibleCategories: [
      'transport-emissions',
      'energy-efficiency',
      'pollution-prevention',
      'climate-adaptation',
    ],
    indicativeTerms: 'Margin step-down 5-15 bps on KPI met; symmetric step-up',
    reference: 'https://www.lma.eu.com/sustainable-lending',
  },
  {
    id: 'icma-transition',
    name: 'ICMA Climate Transition Finance',
    type: 'transition-finance',
    sponsor: 'Issuer',
    authority: 'ICMA Climate Transition Finance Handbook (Dec 2023)',
    regions: ['KE', 'TZ', 'UG', 'RW', 'ZA', 'NG', 'GH', 'EG', 'EU', 'UK', 'US'],
    eligibleProjectTypes: ['industrial', 'energy', 'mining', 'infrastructure-port'],
    eligibleCategories: ['pollution-prevention', 'energy-efficiency', 'transport-emissions'],
    indicativeTerms: 'Hard-to-abate transition; sci-based pathway disclosure required',
    reference: 'https://www.icmagroup.org/sustainable-finance/the-principles-guidelines-and-handbooks/',
  },
  // Multilateral / development finance
  {
    id: 'gcf',
    name: 'Green Climate Fund (GCF)',
    type: 'concessional-debt',
    sponsor: 'GCF',
    authority: 'UNFCCC Green Climate Fund',
    regions: ['KE', 'TZ', 'UG', 'RW', 'BI', 'ET', 'ZA', 'NG', 'GH', 'EG'],
    eligibleProjectTypes: [
      'water',
      'agriculture',
      'energy',
      'infrastructure-rail',
      'infrastructure-port',
      'residential',
    ],
    eligibleCategories: [
      'renewable-energy',
      'water',
      'climate-adaptation',
      'biodiversity',
      'land-use',
    ],
    indicativeTerms: 'Up to 25-yr tenor; 0-4% rate; grants + concessional debt + equity',
    reference: 'https://www.greenclimate.fund/',
  },
  {
    id: 'afdb-sefa',
    name: 'AfDB Sustainable Energy Fund for Africa (SEFA)',
    type: 'concessional-debt',
    sponsor: 'AfDB',
    authority: 'AfDB',
    regions: ['KE', 'TZ', 'UG', 'RW', 'BI', 'ET', 'ZA', 'NG', 'GH', 'EG'],
    eligibleProjectTypes: ['energy', 'infrastructure-port', 'industrial'],
    eligibleCategories: ['renewable-energy', 'energy-efficiency'],
    indicativeTerms: 'Grants, concessional debt, equity up to USD 9.5m',
    reference: 'https://www.afdb.org/en/topics-and-sectors/initiatives-partnerships/sustainable-energy-fund-for-africa',
  },
  {
    id: 'afdb-aaap',
    name: 'AfDB Africa Adaptation Acceleration Program (AAAP)',
    type: 'concessional-debt',
    sponsor: 'AfDB + GCA',
    authority: 'AfDB',
    regions: ['KE', 'TZ', 'UG', 'RW', 'BI', 'ET', 'ZA', 'NG', 'GH', 'EG'],
    eligibleProjectTypes: ['water', 'agriculture', 'infrastructure-rail', 'infrastructure-port'],
    eligibleCategories: ['climate-adaptation', 'water', 'biodiversity'],
    indicativeTerms: 'USD 25bn rolling envelope; sovereign + non-sovereign',
    reference: 'https://www.afdb.org/en/topics-and-sectors/initiatives-partnerships/africa-adaptation-acceleration-program',
  },
  {
    id: 'afdb-afr100',
    name: 'AfDB / WRI AFR100 — African Forest Landscape Restoration',
    type: 'grant',
    sponsor: 'AfDB + WRI',
    authority: 'AfDB / WRI',
    regions: ['KE', 'TZ', 'UG', 'RW', 'BI', 'ET', 'ZA', 'NG', 'GH'],
    eligibleProjectTypes: ['agriculture', 'mining', 'water', 'infrastructure-rail', 'infrastructure-highway'],
    eligibleCategories: ['land-use', 'biodiversity', 'community'],
    indicativeTerms: 'Landscape restoration grants up to 100 Mha target',
    reference: 'https://afr100.org/',
  },
  {
    id: 'ifc-edge',
    name: 'IFC EDGE Green Building Certification',
    type: 'green-loan',
    sponsor: 'IFC',
    authority: 'IFC + GBCI',
    regions: ['KE', 'TZ', 'UG', 'RW', 'BI', 'ET', 'ZA', 'NG', 'GH', 'EG', 'EU', 'UK', 'US'],
    eligibleProjectTypes: ['residential', 'commercial-office', 'retail', 'hospitality'],
    eligibleCategories: ['energy-efficiency', 'water', 'pollution-prevention'],
    indicativeTerms: 'EDGE certification unlocks ~50 bps green-loan margin discount',
    reference: 'https://edgebuildings.com/',
  },
  {
    id: 'jbic-green',
    name: 'JBIC GREEN (Global Action for Reconciling Economic Growth and ENvironmental Preservation)',
    type: 'concessional-debt',
    sponsor: 'JBIC',
    authority: 'JBIC',
    regions: ['KE', 'TZ', 'UG', 'RW', 'ET', 'ZA', 'NG', 'EG'],
    eligibleProjectTypes: ['energy', 'industrial', 'infrastructure-port'],
    eligibleCategories: ['renewable-energy', 'energy-efficiency', 'pollution-prevention'],
    indicativeTerms: 'Yen-linked TONA-replacement rate; concessional',
    reference: 'https://www.jbic.go.jp/en/efforts/environment.html',
  },
  {
    id: 'deg-kfw',
    name: 'KfW DEG (Deutsche Entwicklungsgesellschaft)',
    type: 'equity',
    sponsor: 'KfW',
    authority: 'KfW',
    regions: ['KE', 'TZ', 'UG', 'RW', 'ET', 'ZA', 'NG', 'GH', 'EG'],
    eligibleProjectTypes: [
      'residential',
      'commercial-office',
      'industrial',
      'agriculture',
      'energy',
    ],
    eligibleCategories: [
      'renewable-energy',
      'energy-efficiency',
      'water',
      'land-use',
      'community',
    ],
    indicativeTerms: 'Equity + sub-debt, ESG-linked',
    reference: 'https://www.deginvest.de/',
  },
  {
    id: 'eib-global',
    name: 'EIB Global',
    type: 'concessional-debt',
    sponsor: 'EIB',
    authority: 'EIB',
    regions: ['KE', 'TZ', 'UG', 'RW', 'ET', 'ZA', 'NG', 'GH', 'EG'],
    eligibleProjectTypes: [
      'energy',
      'water',
      'infrastructure-rail',
      'infrastructure-port',
      'infrastructure-airport',
    ],
    eligibleCategories: [
      'renewable-energy',
      'water',
      'transport-emissions',
      'pollution-prevention',
    ],
    indicativeTerms: 'Up to 50% project; sovereign + non-sovereign',
    reference: 'https://www.eib.org/en/projects/regions/global/index.htm',
  },
  {
    id: 'afd-proclimat',
    name: 'AFD ProClimat',
    type: 'concessional-debt',
    sponsor: 'AFD',
    authority: 'AFD',
    regions: ['KE', 'TZ', 'UG', 'RW', 'BI', 'ET', 'ZA', 'NG', 'GH', 'EG'],
    eligibleProjectTypes: ['water', 'energy', 'agriculture', 'infrastructure-rail'],
    eligibleCategories: ['renewable-energy', 'climate-adaptation', 'water', 'land-use'],
    indicativeTerms: 'Sovereign concessional debt',
    reference: 'https://www.afd.fr/en/proclimat',
  },
  {
    id: 'fmo-building-prospects',
    name: 'FMO Building Prospects',
    type: 'equity',
    sponsor: 'FMO',
    authority: 'FMO',
    regions: ['KE', 'TZ', 'UG', 'RW', 'ET', 'ZA', 'NG', 'GH', 'EG'],
    eligibleProjectTypes: ['infrastructure-rail', 'infrastructure-port', 'energy', 'industrial'],
    eligibleCategories: ['renewable-energy', 'transport-emissions', 'energy-efficiency'],
    indicativeTerms: 'Equity + debt for frontier-market infra',
    reference: 'https://www.fmo.nl/building-prospects',
  },
  {
    id: 'norfund',
    name: 'Norfund',
    type: 'equity',
    sponsor: 'Norfund',
    authority: 'Norwegian Government',
    regions: ['KE', 'TZ', 'UG', 'RW', 'ET', 'ZA'],
    eligibleProjectTypes: ['energy', 'agriculture', 'residential'],
    eligibleCategories: ['renewable-energy', 'land-use'],
    indicativeTerms: 'Equity; focus renewables + financial inclusion',
    reference: 'https://www.norfund.no/',
  },
  {
    id: 'bii',
    name: 'British International Investment (BII)',
    type: 'equity',
    sponsor: 'BII (ex-CDC)',
    authority: 'BII',
    regions: ['KE', 'TZ', 'UG', 'RW', 'ET', 'ZA', 'NG', 'GH', 'EG'],
    eligibleProjectTypes: [
      'energy',
      'agriculture',
      'industrial',
      'infrastructure-rail',
      'residential',
    ],
    eligibleCategories: ['renewable-energy', 'climate-adaptation', 'community'],
    indicativeTerms: 'Equity + debt, ESG-linked',
    reference: 'https://www.bii.co.uk/',
  },
  {
    id: 'cif-ctf',
    name: 'Climate Investment Funds — CTF + SCF',
    type: 'blended-finance',
    sponsor: 'World Bank Group',
    authority: 'CIF Trustee (World Bank)',
    regions: ['KE', 'TZ', 'UG', 'RW', 'BI', 'ET', 'ZA', 'NG', 'GH', 'EG'],
    eligibleProjectTypes: ['energy', 'industrial', 'agriculture', 'water'],
    eligibleCategories: [
      'renewable-energy',
      'climate-adaptation',
      'land-use',
      'energy-efficiency',
    ],
    indicativeTerms: 'Blended concessional debt; MDB co-financing required',
    reference: 'https://www.cif.org/',
  },
  {
    id: 'ep5',
    name: 'Equator Principles 5 (EP5) — project-finance qualification',
    type: 'guarantee',
    sponsor: 'Equator Principles Association',
    authority: 'Equator Principles 5 (Jul 2025)',
    regions: ['KE', 'TZ', 'UG', 'RW', 'ET', 'ZA', 'NG', 'GH', 'EG', 'EU', 'UK', 'US'],
    eligibleProjectTypes: [
      'infrastructure-rail',
      'infrastructure-port',
      'infrastructure-airport',
      'infrastructure-highway',
      'energy',
      'mining',
      'industrial',
    ],
    eligibleCategories: ['climate-adaptation', 'biodiversity', 'pollution-prevention'],
    indicativeTerms: 'Project-finance ≥USD 10m; corporate loans ≥USD 50m; mandatory climate transition plan for high-risk',
    reference: 'https://equator-principles.com/',
  },
];

export function findInstrumentById(id: string): FinancingInstrument | undefined {
  return GREEN_FINANCE_CATALOG.find((i) => i.id === id);
}
