apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bossnyumba-prod

resources:
  - ../../base

images:
  - name: ghcr.io/bossnyumba/scientific-discovery-sidecar
    newTag: ${IMAGE_TAG}

patches:
  - target:
      kind: Deployment
      name: scientific-discovery-sidecar
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "2"
            memory: "4Gi"
          limits:
            cpu: "4"
            memory: "8Gi"
      - op: replace
        path: /spec/template/spec/affinity/podAntiAffinity
        value:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: scientific-discovery-sidecar
              topologyKey: kubernetes.io/hostname
