/**
 * WalletBar — sticky-top wallet display for the marketplace home.
 *
 * Closes G3 in `Docs/AUDIT/RESEARCH_GAPS_2026-05-29.md` — wires the
 * wallet pattern researched in
 * `Docs/RESEARCH/buyer-marketplace-sota.md` §2.1 + §8:
 *
 *   - **TZS primary, USD/KES secondary** with a tap-to-toggle pill
 *     (Sorted Wallet 2.0 multi-currency UX).
 *   - **FX rate visible** with timestamp; stale > 5 min triggers a
 *     soft refresh indicator.
 *   - **Fund / withdraw CTAs** are out of v1 scope (G8 roadmap item)
 *     so this component renders read-only. The shape is forward-
 *     compatible with the eventual CTA wiring.
 *
 * Per BossNyumba hard rule: every money render uses `formatCurrency`
 * (here delegated to `formatMoney(amount, currency)` which is a tiny
 * 3-currency helper — proper i18n money formatting will land when the
 * gateway endpoint ships rendering hints).
 */

import { Pressable, StyleSheet, Text, View } from 'react-native'
import { tokens } from '@/ui-litfin'
import { formatWalletAmount, type WalletCurrency } from './walletFormat'

export interface WalletSnapshot {
  readonly tzs: number
  readonly usd: number
  readonly kes: number
  /**
   * Tenant-source FX rates pinned at the moment the snapshot was
   * generated by the gateway. Display-only — never used to convert
   * client-side. Per buyer-sota §8 "FX rate visible".
   */
  readonly fxRates: {
    readonly usdPerTzs: number
    readonly kesPerTzs: number
    readonly capturedAt: string
  }
}

export interface WalletBarProps {
  readonly snapshot: WalletSnapshot | null
  readonly translate: (key: string) => string
  readonly secondary: WalletCurrency
  readonly onSecondaryToggle: () => void
  readonly now?: Date
}

const STALE_MS = 5 * 60 * 1000

export function WalletBar({
  snapshot,
  translate,
  secondary,
  onSecondaryToggle,
  now
}: WalletBarProps) {
  if (snapshot === null) {
    return (
      <View style={styles.bar} testID="wallet-bar-loading">
        <Text style={styles.label}>{translate('wallet.loading')}</Text>
      </View>
    )
  }
  const nowDate = now ?? new Date()
  const capturedAt = new Date(snapshot.fxRates.capturedAt)
  const ageMs = nowDate.getTime() - capturedAt.getTime()
  const isStale = ageMs > STALE_MS
  const secondaryAmount = secondary === 'USD' ? snapshot.usd : snapshot.kes
  return (
    <View style={styles.bar} testID="wallet-bar">
      <View style={styles.primaryCol}>
        <Text style={styles.label}>{translate('wallet.balance')}</Text>
        <Text style={styles.primary}>{formatWalletAmount(snapshot.tzs, 'TZS')}</Text>
      </View>
      <Pressable
        style={styles.secondaryCol}
        onPress={onSecondaryToggle}
        accessibilityRole="button"
        accessibilityLabel={translate('wallet.toggle_secondary')}
        testID="wallet-bar-toggle"
      >
        <Text style={styles.secondaryAmount}>
          ≈ {formatWalletAmount(secondaryAmount, secondary)}
        </Text>
        <Text style={[styles.fxNote, isStale ? styles.fxStale : null]}>
          {translate(isStale ? 'wallet.fx_stale' : 'wallet.fx_label')}
        </Text>
      </Pressable>
    </View>
  )
}

const styles = StyleSheet.create({
  bar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: tokens.space.md,
    paddingVertical: tokens.space.md,
    backgroundColor: tokens.color.bgRaised,
    borderRadius: tokens.radius.md,
    borderWidth: 1,
    borderColor: tokens.color.borderGold,
    gap: tokens.space.md
  },
  primaryCol: {
    flex: 1
  },
  secondaryCol: {
    alignItems: 'flex-end'
  },
  label: {
    ...tokens.type.eyebrow,
    color: tokens.color.textMuted
  },
  primary: {
    ...tokens.type.h2,
    color: tokens.color.gold,
    marginTop: 2
  },
  secondaryAmount: {
    ...tokens.type.bodyStrong,
    color: tokens.color.textPrimary
  },
  fxNote: {
    ...tokens.type.micro,
    color: tokens.color.textMuted,
    marginTop: 2
  },
  fxStale: {
    color: tokens.color.warn
  }
})
