/**
 * In-process PDF renderer for `owner_statements` rows that the
 * `statement-adapter` wrote as `status='draft'`.
 *
 * Wave-3 deep-scrub C1 — the statement adapter (B1) writes drafts but
 * never produces an artifact. This renderer flips each draft to the
 * post-render state with a `pdfUrl` populated so the downstream
 * notification adapter has something concrete to link the owner email
 * to.
 *
 * Wave-4 deep-scrub D2 — replaced the `<placeholder>` byte buffer with
 * a real, valid, A4-sized PDF document generated by the in-tree
 * `pdf-templates/owner-statement-template`. The renderer keeps an
 * injectable `render` slot so existing tests can still substitute a
 * stub.
 *
 * Schema reality check
 * --------------------
 * The `owner_statement_status` enum only allows
 *   ['draft', 'pending_review', 'approved', 'sent', 'acknowledged'].
 * There is no `'rendered'` value (and we do NOT add one in this commit
 * — the renderer must work against the shipped schema). We therefore
 * treat `pending_review` as the post-render state: the row has a PDF
 * artifact and is ready for the operator's review pass.
 *
 * The schema also has no `run_id` column on `owner_statements`. We
 * scope the drain by `(tenant_id, status='draft')`, optionally further
 * narrowed by `periodStart/periodEnd` when the caller supplies them.
 * The `runId` parameter is preserved on the public API for log
 * correlation and forward-compatibility once a `run_id` column lands.
 *
 * Storage
 * -------
 * Until a real document store is available we encode the rendered
 * bytes as a `data:application/pdf;base64,...` URL and write it to
 * `owner_statements.pdf_url`. This keeps the artifact retrievable by
 * its row id and avoids introducing a new table just to ship the
 * end-to-end happy path. A follow-up can swap to S3 / blob storage by
 * replacing `toPdfUrl` only.
 *
 * Tenant-scoped on every query.
 */

import { sql } from 'drizzle-orm';

import {
  renderOwnerStatementPdf,
  type OwnerStatementPdfData,
} from './pdf-templates/owner-statement-template';

type Logger = {
  warn(meta: Record<string, unknown>, msg: string): void;
  info?(meta: Record<string, unknown>, msg: string): void;
};

type DbExecutor = { execute(q: unknown): Promise<unknown> };

export type RenderDraftsForRunInput = {
  readonly runId: string;
  readonly tenantId: string;
  readonly periodStart?: string;
  readonly periodEnd?: string;
};

export type RenderDraftsForRunOutput = {
  readonly rendered: number;
  readonly failed: number;
};

export type PdfRenderer = {
  renderDraftsForRun(
    input: RenderDraftsForRunInput,
  ): Promise<RenderDraftsForRunOutput>;
};

function asRows(res: unknown): readonly Record<string, unknown>[] {
  if (Array.isArray(res)) return res as Record<string, unknown>[];
  const r = (res as { rows?: unknown }).rows;
  return Array.isArray(r) ? (r as Record<string, unknown>[]) : [];
}

function toStr(v: unknown): string {
  return typeof v === 'string' ? v : '';
}

function toNumber(v: unknown): number {
  if (typeof v === 'number') return v;
  if (typeof v === 'string') {
    const n = Number.parseInt(v, 10);
    return Number.isFinite(n) ? n : 0;
  }
  if (typeof v === 'bigint') return Number(v);
  return 0;
}

/**
 * Build the human-facing summary that goes into the rendered PDF body.
 * Pure — no I/O, no clock — so the renderer stays trivially testable.
 *
 * Retained for backwards compatibility with existing tests; the real
 * PDF body now comes from `renderOwnerStatementPdf` which derives a
 * structured line list from the same `OwnerStatementPdfData` shape.
 */
export function buildStatementSummary(row: {
  readonly statementId: string;
  readonly statementNumber: string;
  readonly ownerId: string;
  readonly periodStart: string;
  readonly periodEnd: string;
  readonly grossRentMinor: number;
  readonly currency: string;
}): string {
  const lines: readonly string[] = [
    `OWNER STATEMENT`,
    `Statement: ${row.statementNumber}`,
    `Owner: ${row.ownerId}`,
    `Period: ${row.periodStart} -> ${row.periodEnd}`,
    `Gross rent (minor units): ${row.grossRentMinor}`,
    `Currency: ${row.currency || 'XXX'}`,
    `Statement id: ${row.statementId}`,
  ];
  return lines.join('\n');
}

/**
 * Default PDF byte producer.
 *
 * Receives an `OwnerStatementPdfData` payload and returns a Buffer
 * containing a valid `%PDF-1.4` document. The `html` overload is kept
 * so legacy callers / injected stubs that pass a string still work —
 * in that branch we wrap the supplied text in a minimal one-page PDF.
 */
export function renderPdfBytes(
  input: string | OwnerStatementPdfData,
): Buffer {
  if (typeof input === 'string') {
    // Legacy / stub path — wrap the supplied html-like blob in a real
    // PDF so the artifact still passes a `%PDF-` magic-byte check.
    // No real-currency context exists at this seam (the caller passed a
    // raw string), so we route through the template-internal empty
    // currencyCode path — `formatMinorAmount` and `buildStatementLines`
    // both fall back to `'XXX'` when the code is empty, keeping the
    // stub bytes valid PDF without baking a jurisdiction into the
    // renderer. Real flows MUST go through `rowToPdfData` which carries
    // the row's resolved currency.
    return renderOwnerStatementPdf({
      statementId: '(legacy)',
      statementNumber: '(legacy)',
      tenantId: '(legacy)',
      ownerId: '(legacy)',
      periodStart: '',
      periodEnd: '',
      currencyCode: '',
      grossRentMinor: 0,
      extraLineItems: [{ label: input, amountMinor: 0 }],
    });
  }
  return renderOwnerStatementPdf(input);
}

function toPdfUrl(bytes: Buffer): string {
  const b64 = bytes.toString('base64');
  return `data:application/pdf;base64,${b64}`;
}

/**
 * Map a `owner_statements` row into the strongly-typed payload the
 * template consumes. Pure — no DB or clock access.
 */
function rowToPdfData(
  row: Record<string, unknown>,
  tenantId: string,
): OwnerStatementPdfData | null {
  const statementId = toStr(row.id);
  if (!statementId) return null;

  const grossRentMinor = toNumber(row.gross_rent_collected);
  const platformFeeMinor = toNumber(row.management_fee);
  const kraMriDeductionMinor = toNumber(row.other_expenses);
  const totalExpensesMinor = toNumber(row.total_expenses);
  const netIncomeMinor = toNumber(row.net_income);
  const amountDueMinor = toNumber(row.amount_due);

  // Prefer `net_income` when present; fall back to `amount_due` (which
  // the statement-adapter populates with the gross figure).
  const netDisbursementMinor =
    netIncomeMinor !== 0 ? netIncomeMinor : amountDueMinor;

  return {
    statementId,
    statementNumber: toStr(row.statement_number),
    tenantId,
    ownerId: toStr(row.owner_id),
    periodStart: toStr(row.period_start),
    periodEnd: toStr(row.period_end),
    currencyCode: toStr(row.currency),
    grossRentMinor,
    kraMriDeductionMinor,
    platformFeeMinor,
    netDisbursementMinor,
    extraLineItems:
      totalExpensesMinor > 0
        ? [{ label: 'Total expenses', amountMinor: totalExpensesMinor }]
        : undefined,
  };
}

export type CreateDrizzlePdfRendererDeps = {
  readonly db: unknown;
  readonly logger: Logger;
  readonly render?: (input: string | OwnerStatementPdfData) => Buffer;
};

export function createDrizzlePdfRenderer(
  deps: CreateDrizzlePdfRendererDeps,
): PdfRenderer {
  const { db, logger } = deps;
  const render = deps.render ?? renderPdfBytes;
  const exec = (db as DbExecutor).execute.bind(db as DbExecutor);

  return {
    async renderDraftsForRun(input) {
      const { runId, tenantId, periodStart, periodEnd } = input;

      let drafts: readonly Record<string, unknown>[] = [];
      try {
        const res = await exec(sql`
          SELECT
            id,
            statement_number,
            owner_id,
            period_start,
            period_end,
            gross_rent_collected,
            management_fee,
            other_expenses,
            total_expenses,
            net_income,
            amount_due,
            currency
          FROM owner_statements
          WHERE tenant_id = ${tenantId}
            AND status = 'draft'
            ${periodStart ? sql`AND period_start = ${periodStart}` : sql``}
            ${periodEnd ? sql`AND period_end = ${periodEnd}` : sql``}
        `);
        drafts = asRows(res);
      } catch (err) {
        logger.warn(
          {
            port: 'pdf-renderer',
            runId,
            tenantId,
            degraded_reason: 'select_drafts_failed',
            err: err instanceof Error ? err.message : String(err),
          },
          'monthly-close: pdf-renderer could not load drafts — returning zeroes',
        );
        return { rendered: 0, failed: 0 };
      }

      let rendered = 0;
      let failed = 0;

      for (const row of drafts) {
        const pdfData = rowToPdfData(row, tenantId);
        if (!pdfData) continue;
        const statementId = pdfData.statementId;

        try {
          const bytes = render(pdfData);
          const pdfUrl = toPdfUrl(bytes);

          await exec(sql`
            UPDATE owner_statements
            SET status = 'pending_review',
                pdf_url = ${pdfUrl},
                updated_at = NOW()
            WHERE id = ${statementId}
              AND tenant_id = ${tenantId}
              AND status = 'draft'
          `);
          rendered += 1;
        } catch (err) {
          failed += 1;
          logger.warn(
            {
              port: 'pdf-renderer',
              runId,
              tenantId,
              statementId,
              degraded_reason: 'render_or_update_failed',
              err: err instanceof Error ? err.message : String(err),
            },
            'monthly-close: pdf-renderer failed for one statement — continuing',
          );
        }
      }

      logger.info?.(
        {
          port: 'pdf-renderer',
          runId,
          tenantId,
          rendered,
          failed,
          total: drafts.length,
        },
        'monthly-close: pdf-renderer drained drafts',
      );

      return { rendered, failed };
    },
  };
}
