/**
 * Stage 06 — autobiography generation.
 *
 * Closes May-18 ledger §4.2c. After the worker has reflected on the
 * day's traces and written memory deltas, this stage produces a
 * narrative-form autobiography ("Over the past 24 hours I have answered
 * M questions, refused R, …") and persists it into the persona
 * core-memory block. The autobiography is what makes the brain feel
 * like the SAME brain across sessions — not a fresh-start chatbot —
 * which is the LITFIN-side "13c" pattern we deferred.
 *
 * The narrative is generated by the pure function
 * `generateAutobiography` exported from
 * `@bossnyumba/central-intelligence/metacognition` — no LLM call here;
 * the pure aggregator does all the work. A downstream embellisher
 * (kernel) can rewrite it in the persona's voice on read.
 *
 * Output: one `MemoryDelta` per persona in the trace window. Stage-04
 * is responsible for the actual write; this stage is pure derivation.
 *
 * Reference:
 *   - LITFIN: src/core/litfin-ai/memory/autobiography.ts
 *   - Anthropic 2025 — persistent persona pattern
 */

import { createHash } from 'node:crypto';
import {
  generateAutobiography,
  type AutobiographyDecisionRecord,
} from '@bossnyumba/central-intelligence/metacognition';
import type {
  InteractionTrace,
  MemoryDelta,
  BrainWorkerLogger,
} from '../types.js';

export interface Stage06Args {
  readonly tenantId: string;
  readonly windowStart: string;
  readonly windowEnd: string;
  readonly traces: ReadonlyArray<InteractionTrace>;
  readonly logger?: BrainWorkerLogger;
}

/**
 * Produces one persona-scoped autobiography delta per persona seen in
 * the trace window. Tenant-scoped, idempotent (same window → same
 * idempotency key).
 */
export function generateAutobiographyDeltas(args: Stage06Args): ReadonlyArray<MemoryDelta> {
  const tracesByPersona = groupByPersona(args.traces);
  const deltas: MemoryDelta[] = [];

  for (const [personaId, personaTraces] of tracesByPersona) {
    const decisions = personaTraces.map(traceToDecisionRecord);
    if (decisions.length === 0) continue;

    const autobiography = generateAutobiography({
      personaId,
      windowDecisions: decisions,
      windowStart: args.windowStart,
      windowEnd: args.windowEnd,
    });

    const idempotencyKey = createHash('sha256')
      .update(
        [
          args.tenantId,
          personaId,
          args.windowStart,
          args.windowEnd,
          'autobiography',
        ].join('|'),
      )
      .digest('hex');

    deltas.push({
      idempotencyKey,
      tenantId: args.tenantId,
      blockKind: 'core',
      coreSubKind: 'persona',
      userId: null,
      personaId,
      semanticKey: null,
      actionTag: 'memory.persona.autobiography',
      content: autobiography.narrative,
      confidence: clampConfidence(autobiography.avgConfidence),
      rationale: buildRationale(autobiography),
    });

    args.logger?.info?.(
      {
        stage: 'autobiography',
        tenantId: args.tenantId,
        personaId,
        decisionCount: decisions.length,
        narrativeLen: autobiography.narrative.length,
      },
      'autobiography delta produced',
    );
  }

  return Object.freeze(deltas);
}

// ─────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────

function groupByPersona(
  traces: ReadonlyArray<InteractionTrace>,
): Map<string, InteractionTrace[]> {
  const out = new Map<string, InteractionTrace[]>();
  for (const t of traces) {
    // A trace without an explicit personaId is bucketed under
    // 'default-persona' so the autobiography still gets written for the
    // tenant's primary persona surface. Multi-persona tenants drive
    // distinct narratives per persona.
    const key = t.personaId ?? 'default-persona';
    const bucket = out.get(key) ?? [];
    bucket.push(t);
    out.set(key, bucket);
  }
  return out;
}

function traceToDecisionRecord(t: InteractionTrace): AutobiographyDecisionRecord {
  const outcome = mapOutcome(t.outcome, t.payload);
  const stakes = mapStakes(t.payload);
  const topic = extractTopic(t.payload, t.summary);
  const confidence = extractConfidence(t.payload);
  return {
    thoughtId: t.traceId,
    outcome,
    stakes,
    confidence,
    ...(topic !== undefined && { topic }),
    capturedAt: t.capturedAt,
  };
}

function mapOutcome(
  outcome: string | null,
  payload: Readonly<Record<string, unknown>>,
): AutobiographyDecisionRecord['outcome'] {
  // Explicit refusal markers in the payload override the generic outcome.
  if (payload['refusal'] === true || payload['blocked'] === true) return 'refusal';
  if (payload['softened'] === true) return 'softened';
  switch (outcome) {
    case 'success':
      return 'answer';
    case 'failure':
    case 'corrected':
    case 'abandoned':
      // A failure that the operator corrected is the brain learning a
      // ceiling — modeled as 'softened' so future narratives reflect
      // self-awareness of the boundary.
      return 'softened';
    default:
      return 'answer';
  }
}

function mapStakes(
  payload: Readonly<Record<string, unknown>>,
): AutobiographyDecisionRecord['stakes'] {
  const raw = payload['stakes'];
  if (raw === 'critical' || raw === 'high' || raw === 'medium' || raw === 'low') {
    return raw;
  }
  // Default heuristic: payment / lease-termination / eviction tags are
  // critical; everything else is medium.
  const tag = String(payload['actionTag'] ?? '').toLowerCase();
  if (
    tag.includes('payment') ||
    tag.includes('terminate') ||
    tag.includes('eviction') ||
    tag.includes('disburse')
  ) {
    return 'critical';
  }
  return 'medium';
}

function extractTopic(
  payload: Readonly<Record<string, unknown>>,
  summary: string,
): string | undefined {
  const explicit = payload['topic'];
  if (typeof explicit === 'string' && explicit.trim().length > 0) {
    return explicit.trim();
  }
  // Heuristic fallback — first two whitespace-separated tokens of the
  // summary. The kernel's downstream embellisher refines this; we just
  // need something stable for the histogram.
  const tokens = summary.trim().split(/\s+/).slice(0, 2);
  return tokens.length > 0 ? tokens.join(' ').toLowerCase() : undefined;
}

function extractConfidence(payload: Readonly<Record<string, unknown>>): number {
  const raw = payload['confidence'];
  if (typeof raw === 'number' && Number.isFinite(raw)) {
    return clampConfidence(raw);
  }
  return 0.5;
}

function clampConfidence(n: number): number {
  if (!Number.isFinite(n)) return 0;
  if (n < 0) return 0;
  if (n > 1) return 1;
  return n;
}

function buildRationale(autobiography: {
  totals: { answers: number; softened: number; refusals: number; criticalTurns: number };
  avgConfidence: number;
}): string {
  const t = autobiography.totals;
  return (
    `Generated from ${t.answers + t.softened + t.refusals} decisions in window: ` +
    `${t.answers} answered, ${t.softened} softened, ${t.refusals} refused, ` +
    `${t.criticalTurns} critical-stakes turns. ` +
    `Mean confidence ${autobiography.avgConfidence.toFixed(2)}.`
  );
}
