apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bossnyumba-staging

resources:
  - ../../base

images:
  - name: ghcr.io/georgemwiki/bossnyumba-consolidation-worker
    newTag: staging

patches:
  - target:
      kind: Deployment
      name: consolidation-worker
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
  - target:
      kind: ExternalSecret
      name: consolidation-worker-secrets
    patch: |-
      - op: replace
        path: /spec/dataFrom/0/extract/key
        value: bossnyumba/staging/consolidation-worker
