apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bossnyumba-app

resources:
  - ../../base

namePrefix: staging-
commonLabels:
  app.kubernetes.io/instance: staging

images:
  - name: ghcr.io/georgemwiki/bossnyumba-field-capture-service
    newTag: staging
