/**
 * Report templates with formatting
 */

export const REPORT_TEMPLATES = {
  rentRoll: {
    title: 'Rent Roll Report',
    header: ['Unit', 'Property', 'Monthly Rent', 'Status', 'Tenant'],
    footer: 'Generated by BOSSNYUMBA Reports',
  },
  collection: {
    title: 'Collection Report',
    header: ['Date', 'Amount', 'Reference', 'Customer'],
    footer: 'Generated by BOSSNYUMBA Reports',
  },
  occupancy: {
    title: 'Occupancy Report',
    header: ['Property', 'Total Units', 'Occupied', 'Occupancy %'],
    footer: 'Generated by BOSSNYUMBA Reports',
  },
  maintenance: {
    title: 'Maintenance Report',
    header: ['Category', 'Count', 'Cost'],
    footer: 'Generated by BOSSNYUMBA Reports',
  },
  financial: {
    title: 'Financial Summary',
    header: ['Metric', 'Value'],
    footer: 'Generated by BOSSNYUMBA Reports',
  },
  tenantStatement: {
    title: 'Tenant Statement',
    header: ['Date', 'Description', 'Debit', 'Credit', 'Balance'],
    footer: 'Generated by BOSSNYUMBA Reports',
  },
  propertyPerformance: {
    title: 'Property Performance',
    header: ['Metric', 'Value'],
    footer: 'Generated by BOSSNYUMBA Reports',
  },
} as const;

export function formatCurrency(amount: number, currency = 'KES'): string {
  return new Intl.NumberFormat('en-KE', { style: 'currency', currency }).format(amount);
}

export function formatPercent(value: number): string {
  return `${value.toFixed(1)}%`;
}

export function formatDate(date: Date): string {
  return date.toISOString().slice(0, 10);
}
