apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bossnyumba-prod

resources:
  - ../../base

images:
  - name: ghcr.io/georgemwiki/bossnyumba-proactive-triggers-worker
    newTag: ${IMAGE_TAG}

patches:
  - target:
      kind: Deployment
      name: proactive-triggers-worker
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "300m"
            memory: "512Mi"
          limits:
            cpu: "2"
            memory: "2Gi"
