/**
 * Learning Journey Registry — named multi-step flows.
 *
 * Estate-management edition: admin onboarding, property-owner onboarding,
 * tenant onboarding, estate-officer training, migration wizard, compliance
 * setup. Each journey's steps map to concepts in classroom/concepts-catalog
 * so the Professor sub-persona can teach + assess along the way.
 *
 * Pure data + lookup helpers. No I/O.
 */

import type {
  JourneyDefinition,
  JourneyStep,
  JourneyAudience,
} from './journey-ui-types.js';

const adminOnboardingSteps: readonly JourneyStep[] = [
  {
    id: 'admin-welcome',
    kind: 'video',
    titleEn: 'Welcome to BOSSNYUMBA',
    titleSw: 'Karibu BOSSNYUMBA',
    descriptionEn: 'Mr. Mwikila introduces the platform and your role as admin.',
    descriptionSw: 'Mr. Mwikila anakuelezea jukwaa na wajibu wako kama msimamizi.',
    expectedMinutes: 5,
    conceptIds: [],
    prerequisites: [],
    required: true,
    videoRef: 'videos/admin/welcome.mp4',
    durationSeconds: 180,
    transcriptRef: 'videos/admin/welcome.vtt',
  },
  {
    id: 'admin-portfolio-shape',
    kind: 'ai-conversation',
    titleEn: 'Shape your portfolio',
    titleSw: 'Pangilia mali yako',
    descriptionEn: 'Conversation to capture property count, unit types, regions.',
    descriptionSw: 'Mazungumzo ya kuchukua idadi ya mali, aina, maeneo.',
    expectedMinutes: 10,
    conceptIds: ['rent_affordability'],
    prerequisites: ['admin-welcome'],
    required: true,
    personaId: 'mr-mwikila',
    openingPromptEn: 'Tell me about the estate you manage — how many units, where, and who owns them.',
    openingPromptSw: 'Niambie kuhusu mali unayosimamia — vyumba vingapi, wapi, na nani mmiliki.',
    evaluationRubric: ['unit-count-captured', 'region-captured', 'owner-linked'],
  },
  {
    id: 'admin-invite-team',
    kind: 'hands-on-task',
    titleEn: 'Invite your team',
    titleSw: 'Walike timu yako',
    descriptionEn: 'Invite estate officers, station masters, and finance staff.',
    descriptionSw: 'Walike maofisa wa mali, viongozi wa vituo, na wafanyakazi wa fedha.',
    expectedMinutes: 8,
    conceptIds: [],
    prerequisites: ['admin-portfolio-shape'],
    required: true,
    taskRef: 'task/invite-team',
    successCriteria: ['at-least-one-officer-invited'],
    blockOnCompletion: false,
  },
  {
    id: 'admin-approval-policy',
    kind: 'reading',
    titleEn: 'Approval policies explained',
    titleSw: 'Maelezo ya sera za idhini',
    descriptionEn: 'Understand how approval matrices work for arrears, tender awards, and maintenance.',
    descriptionSw: 'Elewa jinsi matrix za idhini zinavyofanya kazi.',
    expectedMinutes: 7,
    conceptIds: [],
    prerequisites: ['admin-invite-team'],
    required: true,
    contentMdRef: 'docs/admin/approval-policies.md',
    estimatedWordCount: 900,
  },
  {
    id: 'admin-financial-setup',
    kind: 'hands-on-task',
    titleEn: 'Configure GePG and M-Pesa',
    titleSw: 'Sanidi GePG na M-Pesa',
    descriptionEn: 'Wire up the rent collection channels your estate actually uses.',
    descriptionSw: 'Unganisha njia za ukusanyaji wa kodi.',
    expectedMinutes: 12,
    conceptIds: ['gepg_reconciliation'],
    prerequisites: ['admin-approval-policy'],
    required: true,
    taskRef: 'task/configure-payment-channels',
    successCriteria: ['at-least-one-channel-configured'],
    blockOnCompletion: true,
  },
  {
    id: 'admin-first-report',
    kind: 'hands-on-task',
    titleEn: 'Generate your first owner report',
    titleSw: 'Tengeneza ripoti yako ya kwanza ya mmiliki',
    descriptionEn: 'Walk through a real report generation for an owner.',
    descriptionSw: 'Tengeneza ripoti halisi kwa mmiliki.',
    expectedMinutes: 10,
    conceptIds: [],
    prerequisites: ['admin-financial-setup'],
    required: true,
    taskRef: 'task/generate-owner-report',
    successCriteria: ['report-pdf-generated'],
    blockOnCompletion: false,
  },
  {
    id: 'admin-quiz',
    kind: 'quiz',
    titleEn: 'Admin onboarding quiz',
    titleSw: 'Jaribio la uanzishaji wa msimamizi',
    descriptionEn: 'Confirm your mastery of BOSSNYUMBA admin fundamentals.',
    descriptionSw: 'Thibitisha ufahamu wako wa msingi wa msimamizi.',
    expectedMinutes: 8,
    conceptIds: ['rent_affordability', 'deposit_structures', 'gepg_reconciliation'],
    prerequisites: ['admin-first-report'],
    required: true,
    questionIds: ['q-admin-1', 'q-admin-2', 'q-admin-3', 'q-admin-4', 'q-admin-5'],
    passingScore: 70,
    maxAttempts: 3,
  },
];

const propertyOwnerOnboardingSteps: readonly JourneyStep[] = [
  {
    id: 'owner-welcome',
    kind: 'video',
    titleEn: 'Owner quick-start',
    titleSw: 'Uanzishaji wa haraka kwa mmiliki',
    descriptionEn: 'Two-minute tour of the owner portal.',
    descriptionSw: 'Ziara ya dakika mbili ya tovuti ya mmiliki.',
    expectedMinutes: 3,
    conceptIds: [],
    prerequisites: [],
    required: true,
    videoRef: 'videos/owner/welcome.mp4',
    durationSeconds: 120,
  },
  {
    id: 'owner-property-registration',
    kind: 'hands-on-task',
    titleEn: 'Register your property',
    titleSw: 'Sajili mali yako',
    descriptionEn: 'Capture property details, units, and amenities.',
    descriptionSw: 'Chukua maelezo ya mali, vyumba, na huduma.',
    expectedMinutes: 10,
    conceptIds: [],
    prerequisites: ['owner-welcome'],
    required: true,
    taskRef: 'task/register-property',
    successCriteria: ['property-created', 'at-least-one-unit'],
    blockOnCompletion: true,
  },
  {
    id: 'owner-rent-pricing',
    kind: 'ai-conversation',
    titleEn: 'Price your rent',
    titleSw: 'Weka bei ya kodi',
    descriptionEn: 'Mr. Mwikila suggests rent bands based on comparables.',
    descriptionSw: 'Mr. Mwikila anapendekeza bei ya kodi.',
    expectedMinutes: 8,
    conceptIds: ['rent_affordability', 'rent_escalation'],
    prerequisites: ['owner-property-registration'],
    required: true,
    personaId: 'mr-mwikila',
    openingPromptEn: 'What rent are you thinking for these units? I can check comparables in your district.',
    openingPromptSw: 'Kodi gani unafikiria? Naweza kulinganisha na mali nyingine.',
    evaluationRubric: ['rent-set', 'comparables-reviewed'],
  },
  {
    id: 'owner-tenant-acquisition',
    kind: 'reading',
    titleEn: 'How BOSSNYUMBA finds tenants',
    titleSw: 'Jinsi BOSSNYUMBA inavyotafuta wapangaji',
    descriptionEn: 'Understanding tenant vetting, waitlist, and acquisition.',
    descriptionSw: 'Elewa uchunguzi wa mpangaji na orodha ya kusubiri.',
    expectedMinutes: 6,
    conceptIds: [],
    prerequisites: ['owner-rent-pricing'],
    required: false,
    contentMdRef: 'docs/owner/tenant-acquisition.md',
    estimatedWordCount: 700,
  },
  {
    id: 'owner-quiz',
    kind: 'quiz',
    titleEn: 'Owner readiness check',
    titleSw: 'Ukaguzi wa utayari wa mmiliki',
    descriptionEn: 'Quick quiz to confirm you are ready.',
    descriptionSw: 'Jaribio la haraka.',
    expectedMinutes: 5,
    conceptIds: ['rent_affordability', 'rent_escalation'],
    prerequisites: ['owner-tenant-acquisition'],
    required: true,
    questionIds: ['q-owner-1', 'q-owner-2', 'q-owner-3'],
    passingScore: 66,
    maxAttempts: 3,
  },
];

const tenantOnboardingSteps: readonly JourneyStep[] = [
  {
    id: 'tenant-welcome',
    kind: 'video',
    titleEn: 'Welcome home',
    titleSw: 'Karibu nyumbani',
    descriptionEn: 'What BOSSNYUMBA does for you as a tenant.',
    descriptionSw: 'BOSSNYUMBA inakufanyia nini kama mpangaji.',
    expectedMinutes: 2,
    conceptIds: [],
    prerequisites: [],
    required: true,
    videoRef: 'videos/tenant/welcome.mp4',
    durationSeconds: 90,
  },
  {
    id: 'tenant-profile',
    kind: 'hands-on-task',
    titleEn: 'Complete your profile',
    titleSw: 'Kamilisha wasifu wako',
    descriptionEn: 'Identity, contact, emergency contact.',
    descriptionSw: 'Utambulisho, mawasiliano, dharura.',
    expectedMinutes: 5,
    conceptIds: [],
    prerequisites: ['tenant-welcome'],
    required: true,
    taskRef: 'task/complete-tenant-profile',
    successCriteria: ['profile-complete'],
    blockOnCompletion: false,
  },
  {
    id: 'tenant-lease-review',
    kind: 'reading',
    titleEn: 'Read your lease',
    titleSw: 'Soma mkataba wako',
    descriptionEn: 'Plain-language summary plus the full lease PDF.',
    descriptionSw: 'Muhtasari wa lugha rahisi na PDF kamili.',
    expectedMinutes: 8,
    conceptIds: ['deposit_structures'],
    prerequisites: ['tenant-profile'],
    required: true,
    contentMdRef: 'docs/tenant/lease-summary.md',
    estimatedWordCount: 500,
  },
  {
    id: 'tenant-first-payment',
    kind: 'hands-on-task',
    titleEn: 'Make your first payment',
    titleSw: 'Fanya malipo yako ya kwanza',
    descriptionEn: 'GePG, M-Pesa, Azam, or bank transfer.',
    descriptionSw: 'GePG, M-Pesa, Azam, au benki.',
    expectedMinutes: 6,
    conceptIds: ['gepg_reconciliation'],
    prerequisites: ['tenant-lease-review'],
    required: true,
    taskRef: 'task/make-first-payment',
    successCriteria: ['payment-received'],
    blockOnCompletion: false,
  },
];

const estateOfficerTrainingSteps: readonly JourneyStep[] = [
  { id: 'officer-role', kind: 'video', titleEn: 'Your role as estate officer', titleSw: 'Wajibu wako kama afisa wa mali', descriptionEn: 'How officers fit in the BOSSNYUMBA ops chain.', descriptionSw: 'Jinsi maofisa wanavyoingia katika mfumo.', expectedMinutes: 5, conceptIds: [], prerequisites: [], required: true, videoRef: 'videos/officer/role.mp4', durationSeconds: 180 },
  { id: 'officer-daily-rituals', kind: 'reading', titleEn: 'Daily rituals', titleSw: 'Tasriba za kila siku', descriptionEn: 'Morning checks, mid-day triage, end-of-day handover.', descriptionSw: 'Ukaguzi wa asubuhi, triage mchana, utoaji wa jioni.', expectedMinutes: 6, conceptIds: [], prerequisites: ['officer-role'], required: true, contentMdRef: 'docs/officer/daily-rituals.md', estimatedWordCount: 600 },
  { id: 'officer-tenant-relationships', kind: 'ai-conversation', titleEn: 'Tenant relationship basics', titleSw: 'Msingi wa uhusiano na mpangaji', descriptionEn: 'Practice handling a rude tenant scenario.', descriptionSw: 'Zoezi la kushughulikia mpangaji mkali.', expectedMinutes: 10, conceptIds: [], prerequisites: ['officer-daily-rituals'], required: true, personaId: 'mr-mwikila', openingPromptEn: 'Roleplay: a tenant is yelling about a water leak. Show me how you calm them down.', openingPromptSw: 'Mchezo: mpangaji anapiga kelele. Nionyeshe jinsi unavyomtuliza.', evaluationRubric: ['empathy', 'action', 'escalation-path'] },
  { id: 'officer-arrears-process', kind: 'reading', titleEn: 'Arrears ladder', titleSw: 'Ngazi za deni la kodi', descriptionEn: 'Reminder, warning, final notice, legal.', descriptionSw: 'Ukumbusho, onyo, tahadhari, sheria.', expectedMinutes: 7, conceptIds: ['rent_affordability'], prerequisites: ['officer-tenant-relationships'], required: true, contentMdRef: 'docs/officer/arrears-ladder.md', estimatedWordCount: 900 },
  { id: 'officer-maintenance-triage', kind: 'hands-on-task', titleEn: 'Triage a maintenance ticket', titleSw: 'Chagua tikiti ya matengenezo', descriptionEn: 'Classify severity and route.', descriptionSw: 'Panga ukali na mwelekeo.', expectedMinutes: 8, conceptIds: [], prerequisites: ['officer-arrears-process'], required: true, taskRef: 'task/triage-ticket', successCriteria: ['classification-correct', 'vendor-matched'], blockOnCompletion: false },
  { id: 'officer-inspection-walk', kind: 'video', titleEn: 'FAR inspection walkthrough', titleSw: 'Ziara ya ukaguzi wa FAR', descriptionEn: 'A step-by-step inspection demonstration.', descriptionSw: 'Maonyesho ya ukaguzi hatua kwa hatua.', expectedMinutes: 12, conceptIds: [], prerequisites: ['officer-maintenance-triage'], required: true, videoRef: 'videos/officer/far-inspection.mp4', durationSeconds: 720 },
  { id: 'officer-tender-basics', kind: 'reading', titleEn: 'Tender basics', titleSw: 'Msingi wa zabuni', descriptionEn: 'How we award contracts.', descriptionSw: 'Jinsi tunavyotoa mikataba.', expectedMinutes: 6, conceptIds: [], prerequisites: ['officer-inspection-walk'], required: true, contentMdRef: 'docs/officer/tenders.md', estimatedWordCount: 800 },
  { id: 'officer-compliance-101', kind: 'reading', titleEn: 'Compliance 101', titleSw: 'Utii 101', descriptionEn: 'What you must log and when.', descriptionSw: 'Nini cha kuandika na lini.', expectedMinutes: 5, conceptIds: [], prerequisites: ['officer-tender-basics'], required: true, contentMdRef: 'docs/officer/compliance-101.md', estimatedWordCount: 600 },
  { id: 'officer-payment-chase', kind: 'hands-on-task', titleEn: 'Practice an arrears call', titleSw: 'Zoezi la simu ya deni', descriptionEn: 'Record a mock call script and get AI feedback.', descriptionSw: 'Rekodi simu ya mchezo.', expectedMinutes: 10, conceptIds: [], prerequisites: ['officer-compliance-101'], required: true, taskRef: 'task/arrears-call-practice', successCriteria: ['script-recorded', 'ai-feedback-received'], blockOnCompletion: false },
  { id: 'officer-emergency-protocol', kind: 'video', titleEn: 'Emergency protocol', titleSw: 'Itifaki ya dharura', descriptionEn: 'Fire, flood, structural damage, medical.', descriptionSw: 'Moto, mafuriko, uharibifu, matibabu.', expectedMinutes: 6, conceptIds: [], prerequisites: ['officer-payment-chase'], required: true, videoRef: 'videos/officer/emergency.mp4', durationSeconds: 360 },
  { id: 'officer-swahili-estate-vocab', kind: 'reading', titleEn: 'Swahili estate vocabulary', titleSw: 'Msamiati wa mali kwa Kiswahili', descriptionEn: 'Key property-management Swahili terms.', descriptionSw: 'Maneno muhimu ya usimamizi wa mali.', expectedMinutes: 5, conceptIds: [], prerequisites: ['officer-emergency-protocol'], required: false, contentMdRef: 'docs/officer/swahili-vocab.md', estimatedWordCount: 400 },
  { id: 'officer-certification-quiz', kind: 'quiz', titleEn: 'Estate officer certification', titleSw: 'Cheti cha afisa wa mali', descriptionEn: 'Passing certifies you as an estate officer.', descriptionSw: 'Kupita kunakupa cheti.', expectedMinutes: 15, conceptIds: ['rent_affordability', 'deposit_structures', 'gepg_reconciliation'], prerequisites: ['officer-swahili-estate-vocab'], required: true, questionIds: ['q-off-1', 'q-off-2', 'q-off-3', 'q-off-4', 'q-off-5', 'q-off-6', 'q-off-7', 'q-off-8', 'q-off-9', 'q-off-10'], passingScore: 80, maxAttempts: 3 },
];

const migrationWizardSteps: readonly JourneyStep[] = [
  { id: 'mig-intro', kind: 'video', titleEn: 'Migrating from your old system', titleSw: 'Kuhamisha kutoka mfumo wako wa zamani', descriptionEn: 'What we need and how it works.', descriptionSw: 'Tunahitaji nini na inafanya kazi vipi.', expectedMinutes: 3, conceptIds: [], prerequisites: [], required: true, videoRef: 'videos/migration/intro.mp4', durationSeconds: 180 },
  { id: 'mig-upload-source', kind: 'hands-on-task', titleEn: 'Upload source data', titleSw: 'Pakua data ya chanzo', descriptionEn: 'CSV, Excel, or direct LPMS export.', descriptionSw: 'CSV, Excel, au LPMS.', expectedMinutes: 10, conceptIds: [], prerequisites: ['mig-intro'], required: true, taskRef: 'task/migration-upload', successCriteria: ['source-uploaded'], blockOnCompletion: true },
  { id: 'mig-field-mapping', kind: 'ai-conversation', titleEn: 'Map your fields', titleSw: 'Panga sehemu zako', descriptionEn: 'Mr. Mwikila helps map source columns to BOSSNYUMBA fields.', descriptionSw: 'Mr. Mwikila anakusaidia kupanga.', expectedMinutes: 15, conceptIds: [], prerequisites: ['mig-upload-source'], required: true, personaId: 'mr-mwikila', openingPromptEn: 'I see your file has columns like TenantName, UnitNo, RentKSh. Let me propose a mapping.', openingPromptSw: 'Ninaona faili lako lina TenantName, UnitNo, RentKSh. Naomba nipendekeze upangaji.', evaluationRubric: ['all-required-fields-mapped'] },
  { id: 'mig-validate', kind: 'hands-on-task', titleEn: 'Validate migrated data', titleSw: 'Thibitisha data iliyohamishwa', descriptionEn: 'Review a sample and approve.', descriptionSw: 'Kagua sampuli na kibali.', expectedMinutes: 8, conceptIds: [], prerequisites: ['mig-field-mapping'], required: true, taskRef: 'task/migration-validate', successCriteria: ['sample-approved'], blockOnCompletion: true },
];

const complianceSetupSteps: readonly JourneyStep[] = [
  { id: 'comp-country', kind: 'ai-conversation', titleEn: 'Which country rules apply?', titleSw: 'Sheria za nchi ipi zinatumika?', descriptionEn: 'Confirm country-specific compliance (TZA / KEN / UGA).', descriptionSw: 'Thibitisha utii wa nchi.', expectedMinutes: 4, conceptIds: [], prerequisites: [], required: true, personaId: 'mr-mwikila', openingPromptEn: 'Which country do you operate in? Tanzania, Kenya, Uganda, or Rwanda?', openingPromptSw: 'Unafanya kazi nchi gani?', evaluationRubric: ['country-captured'] },
  { id: 'comp-doc-templates', kind: 'hands-on-task', titleEn: 'Load compliance templates', titleSw: 'Pakia nakala za utii', descriptionEn: 'Auto-load country lease + compliance templates.', descriptionSw: 'Pakia nakala za nchi.', expectedMinutes: 3, conceptIds: [], prerequisites: ['comp-country'], required: true, taskRef: 'task/load-compliance-templates', successCriteria: ['templates-loaded'], blockOnCompletion: false },
  { id: 'comp-inspection-schedule', kind: 'hands-on-task', titleEn: 'Set inspection cadence', titleSw: 'Weka ratiba ya ukaguzi', descriptionEn: 'FAR, fire, water, electrical.', descriptionSw: 'FAR, moto, maji, umeme.', expectedMinutes: 5, conceptIds: [], prerequisites: ['comp-doc-templates'], required: true, taskRef: 'task/inspection-schedule', successCriteria: ['schedule-set'], blockOnCompletion: false },
  { id: 'comp-certify', kind: 'quiz', titleEn: 'Compliance readiness quiz', titleSw: 'Jaribio la utii', descriptionEn: 'Confirm understanding of country rules.', descriptionSw: 'Thibitisha utii.', expectedMinutes: 6, conceptIds: [], prerequisites: ['comp-inspection-schedule'], required: true, questionIds: ['q-comp-1', 'q-comp-2', 'q-comp-3'], passingScore: 70, maxAttempts: 3 },
];

export const JOURNEY_REGISTRY: readonly JourneyDefinition[] = [
  {
    id: 'admin-onboarding',
    version: '1.0.0',
    audience: 'admin',
    titleEn: 'Admin onboarding',
    titleSw: 'Uanzishaji wa msimamizi',
    summaryEn: 'Seven steps to set up BOSSNYUMBA for your estate.',
    summarySw: 'Hatua saba za kuanzisha BOSSNYUMBA.',
    totalExpectedMinutes: 60,
    steps: adminOnboardingSteps,
    countryScopes: ['TZA', 'KEN', 'UGA', 'RWA'],
  },
  {
    id: 'property-owner-onboarding',
    version: '1.0.0',
    audience: 'property-owner',
    titleEn: 'Property owner onboarding',
    titleSw: 'Uanzishaji wa mmiliki',
    summaryEn: 'Five steps to list your property and price it.',
    summarySw: 'Hatua tano za kuorodhesha mali yako.',
    totalExpectedMinutes: 32,
    steps: propertyOwnerOnboardingSteps,
    countryScopes: ['TZA', 'KEN', 'UGA', 'RWA'],
  },
  {
    id: 'tenant-onboarding',
    version: '1.0.0',
    audience: 'tenant',
    titleEn: 'Tenant onboarding',
    titleSw: 'Uanzishaji wa mpangaji',
    summaryEn: 'Four steps from welcome to first payment.',
    summarySw: 'Hatua nne hadi malipo ya kwanza.',
    totalExpectedMinutes: 21,
    steps: tenantOnboardingSteps,
    countryScopes: ['TZA', 'KEN', 'UGA', 'RWA'],
  },
  {
    id: 'estate-officer-training',
    version: '1.0.0',
    audience: 'estate-officer',
    titleEn: 'Estate officer certification',
    titleSw: 'Cheti cha afisa wa mali',
    summaryEn: 'Twelve-step certification for estate officers.',
    summarySw: 'Cheti cha hatua kumi na mbili.',
    totalExpectedMinutes: 95,
    steps: estateOfficerTrainingSteps,
    countryScopes: ['TZA', 'KEN', 'UGA', 'RWA'],
  },
  {
    id: 'migration-wizard',
    version: '1.0.0',
    audience: 'migration',
    titleEn: 'Migration wizard',
    titleSw: 'Uongozi wa uhamiaji',
    summaryEn: 'Bring your data from an old system into BOSSNYUMBA.',
    summarySw: 'Leta data yako ya zamani.',
    totalExpectedMinutes: 36,
    steps: migrationWizardSteps,
    countryScopes: ['TZA', 'KEN', 'UGA', 'RWA'],
  },
  {
    id: 'compliance-setup',
    version: '1.0.0',
    audience: 'compliance',
    titleEn: 'Compliance setup',
    titleSw: 'Uanzishaji wa utii',
    summaryEn: 'Country-specific compliance configuration.',
    summarySw: 'Usanidi wa utii wa nchi.',
    totalExpectedMinutes: 18,
    steps: complianceSetupSteps,
    countryScopes: ['TZA', 'KEN', 'UGA', 'RWA'],
  },
];

export function getJourney(journeyId: string): JourneyDefinition | undefined {
  return JOURNEY_REGISTRY.find((j) => j.id === journeyId);
}

export function listJourneysForAudience(
  audience: JourneyAudience,
): readonly JourneyDefinition[] {
  return JOURNEY_REGISTRY.filter((j) => j.audience === audience);
}

export function listJourneysForCountry(
  countryCode: string,
): readonly JourneyDefinition[] {
  return JOURNEY_REGISTRY.filter((j) => j.countryScopes.includes(countryCode));
}

export function getStep(
  journeyId: string,
  stepId: string,
): JourneyStep | undefined {
  const j = getJourney(journeyId);
  if (!j) return undefined;
  return j.steps.find((s) => s.id === stepId);
}
