/**
 * Contextual Chunker — Anthropic Contextual Retrieval pattern.
 *
 * Prepends a document-scoped 1-2 sentence context blurb to each chunk
 * BEFORE embedding. Anthropic's published data (Sept 2024) shows the
 * preface cuts top-20 retrieval failure by 35-49% on their RAG
 * benchmark. The preface is generated by an LLM with the full document
 * held in prompt cache, so the marginal cost per chunk approaches the
 * cached-read price (~$1 / 1M doc tokens).
 *
 * Design — pure orchestration module:
 *   - Takes raw chunks + full document text.
 *   - Calls a caller-supplied `contextualizeFn` once per chunk batch.
 *   - Returns each chunk paired with a short context summary plus the
 *     concatenated `embedText` field the embedder should ingest.
 *
 * Identity-fallback policy (ship before LLM keys):
 *   - When `skipLlm` is true, when the document text is empty, OR when
 *     no `contextualizeFn` is supplied (i.e. no brain wired in), we
 *     return identity chunks (`contextSummary = ''`,
 *     `embedText = chunkText`). RAG still works — just without the
 *     35-49% lift. This lets the property-management workspace ship the
 *     pipeline before Anthropic / OpenAI keys are provisioned.
 *
 * Ported from LITFIN `src/core/document-intelligence/contextual-rag/
 * contextual-chunker.ts` (268 LOC). LITFIN bound the default
 * contextualiser to `brain.think()`; the BOSSNYUMBA port stays
 * neutral — callers inject the LLM call so the module has no runtime
 * dependency on any specific provider.
 *
 * @module @bossnyumba/ai-copilot/retrieval/contextual-chunker
 */

import type { ContextualChunk } from './types.js';
import { logger } from '../logger.js';

// ===========================================================================
// Constants
// ===========================================================================

/** Soft cap on document length passed to the contextualiser prompt.
 *  Aligned with the Anthropic / OpenAI 200k input window. */
const MAX_DOC_CHARS_FOR_CONTEXT = 180_000;

/** Soft cap on the preface length we keep per chunk. The Anthropic
 *  recipe uses 50-100 tokens; ~400 chars covers that comfortably. */
const MAX_PREFACE_CHARS = 400;

/** Hard cap on the chunk text exposed in the contextualiser prompt. A
 *  leading slice is enough for the LLM to summarise the chunk's role. */
const MAX_CHUNK_PREVIEW_CHARS = 800;

/** Default batch size when the caller doesn't pass one. Keeps each
 *  LLM round-trip bounded so a 500-chunk document doesn't blow the
 *  wall-clock budget. */
const DEFAULT_BATCH_SIZE = 6;

// ===========================================================================
// Types
// ===========================================================================

/**
 * Signature of the per-batch contextualiser. Receives the document
 * preview + the chunk previews; returns one summary per chunk.
 *
 * Callers in production wire this to a Haiku / GPT-4o-mini call with
 * the document held in prompt cache. Tests inject a stub.
 */
export type ContextualizeFn = (input: {
  readonly documentText: string;
  readonly chunks: ReadonlyArray<{
    readonly chunkIndex: number;
    readonly preview: string;
  }>;
}) => Promise<
  ReadonlyArray<{ readonly chunkIndex: number; readonly summary: string }>
>;

export interface ContextualizeOptions {
  /** Override the LLM batch size. Default 6. */
  readonly batchSize?: number;
  /** Override the per-chunk preface cap. Default 400 chars. */
  readonly maxPrefaceChars?: number;
  /** Skip the LLM entirely and return identity chunks. Useful for unit
   *  tests + dev mode without an API key. */
  readonly skipLlm?: boolean;
  /** Inject a custom contextualiser. When omitted, the module returns
   *  identity chunks (the identity-fallback policy). */
  readonly contextualizeFn?: ContextualizeFn;
}

// ===========================================================================
// Public API
// ===========================================================================

/**
 * Contextualise a set of chunks against the full document.
 *
 * Returns one `ContextualChunk` per input chunk. Order is preserved.
 * Never throws — on LLM failure each affected batch degrades to
 * identity chunks so the downstream embedder always has something to
 * ingest.
 */
export async function contextualizeChunks(
  documentText: string,
  rawChunks: ReadonlyArray<string>,
  options: ContextualizeOptions = {},
): Promise<ReadonlyArray<ContextualChunk>> {
  if (rawChunks.length === 0) return [];
  if (!documentText || documentText.trim().length === 0) {
    return rawChunks.map((text, idx) => identityChunk(idx, text));
  }
  if (options.skipLlm === true) {
    return rawChunks.map((text, idx) => identityChunk(idx, text));
  }
  if (!options.contextualizeFn) {
    // No LLM wired in — degrade gracefully so the pipeline still ships.
    return rawChunks.map((text, idx) => identityChunk(idx, text));
  }

  const docPreview = truncateForContext(
    documentText,
    MAX_DOC_CHARS_FOR_CONTEXT,
  );
  const batchSize = Math.max(1, options.batchSize ?? DEFAULT_BATCH_SIZE);
  const prefaceCap = Math.max(
    40,
    options.maxPrefaceChars ?? MAX_PREFACE_CHARS,
  );
  const contextualizeFn = options.contextualizeFn;

  const summaries = new Map<number, string>();
  for (let i = 0; i < rawChunks.length; i += batchSize) {
    const slice = rawChunks.slice(i, i + batchSize).map((text, j) => ({
      chunkIndex: i + j,
      preview: truncateForContext(text, MAX_CHUNK_PREVIEW_CHARS),
    }));

    try {
      const batch = await contextualizeFn({
        documentText: docPreview,
        chunks: slice,
      });
      for (const entry of batch) {
        const trimmed = entry.summary.trim().slice(0, prefaceCap);
        if (trimmed.length > 0) {
          summaries.set(entry.chunkIndex, trimmed);
        }
      }
    } catch (err) {
      // Single batch failure does not poison the whole document.
      // Affected slice falls through to identity chunks.
      logger.error('[retrieval/contextual-chunker] batch failed — slice returns identity', {
          startIndex: i,
          error: err instanceof Error ? err.message : String(err),
        });
    }
  }

  return rawChunks.map((text, idx) => {
    const summary = summaries.get(idx) ?? '';
    return {
      chunkIndex: idx,
      chunkText: text,
      contextSummary: summary,
      embedText: summary.length > 0 ? `${summary}\n\n${text}` : text,
    };
  });
}

// ===========================================================================
// Internal helpers
// ===========================================================================

function identityChunk(index: number, text: string): ContextualChunk {
  return {
    chunkIndex: index,
    chunkText: text,
    contextSummary: '',
    embedText: text,
  };
}

/** Keep the leading portion when over budget. Cover-page + summary
 *  usually carries more signal than appendices. */
function truncateForContext(text: string, cap: number): string {
  if (text.length <= cap) return text;
  return text.slice(0, cap);
}

/**
 * Parse a `[{chunkIndex, summary}]` JSON array from an LLM response.
 * Tolerant of prose preambles around the JSON. Exported because both
 * the prompt-cached default contextualiser AND consumer-supplied
 * wrappers (e.g. a Haiku adapter in `apps/`) need to share the parser.
 */
export function parseContextSummaries(
  text: string,
  expectedIndices: ReadonlyArray<number>,
): ReadonlyArray<{ chunkIndex: number; summary: string }> {
  if (!text) return [];
  const trimmed = text.trim();
  const jsonStart = trimmed.indexOf('[');
  const jsonEnd = trimmed.lastIndexOf(']');
  if (jsonStart < 0 || jsonEnd <= jsonStart) return [];
  const raw = trimmed.slice(jsonStart, jsonEnd + 1);
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return [];
  }
  if (!Array.isArray(parsed)) return [];
  const expected = new Set(expectedIndices);
  const out: Array<{ chunkIndex: number; summary: string }> = [];
  for (const entry of parsed) {
    if (typeof entry !== 'object' || entry === null) continue;
    const e = entry as { chunkIndex?: unknown; summary?: unknown };
    const idx = typeof e.chunkIndex === 'number' ? e.chunkIndex : NaN;
    const summary = typeof e.summary === 'string' ? e.summary : '';
    if (!Number.isInteger(idx) || !expected.has(idx)) continue;
    if (summary.trim().length === 0) continue;
    out.push({ chunkIndex: idx, summary });
  }
  return out;
}
