/**
 * Brand / locale labels for the visible watermark + prompt prefix.
 *
 * EN/SW absolute toggle (hard rail): the active locale selects a SINGLE
 * language label — never mixed. The label is the brand string composited
 * onto public-facing assets; the prefix is prepended to the provider
 * prompt so generated copy stays in-locale.
 *
 * @module @bossnyumba/media-engine/brand/brand-label
 */

import type { MediaDomain, MediaLocale } from '../types.js';

interface LocaleStrings {
  readonly watermark: string;
  readonly promptPrefix: string;
}

/** Per-domain, per-locale strings. Complete EN + SW (no mixing). */
const STRINGS: Readonly<
  Record<MediaDomain, Record<MediaLocale, LocaleStrings>>
> = Object.freeze({
  mining_estate: Object.freeze({
    en: { watermark: 'Generated by BossNyumba', promptPrefix: 'BossNyumba mining estate. ' },
    sw: {
      watermark: 'Imetengenezwa na BossNyumba',
      promptPrefix: 'Shamba la madini la BossNyumba. ',
    },
  }),
  real_estate: Object.freeze({
    en: {
      watermark: 'Generated by BN',
      promptPrefix: 'BN real estate property. ',
    },
    sw: {
      watermark: 'Imetengenezwa na BN',
      promptPrefix: 'Mali ya BN ya nyumba. ',
    },
  }),
});

export function watermarkLabel(
  domain: MediaDomain,
  locale: MediaLocale,
): string {
  return STRINGS[domain][locale].watermark;
}

export function promptPrefix(
  domain: MediaDomain,
  locale: MediaLocale,
): string {
  return STRINGS[domain][locale].promptPrefix;
}
