/**
 * Integration test — chatbot-feel response generated by an LLM passes
 * through the pre-send audit, gets cleaner, intervention is logged, admin
 * dashboard data reflects the trace.
 */
import { describe, it, expect, beforeEach } from "vitest";
import {
  runPreSendAudit,
  listInterventions,
  getSessionStats,
  _resetAuditLog,
} from "../index";
import type { ConversationContext } from "../types";

describe("pre-send-audit integration", () => {
  beforeEach(() => _resetAuditLog());

  it("strips chatbot-feel response, logs interventions, and updates stats", async () => {
    const ctx: ConversationContext = {
      session_id: "session-int-1",
      turn_index: 3,
      portal: "borrower",
      user_message: "Should I take the 12-month or 24-month loan?",
      recent_turns: [
        {
          role: "user",
          content: "I have a Mwananchi shop with 5,123,000 TZS in revenue.",
          turn_index: 0,
        },
        {
          role: "assistant",
          content: "Tell me more about your monthly cash flow.",
          turn_index: 1,
        },
        {
          role: "user",
          content: "Should I take the 12-month or 24-month loan?",
          turn_index: 2,
        },
      ],
      known_user_facts: [
        { key: "shop_name", value: "Mwananchi", source_turn: 0 },
        { key: "revenue", value: "5,123,000", source_turn: 0 },
      ],
      user_asked_for_opinion: true,
    };

    const candidate =
      "Great question! Sure, I'd be happy to help. " +
      "It might be a 12-month or perhaps a 24-month loan, possibly depending on your needs. " +
      "Hope this helps! Is there anything else I can help you with?";

    const result = await runPreSendAudit(candidate, ctx, {
      enable_audit_log: true,
      turn_kind: "decision",
    });

    // Anti-pattern strip removed openers and closers.
    expect(result.final.toLowerCase()).not.toMatch(/^great question/);
    expect(result.final.toLowerCase()).not.toMatch(
      /is there anything else i can help/,
    );
    expect(result.final.toLowerCase()).not.toMatch(/hope this helps/);

    // Position-taker fired (opinion asked, response was hedge soup).
    expect(result.regen_requested).toBe(true);
    expect(result.regen_instruction).not.toBeNull();

    // Audit log contains entries.
    const interventions = listInterventions("session-int-1");
    expect(interventions.length).toBeGreaterThanOrEqual(2);
    expect(interventions.some((i) => i.guard === "anti-pattern-stripper")).toBe(
      true,
    );
    expect(interventions.some((i) => i.guard === "position-taker")).toBe(true);

    // Stats reflect the strip + position intervention.
    const stats = getSessionStats("session-int-1");
    expect(stats).not.toBeNull();
    expect(stats?.anti_pattern_strips ?? 0).toBeGreaterThanOrEqual(1);
    expect(stats?.position_taking_interventions ?? 0).toBeGreaterThanOrEqual(1);
    expect(stats!.chatbot_feel_score).toBeGreaterThan(0);
  });

  it("invokes regen callback when configured and replaces the response", async () => {
    const ctx: ConversationContext = {
      session_id: "session-int-2",
      turn_index: 2,
      portal: "borrower",
      user_message: "Should I refinance now?",
      recent_turns: [
        { role: "user", content: "Should I refinance now?", turn_index: 0 },
      ],
      user_asked_for_opinion: true,
    };
    const candidate =
      "It might be wise, perhaps, possibly, depending on rates.";

    const result = await runPreSendAudit(candidate, ctx, {
      enable_audit_log: true,
      request_regen_callback: async () =>
        "I recommend refinancing now because rates rose 1.5% this month. The tradeoff: a small early-repayment fee.",
    });

    expect(result.final.toLowerCase()).toMatch(/i recommend/);
    expect(result.regen_requested).toBe(false);
  });

  it("synthetic 100-turn sweep produces measurable interventions", async () => {
    const baseUser =
      "Should I take this loan? I run a Mwananchi shop with 4,200,000 TZS revenue.";
    const chatbotResponses = [
      "Sure! That's a great question.",
      "Of course, I'd be happy to help. It could be A or B, perhaps.",
      "Absolutely! Hope this helps!",
      "Got it. Is there anything else I can help you with?",
      "I apologize for any confusion. It might be wise.",
    ];

    let strips = 0;
    let positionFixes = 0;
    let totalInterventions = 0;

    for (let i = 0; i < 100; i++) {
      const ctx: ConversationContext = {
        session_id: `bulk-${i}`,
        turn_index: 2,
        portal: "borrower",
        user_message: baseUser,
        recent_turns: [{ role: "user", content: baseUser, turn_index: 0 }],
        known_user_facts: [
          { key: "shop_name", value: "Mwananchi", source_turn: 0 },
          { key: "revenue", value: "4,200,000", source_turn: 0 },
        ],
        user_asked_for_opinion: true,
      };
      const candidate = chatbotResponses[i % chatbotResponses.length];
      const r = await runPreSendAudit(candidate, ctx, {
        enable_audit_log: true,
        turn_kind: "decision",
      });
      if (r.stats.anti_pattern_strips > 0) strips++;
      if (r.stats.position_taking_interventions > 0) positionFixes++;
      totalInterventions += r.interventions.length;
    }

    expect(strips).toBeGreaterThan(80); // most chatbot responses get stripped
    expect(positionFixes).toBeGreaterThan(50); // most asked for opinion
    expect(totalInterventions).toBeGreaterThan(150);
  });
});
