/**
 * Finance-related glossary. Priority category — rent/arrears/charges
 * vocabulary is used across collection workflows, legal-drafter output,
 * and owner-facing reporting, so curation quality here has direct
 * downstream impact.
 */

import { buildEntries, enOnlyBatch, type EntrySpec } from './helpers.js';
import type { GlossaryEntry } from '../types.js';

const CORE_SPECS: readonly EntrySpec[] = [
  {
    id: 'finance.rent',
    en: 'rent',
    def: 'The periodic sum payable by a tenant to a landlord under a lease or tenancy.',
    cat: 'finance',
    juris: ['GB', 'KE', 'TZ', 'UG', 'US', 'DE', 'KR', 'JP', 'FR', 'AE', 'IN', 'SG', 'AU', 'CA'],
    t: {
      sw: 'kodi',
      ar: 'إيجار',
      fr: 'loyer',
      de: 'Miete',
      ko: '임대료',
      ja: '賃料',
      pt: 'aluguel',
      es: 'renta',
      zh: '租金',
      hi: 'किराया',
    },
  },
  {
    id: 'finance.arrears',
    en: 'arrears',
    def: 'Rent or charges that are overdue and unpaid.',
    cat: 'finance',
    juris: ['GB', 'KE', 'TZ', 'UG', 'US', 'DE', 'KR', 'JP', 'FR', 'IN', 'SG', 'AU'],
    t: {
      sw: 'madeni ya kodi',
      ar: 'متأخرات',
      fr: 'arriérés',
      de: 'Mietrückstand',
      ko: '연체금',
      ja: '滞納',
      pt: 'atrasos',
      es: 'atrasos',
      zh: '欠款',
      hi: 'बकाया',
    },
    cite: { jurisdiction: 'KE', statuteRef: 'Cap 296', section: 's.4', year: 1959 },
  },
  {
    id: 'finance.deposit',
    en: 'security deposit',
    def: 'A refundable sum held by a landlord as security against tenant default or damage.',
    cat: 'finance',
    juris: ['GB', 'KE', 'TZ', 'US', 'DE', 'KR', 'JP', 'FR', 'AE', 'IN', 'SG', 'AU'],
    t: {
      sw: 'amana ya usalama',
      ar: 'تأمين',
      fr: 'dépôt de garantie',
      de: 'Kaution',
      ko: '보증금',
      ja: '敷金',
      pt: 'caução',
      es: 'fianza',
      zh: '押金',
      hi: 'प्रतिभूति जमा',
    },
    cite: { jurisdiction: 'DE', statuteRef: 'BGB', section: '§551', year: 2002 },
  },
  {
    id: 'finance.service_charge',
    en: 'service charge',
    def: 'Periodic sum payable by occupiers to fund shared services (cleaning, security, utilities).',
    cat: 'finance',
    juris: ['GB', 'KE', 'UG', 'AE', 'IN', 'SG', 'ZA'],
    t: {
      sw: 'ada ya huduma',
      ar: 'رسوم الخدمات',
      fr: 'charges de copropriété',
      de: 'Nebenkosten',
      pt: 'taxa de condomínio',
      es: 'cuota de servicios',
      zh: '服务费',
      hi: 'सेवा शुल्क',
    },
  },
  {
    id: 'finance.ground_rent',
    en: 'ground rent',
    def: 'A periodic sum paid by a long-leaseholder to the freeholder for the use of land.',
    cat: 'finance',
    juris: ['GB', 'KE', 'IN', 'SG'],
    t: {
      sw: 'kodi ya ardhi',
      ar: 'إيجار الأرض',
      fr: 'redevance foncière',
      de: 'Erbbauzins',
      zh: '地租',
      hi: 'भू-किराया',
    },
  },
  {
    id: 'finance.garnishee_order',
    en: 'garnishee order',
    def: 'A court order attaching a debt owed to the tenant (e.g. salary) to satisfy rent arrears.',
    cat: 'finance',
    juris: ['KE', 'TZ', 'UG', 'GB', 'IN', 'ZA'],
    t: {
      sw: 'amri ya kukata mshahara',
      ar: 'أمر حجز',
      fr: 'saisie-arrêt',
      de: 'Pfändungsbeschluss',
      hi: 'गारनिशी आदेश',
    },
    cite: { jurisdiction: 'KE', statuteRef: 'CPR Order 22', section: 'r.1', year: 2010 },
  },
  {
    id: 'finance.distress_for_rent',
    en: 'distress for rent',
    def: 'Common-law remedy by which a landlord seizes tenant goods to cover overdue rent.',
    cat: 'finance',
    juris: ['KE', 'UG', 'TZ'],
    cite: { jurisdiction: 'KE', statuteRef: 'Cap 293', section: 's.3', year: 1938 },
    t: { sw: 'kudai kwa nguvu' },
  },
  {
    id: 'finance.escalation',
    en: 'rent escalation',
    def: 'Agreed periodic increase of rent tied to inflation, index, or fixed percentage.',
    cat: 'finance',
    juris: ['KE', 'GB', 'US', 'AE', 'IN', 'SG', 'ZA'],
    t: {
      sw: 'ongezeko la kodi',
      ar: 'زيادة الإيجار',
      fr: 'indexation du loyer',
      de: 'Mietanpassung',
      pt: 'reajuste de aluguel',
      es: 'ajuste de renta',
    },
  },
  {
    id: 'finance.chargeback',
    en: 'chargeback',
    def: 'Reversal of a card payment disputed by the cardholder.',
    cat: 'finance',
    juris: ['GB', 'KE', 'US', 'DE', 'IN', 'SG'],
  },
  {
    id: 'finance.late_fee',
    en: 'late fee',
    def: 'Fee charged for rent paid after the contractual due date.',
    cat: 'finance',
    juris: ['US', 'GB', 'KE', 'AE', 'IN', 'SG', 'AU'],
    t: {
      sw: 'faini ya kuchelewa',
      ar: 'غرامة تأخير',
      fr: 'pénalité de retard',
      de: 'Verzugspauschale',
    },
  },
];

const EXTRA_ROWS: ReadonlyArray<readonly [string, string, string, ReadonlyArray<string>?]> = [
  ['finance.invoice', 'invoice', 'Itemised statement of charges sent to a payer.'],
  ['finance.receipt', 'receipt', 'Written acknowledgement of payment received.'],
  ['finance.statement', 'statement of account', 'Periodic summary of charges and payments on an account.'],
  ['finance.dunning_letter', 'dunning letter', 'Formal notice reminding a debtor of overdue balance.'],
  ['finance.payment_plan', 'payment plan', 'Agreed schedule to clear an overdue balance in instalments.'],
  ['finance.ledger', 'ledger', 'Chronological record of financial transactions on an account.'],
  ['finance.reconciliation', 'reconciliation', 'Matching of internal records against a counter-party statement.'],
  ['finance.write_off', 'write-off', 'Accounting action to derecognise a receivable deemed uncollectable.'],
  ['finance.accrual', 'accrual', 'Expense or revenue recognised before cash movement.'],
  ['finance.prepayment', 'prepayment', 'Rent or charge paid before the due date.'],
  ['finance.overpayment', 'overpayment', 'Payment exceeding the amount due.'],
  ['finance.credit_note', 'credit note', 'Document reducing the receivable owed by the payer.'],
  ['finance.debit_note', 'debit note', 'Document increasing the receivable owed by the payer.'],
  ['finance.trust_account', 'trust account', 'Segregated account holding funds owed to another party.'],
  ['finance.client_account', 'client account', 'Agent account holding deposits and rent for owners.'],
  ['finance.commission', 'commission', 'Fee paid to an agent calculated as a percentage of rent or sale.'],
  ['finance.management_fee', 'management fee', 'Fee for ongoing property-management services.'],
  ['finance.letting_fee', 'letting fee', 'One-off fee for finding and placing a tenant.'],
  ['finance.renewal_fee', 'renewal fee', 'Fee for re-letting to an existing tenant.'],
  ['finance.void_period', 'void period', 'Period during which a unit is untenanted and produces no rent.'],
  ['finance.turnover_rent', 'turnover rent', 'Rent calculated as a percentage of tenant trading revenue.'],
  ['finance.stepped_rent', 'stepped rent', 'Rent schedule with fixed increases at defined dates.'],
  ['finance.rent_free_period', 'rent-free period', 'Interval during which rent is waived as a letting incentive.'],
  ['finance.deposit_protection', 'deposit protection scheme', 'Statutory scheme safeguarding tenant deposits.', ['GB']],
  ['finance.section_8_notice', 'Section 8 notice', 'Landlord notice of breach of tenancy.', ['GB']],
  ['finance.section_21_notice', 'Section 21 notice', 'Landlord no-fault notice to end an AST.', ['GB']],
  ['finance.council_tax', 'council tax', 'Local-authority property tax on residential premises.', ['GB']],
  ['finance.property_tax', 'property tax', 'Ad-valorem tax on real property.', ['US', 'KE', 'AE', 'IN']],
  ['finance.stamp_duty', 'stamp duty', 'Tax on certain legal instruments including leases.', ['GB', 'IN', 'KE', 'SG']],
  ['finance.land_rate', 'land rates', 'Annual municipal charge on freehold or leasehold land.', ['KE', 'UG', 'TZ']],
  ['finance.vat', 'VAT', 'Value-added tax levied on supplies of goods and services.'],
  ['finance.gst', 'GST', 'Goods and services tax.', ['IN', 'SG', 'AU', 'CA']],
  ['finance.withholding_tax', 'withholding tax', 'Tax withheld at source on rent paid to a non-resident landlord.', ['KE', 'UG', 'TZ', 'US']],
  ['finance.capital_allowance', 'capital allowance', 'Tax deduction for depreciation of capital assets.'],
  ['finance.rent_review', 'rent review', 'Contractual re-calculation of rent at defined intervals.'],
  ['finance.open_market_rent', 'open-market rent', 'Rent obtainable for premises let on arm’s-length terms.'],
  ['finance.indexation', 'indexation', 'Adjustment of rent linked to a published price index.'],
  ['finance.cpi_adjustment', 'CPI adjustment', 'Rent revision tied to the consumer price index.'],
  ['finance.default_interest', 'default interest', 'Interest charged on overdue sums at a contractual rate.'],
  ['finance.retention', 'retention', 'Sum withheld from a contractor pending completion defects.'],
];

export const FINANCE_ENTRIES: readonly GlossaryEntry[] = Object.freeze([
  ...buildEntries(CORE_SPECS),
  ...enOnlyBatch('finance', ['GB', 'KE', 'US'], EXTRA_ROWS),
]);
