/**
 * Tenancy-related glossary (300+ termIds).
 *
 * Priority category — 50 most-used terms carry curated translations
 * across all 11 locales. The remainder use English-only stubs with a
 * `// TODO-L18N` marker so the gap is visible in code review.
 *
 * Citations refer to real statutes:
 *   - KE: Landlord & Tenant (Shops, Hotels and Catering Establishments)
 *         Act Cap 301; Rent Restriction Act Cap 296;
 *         Distress for Rent Act Cap 293.
 *   - TZ: Land Act 1999; Law of Marriage Act 1971 §114 (matrimonial home).
 *   - DE: BGB §§535-578 (Miete / Wohnraummiete).
 *   - KR: 주택임대차보호법 (Housing Lease Protection Act).
 *   - JP: 借地借家法 (Land and Building Lease Act).
 *   - GB: Housing Act 1988; Housing Act 2004 (HMO).
 *   - FR: Loi 89-462 du 6 juillet 1989.
 */

import { buildEntries, enOnlyBatch, type EntrySpec } from './helpers.js';
import type { GlossaryEntry } from '../types.js';

const CORE_SPECS: readonly EntrySpec[] = [
  {
    id: 'tenancy.lease',
    en: 'lease',
    def: 'A contract granting exclusive possession of land or premises for a defined term in return for rent.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'TZ', 'UG', 'ZA', 'US', 'DE', 'KR', 'JP', 'FR', 'AE', 'IN', 'SG', 'AU', 'CA'],
    t: {
      sw: 'ukodishaji',
      ar: 'عقد إيجار',
      fr: 'bail',
      de: 'Mietvertrag',
      ko: '임대차',
      ja: '賃貸借',
      pt: 'arrendamento',
      es: 'arrendamiento',
      zh: '租约',
      hi: 'पट्टा',
    },
    cite: { jurisdiction: 'KE', statuteRef: 'Cap 301', section: 's.2', year: 1965 },
    syn: ['tenancy agreement', 'rental contract'],
    related: ['tenancy.tenancy', 'tenancy.licence'],
  },
  {
    id: 'tenancy.tenancy',
    en: 'tenancy',
    def: 'The legal relationship between a landlord and tenant arising from a lease or periodic rental arrangement.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'TZ', 'UG', 'US', 'DE', 'KR', 'JP', 'FR', 'IN', 'SG', 'AU', 'CA'],
    t: {
      sw: 'upangaji',
      ar: 'إيجار',
      fr: 'location',
      de: 'Mietverhältnis',
      ko: '임차',
      ja: '賃借',
      pt: 'locação',
      es: 'tenencia',
      zh: '租赁',
      hi: 'किरायेदारी',
    },
  },
  {
    id: 'tenancy.landlord',
    en: 'landlord',
    def: 'The owner or holder of an interest in land who grants a lease or tenancy to another.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'TZ', 'UG', 'US', 'DE', 'KR', 'JP', 'FR', 'IN', 'SG', 'AU', 'CA', 'AE', 'ZA', 'BR'],
    t: {
      sw: 'mwenye nyumba',
      ar: 'مالك العقار',
      fr: 'bailleur',
      de: 'Vermieter',
      ko: '임대인',
      ja: '賃貸人',
      pt: 'locador',
      es: 'arrendador',
      zh: '房东',
      hi: 'मकान मालिक',
    },
    cite: { jurisdiction: 'DE', statuteRef: 'BGB', section: '§535(1)', year: 2002 },
  },
  {
    id: 'tenancy.tenant',
    en: 'tenant',
    def: 'The party who holds possession of land or premises under a lease or tenancy in return for rent.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'TZ', 'UG', 'US', 'DE', 'KR', 'JP', 'FR', 'IN', 'SG', 'AU', 'CA', 'AE', 'ZA', 'BR'],
    t: {
      sw: 'mpangaji',
      ar: 'مستأجر',
      fr: 'locataire',
      de: 'Mieter',
      ko: '임차인',
      ja: '賃借人',
      pt: 'inquilino',
      es: 'arrendatario',
      zh: '租客',
      hi: 'किरायेदार',
    },
  },
  {
    id: 'tenancy.sublease',
    en: 'sublease',
    def: 'A lease granted by a tenant to a sub-tenant out of the residue of the head lease term.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'TZ', 'US', 'DE', 'KR', 'JP', 'FR', 'IN', 'SG', 'AU', 'CA'],
    t: {
      sw: 'ukodishaji mdogo',
      ar: 'إيجار من الباطن',
      fr: 'sous-location',
      de: 'Untermiete',
      ko: '전대차',
      ja: '転貸借',
      pt: 'sublocação',
      es: 'subarriendo',
      zh: '转租',
      hi: 'उप-पट्टा',
    },
    cite: { jurisdiction: 'DE', statuteRef: 'BGB', section: '§540', year: 2002 },
    syn: ['subletting'],
  },
  {
    id: 'tenancy.licence',
    en: 'licence',
    def: 'A permission to occupy premises without an exclusive possessory interest; not a lease.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'US', 'SG', 'IN', 'AU', 'CA'],
    t: {
      sw: 'leseni ya makazi',
      ar: 'ترخيص إشغال',
      fr: 'autorisation d’occupation',
      de: 'Nutzungserlaubnis',
      ko: '사용허가',
      ja: '使用許可',
      pt: 'licença de ocupação',
      es: 'licencia de ocupación',
      zh: '使用许可',
      hi: 'कब्जा अनुज्ञप्ति',
    },
    notes: 'In English common law Street v Mountford (1985) distinguishes lease vs licence by exclusive possession.',
  },
  {
    id: 'tenancy.assignment',
    en: 'assignment',
    def: 'Transfer by a tenant of its entire remaining leasehold interest to a third party.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'US', 'CA', 'AU', 'SG'],
    t: {
      sw: 'uhamisho wa ukodishaji',
      ar: 'إحالة عقد إيجار',
      fr: 'cession de bail',
      de: 'Mietübertragung',
      ko: '임차권 양도',
      ja: '賃借権譲渡',
      pt: 'cessão do arrendamento',
      es: 'cesión del arriendo',
      zh: '租赁权转让',
      hi: 'पट्टा हस्तांतरण',
    },
  },
  {
    id: 'tenancy.surrender',
    en: 'surrender',
    def: 'Mutual termination of a lease by the tenant yielding possession back to the landlord before expiry.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'US', 'CA', 'AU', 'SG'],
    t: {
      sw: 'kusalimisha ukodishaji',
      ar: 'تنازل عن الإيجار',
      fr: 'remise du bail',
      de: 'Rückgabe des Mietverhältnisses',
      ko: '임대차 반환',
      ja: '賃貸借解除による返還',
      pt: 'entrega antecipada',
      es: 'renuncia anticipada',
      zh: '提前退租',
      hi: 'पट्टा समर्पण',
    },
  },
  {
    id: 'tenancy.forfeiture',
    en: 'forfeiture',
    def: 'A landlord’s right to re-enter and terminate a lease on breach by the tenant.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'SG', 'AU', 'IN'],
    t: {
      sw: 'kunyanganywa ukodishaji',
      ar: 'إسقاط حق الإيجار',
      fr: 'déchéance du bail',
      de: 'Verwirkung',
      ko: '임대차 상실',
      ja: '賃借権喪失',
      pt: 'perda do arrendamento',
      es: 'resolución por incumplimiento',
      zh: '没收租权',
      hi: 'पट्टे की जब्ती',
    },
    cite: { jurisdiction: 'GB', statuteRef: 'Law of Property Act', section: 's.146', year: 1925 },
  },
  {
    id: 'tenancy.distress',
    en: 'distress for rent',
    def: 'Common-law and statutory remedy by which a landlord seizes the tenant’s chattels on the demised premises to satisfy rent arrears.',
    cat: 'tenancy',
    juris: ['KE', 'UG', 'TZ', 'GB'],
    t: {
      sw: 'kukamata mali kwa kodi',
      ar: 'الحجز لاستيفاء الإيجار',
      fr: 'saisie-gagerie',
      de: 'Vermieterpfandrecht',
      ko: '임료 체납 물건 압류',
      ja: '家賃滞納動産差押',
      pt: 'penhora por aluguer',
      es: 'embargo por rentas',
      zh: '欠租扣押',
      hi: 'किराया वसूली ज़ब्ती',
    },
    cite: { jurisdiction: 'KE', statuteRef: 'Cap 293', section: 's.3', year: 1930 },
    notes: 'Abolished in England & Wales by the Tribunals, Courts and Enforcement Act 2007; still in force in KE and UG.',
  },
  {
    id: 'tenancy.holding_over',
    en: 'holding over',
    def: 'Continued occupation by the tenant after the contractual term has ended, with or without the landlord’s consent.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'US', 'SG', 'AU', 'IN'],
    t: {
      sw: 'kubaki baada ya muda',
      ar: 'بقاء بعد انتهاء العقد',
      fr: 'maintien dans les lieux',
      de: 'Fortsetzung nach Ablauf',
      ko: '기간만료 후 계속 점유',
      ja: '期間満了後居住継続',
      pt: 'permanência após termo',
      es: 'permanencia tras el vencimiento',
      zh: '期满续占',
      hi: 'अवधि के बाद कब्जा',
    },
  },
  {
    id: 'tenancy.yielding_up',
    en: 'yielding up',
    def: 'The covenant or obligation on the tenant to return the premises to the landlord at the end of the term in the required state of repair.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'SG', 'AU'],
    t: {
      sw: 'kurudisha jengo',
      ar: 'تسليم المأجور',
      fr: 'restitution des lieux',
      de: 'Rückgabepflicht',
      ko: '목적물 반환',
      ja: '物件返還',
      pt: 'restituição do imóvel',
      es: 'entrega del inmueble',
      zh: '物业返还',
      hi: 'स्थान वापसी',
    },
  },
  {
    id: 'tenancy.rent_review',
    en: 'rent review',
    def: 'A contractual mechanism by which rent is periodically adjusted (typically to market rent or by indexation).',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'SG', 'AU', 'AE', 'DE', 'FR'],
    t: {
      sw: 'mapitio ya kodi',
      ar: 'مراجعة الإيجار',
      fr: 'révision du loyer',
      de: 'Mietanpassung',
      ko: '임대료 재조정',
      ja: '賃料改定',
      pt: 'revisão da renda',
      es: 'revisión de la renta',
      zh: '租金复核',
      hi: 'किराया समीक्षा',
    },
    cite: { jurisdiction: 'DE', statuteRef: 'BGB', section: '§§557-561', year: 2002 },
  },
  {
    id: 'tenancy.break_clause',
    en: 'break clause',
    def: 'A contractual right to terminate a lease early on notice, exercisable by one or both parties.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'SG', 'AU', 'AE'],
    t: {
      sw: 'kipengele cha kuvunja',
      ar: 'شرط إنهاء مبكر',
      fr: 'clause résolutoire',
      de: 'Kündigungsklausel',
      ko: '중도해지 조항',
      ja: '中途解約条項',
      pt: 'cláusula de denúncia',
      es: 'cláusula de resolución',
      zh: '中止条款',
      hi: 'विच्छेद धारा',
    },
  },
  {
    id: 'tenancy.renewal',
    en: 'lease renewal',
    def: 'Extension or re-grant of a lease on or after its expiry, often on negotiated or statutory terms.',
    cat: 'tenancy',
    juris: ['KE', 'GB', 'US', 'KR', 'JP', 'DE', 'FR', 'SG', 'AE', 'IN', 'AU'],
    t: {
      sw: 'kuongeza muda wa ukodishaji',
      ar: 'تجديد الإيجار',
      fr: 'renouvellement du bail',
      de: 'Mietverlängerung',
      ko: '임대차 갱신',
      ja: '賃貸借更新',
      pt: 'renovação do arrendamento',
      es: 'renovación del arriendo',
      zh: '租约续订',
      hi: 'पट्टा नवीकरण',
    },
    cite: { jurisdiction: 'KE', statuteRef: 'Cap 301', section: 's.4-7', year: 1965 },
  },
  {
    id: 'tenancy.notice_to_quit',
    en: 'notice to quit',
    def: 'Formal notice by landlord or tenant terminating a periodic tenancy.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'US', 'IN', 'SG', 'AU'],
    t: {
      sw: 'ilani ya kuondoka',
      ar: 'إشعار إخلاء',
      fr: 'congé',
      de: 'Kündigung',
      ko: '퇴거통지',
      ja: '解約通知',
      pt: 'notificação de despejo',
      es: 'notificación de desalojo',
      zh: '退租通知',
      hi: 'रिक्त करने का नोटिस',
    },
  },
  {
    id: 'tenancy.security_of_tenure',
    en: 'security of tenure',
    def: 'A tenant’s statutory right to remain in occupation and claim renewal subject to defined grounds.',
    cat: 'tenancy',
    juris: ['KE', 'GB', 'DE', 'FR', 'KR', 'JP'],
    t: {
      sw: 'uhakika wa upangaji',
      ar: 'أمن الحيازة',
      fr: 'droit au maintien dans les lieux',
      de: 'Bestandsschutz',
      ko: '임차권 보장',
      ja: '借家権保護',
      pt: 'segurança de posse',
      es: 'seguridad de tenencia',
      zh: '租赁保障',
      hi: 'पट्टा सुरक्षा',
    },
    cite: { jurisdiction: 'GB', statuteRef: 'Landlord and Tenant Act', section: 'Part II', year: 1954 },
  },
  {
    id: 'tenancy.assured_shorthold',
    en: 'assured shorthold tenancy',
    def: 'UK statutory residential tenancy under Housing Act 1988 allowing landlord to regain possession on 2 months’ notice after the fixed term.',
    cat: 'tenancy',
    juris: ['GB'],
    t: {
      sw: 'ukodishaji wa muda mfupi (AST)',
      ar: 'عقد إيجار سكني قصير (AST)',
      fr: 'bail résidentiel court (AST)',
      de: 'Kurzzeit-Wohnungsmietvertrag (AST)',
      ko: '단기보장임대 (AST)',
      ja: '短期保障賃貸借 (AST)',
      pt: 'arrendamento de curta duração (AST)',
      es: 'arrendamiento asegurado de corto plazo (AST)',
      zh: '短期保障租赁 (AST)',
      hi: 'संक्षिप्त आश्वस्त पट्टा (AST)',
    },
    cite: { jurisdiction: 'GB', statuteRef: 'Housing Act 1988', section: 's.19A-21', year: 1988 },
    syn: ['AST'],
  },
  {
    id: 'tenancy.periodic_tenancy',
    en: 'periodic tenancy',
    def: 'A tenancy that runs from period to period (monthly, weekly, yearly) without a fixed end date.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'US', 'SG', 'AU', 'IN', 'CA'],
    t: {
      sw: 'upangaji wa muda kwa muda',
      ar: 'إيجار دوري',
      fr: 'bail à tacite reconduction',
      de: 'Mietverhältnis auf unbestimmte Zeit',
      ko: '기간자동갱신 임대차',
      ja: '期間の定めのない賃貸借',
      pt: 'arrendamento por prazo indeterminado',
      es: 'arriendo de período en período',
      zh: '定期租赁',
      hi: 'आवधिक किरायेदारी',
    },
  },
  {
    id: 'tenancy.fixed_term',
    en: 'fixed-term tenancy',
    def: 'A tenancy granted for a definite period with a specified end date.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'US', 'DE', 'FR', 'KR', 'JP', 'SG', 'AU', 'IN', 'CA'],
    t: {
      sw: 'upangaji wa muda maalum',
      ar: 'إيجار محدد المدة',
      fr: 'bail à durée déterminée',
      de: 'befristeter Mietvertrag',
      ko: '확정기간 임대차',
      ja: '定期賃貸借',
      pt: 'arrendamento a termo certo',
      es: 'arriendo a plazo fijo',
      zh: '定期租赁',
      hi: 'निश्चित अवधि पट्टा',
    },
    cite: { jurisdiction: 'JP', statuteRef: '借地借家法', section: '§38', year: 1991 },
  },
  {
    id: 'tenancy.at_will',
    en: 'tenancy at will',
    def: 'A tenancy determinable by either party at any time, without fixed term or rent period.',
    cat: 'tenancy',
    juris: ['GB', 'US', 'KE'],
    t: {
      sw: 'upangaji wa ridhaa',
      ar: 'إيجار بإرادة منفردة',
      fr: 'bail précaire',
      de: 'Mietverhältnis auf Widerruf',
      ko: '임의임대차',
      ja: '随意賃貸借',
      pt: 'arrendamento precário',
      es: 'arriendo a voluntad',
      zh: '随意租赁',
      hi: 'इच्छानुसार किरायेदारी',
    },
  },
  {
    id: 'tenancy.at_sufferance',
    en: 'tenancy at sufferance',
    def: 'Occupation continuing after lawful possession has ended, without the landlord’s consent but without ejectment.',
    cat: 'tenancy',
    juris: ['GB', 'US'],
    t: {
      sw: 'upangaji wa kustahimili',
      ar: 'إيجار بالتسامح',
      fr: 'occupation tolérée',
      de: 'Besitz nach Duldung',
      ko: '묵인임대차',
      ja: '黙認賃貸借',
      pt: 'arrendamento por tolerância',
      es: 'tenencia por tolerancia',
      zh: '容忍租赁',
      hi: 'सहनशीलता से किरायेदारी',
    },
  },
  {
    id: 'tenancy.quiet_enjoyment',
    en: 'quiet enjoyment',
    def: 'Implied or express covenant that the tenant shall enjoy possession without lawful disturbance by the landlord.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'US', 'SG', 'IN', 'AU', 'CA'],
    t: {
      sw: 'haki ya kufurahia kwa amani',
      ar: 'حق الانتفاع الهادئ',
      fr: 'jouissance paisible',
      de: 'ungestörter Besitz',
      ko: '평온한 사용권',
      ja: '平穏な使用収益',
      pt: 'fruição pacífica',
      es: 'goce pacífico',
      zh: '宁居权',
      hi: 'शांत उपभोग',
    },
  },
  {
    id: 'tenancy.exclusive_possession',
    en: 'exclusive possession',
    def: 'The right to occupy premises to the exclusion of all others, including the landlord; hallmark of a lease.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'US', 'SG', 'AU'],
    t: {
      sw: 'umiliki wa pekee',
      ar: 'حيازة حصرية',
      fr: 'possession exclusive',
      de: 'ausschließlicher Besitz',
      ko: '전용점유',
      ja: '排他的占有',
      pt: 'posse exclusiva',
      es: 'posesión exclusiva',
      zh: '排他占有',
      hi: 'विशेष कब्जा',
    },
  },
  {
    id: 'tenancy.covenant',
    en: 'covenant',
    def: 'A promise contained in a lease binding the party who gives it.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'US', 'SG', 'AU', 'IN', 'CA'],
    t: {
      sw: 'ahadi ya mkataba',
      ar: 'تعهد عقدي',
      fr: 'engagement contractuel',
      de: 'Vertragspflicht',
      ko: '임대차상 약정',
      ja: '賃貸借上の約定',
      pt: 'obrigação contratual',
      es: 'pacto contractual',
      zh: '租约承诺',
      hi: 'अनुबंध प्रतिज्ञा',
    },
  },
  {
    id: 'tenancy.rent',
    en: 'rent',
    def: 'The periodic payment by the tenant to the landlord for use and occupation of the premises.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'TZ', 'UG', 'US', 'DE', 'FR', 'KR', 'JP', 'SG', 'AU', 'IN', 'CA', 'AE', 'BR', 'ZA'],
    t: {
      sw: 'kodi',
      ar: 'إيجار',
      fr: 'loyer',
      de: 'Miete',
      ko: '임대료',
      ja: '賃料',
      pt: 'aluguer',
      es: 'renta',
      zh: '租金',
      hi: 'किराया',
    },
  },
  {
    id: 'tenancy.premises',
    en: 'premises',
    def: 'The land and buildings demised under a lease.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'US', 'SG', 'AU'],
    t: {
      sw: 'jengo au eneo',
      ar: 'المأجور',
      fr: 'locaux',
      de: 'Mieträume',
      ko: '임대목적물',
      ja: '賃貸物件',
      pt: 'imóvel locado',
      es: 'inmueble arrendado',
      zh: '租赁物',
      hi: 'परिसर',
    },
  },
  {
    id: 'tenancy.demise',
    en: 'demise',
    def: 'The grant of a leasehold interest by the landlord to the tenant.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'SG', 'AU', 'IN'],
    t: {
      sw: 'utoaji wa ukodishaji',
      ar: 'منح حق الإيجار',
      fr: 'concession de bail',
      de: 'Überlassung',
      ko: '임대차 설정',
      ja: '賃貸借設定',
      pt: 'concessão do arrendamento',
      es: 'otorgamiento del arriendo',
      zh: '租赁授予',
      hi: 'पट्टा अनुदान',
    },
  },
  {
    id: 'tenancy.reversion',
    en: 'reversion',
    def: 'The residue of the landlord’s interest after granting a lease of shorter duration.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'SG', 'AU'],
    t: {
      sw: 'urudisho',
      ar: 'أيلولة الملكية',
      fr: 'droit de retour',
      de: 'Heimfall',
      ko: '복귀권',
      ja: '復帰権',
      pt: 'direito de reversão',
      es: 'derecho de reversión',
      zh: '复归权',
      hi: 'पुनर्प्राप्ति अधिकार',
    },
  },
  {
    id: 'tenancy.head_lease',
    en: 'head lease',
    def: 'The primary lease from which a sublease is derived.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'SG', 'AU'],
    t: {
      sw: 'ukodishaji mkuu',
      ar: 'عقد الإيجار الرئيسي',
      fr: 'bail principal',
      de: 'Hauptmietvertrag',
      ko: '원임대차',
      ja: '原賃貸借',
      pt: 'arrendamento principal',
      es: 'arrendamiento principal',
      zh: '主租约',
      hi: 'मुख्य पट्टा',
    },
  },
  {
    id: 'tenancy.under_lease',
    en: 'underlease',
    def: 'An alternative term for a sublease; a lease derived out of a head lease.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'SG'],
    t: {
      sw: 'ukodishaji chini',
      ar: 'إيجار تبعي',
      fr: 'sous-bail',
      de: 'Untermietvertrag',
      ko: '하위임대차',
      ja: '下位賃貸借',
      pt: 'sub-arrendamento',
      es: 'subarrendamiento',
      zh: '次租约',
      hi: 'उप-पट्टा',
    },
  },
  {
    id: 'tenancy.ground_lease',
    en: 'ground lease',
    def: 'A long lease of land on which the tenant is permitted to erect buildings.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'US', 'HK', 'SG', 'AE'],
    t: {
      sw: 'ukodishaji wa ardhi',
      ar: 'إيجار الأرض',
      fr: 'bail emphytéotique',
      de: 'Erbpacht',
      ko: '토지 임대차',
      ja: '借地権',
      pt: 'aforamento',
      es: 'arriendo del terreno',
      zh: '土地租赁',
      hi: 'भूमि पट्टा',
    },
    cite: { jurisdiction: 'JP', statuteRef: '借地借家法', section: '§2', year: 1991 },
  },
  {
    id: 'tenancy.commercial_lease',
    en: 'commercial lease',
    def: 'A lease of premises used for business, retail, office or industrial purposes.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'US', 'DE', 'FR', 'SG', 'AU', 'AE'],
    t: {
      sw: 'ukodishaji wa biashara',
      ar: 'إيجار تجاري',
      fr: 'bail commercial',
      de: 'Gewerbemietvertrag',
      ko: '상가임대차',
      ja: '事業用賃貸借',
      pt: 'arrendamento comercial',
      es: 'arriendo comercial',
      zh: '商业租赁',
      hi: 'व्यावसायिक पट्टा',
    },
    cite: { jurisdiction: 'FR', statuteRef: 'Code de commerce', section: 'L.145-1', year: 2000 },
  },
  {
    id: 'tenancy.residential_lease',
    en: 'residential lease',
    def: 'A lease of premises used as a dwelling by the tenant.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'US', 'DE', 'FR', 'KR', 'JP', 'SG', 'AU', 'IN', 'CA'],
    t: {
      sw: 'ukodishaji wa makazi',
      ar: 'إيجار سكني',
      fr: 'bail d’habitation',
      de: 'Wohnraummiete',
      ko: '주택임대차',
      ja: '居住用賃貸借',
      pt: 'arrendamento habitacional',
      es: 'arriendo residencial',
      zh: '住宅租赁',
      hi: 'आवासीय पट्टा',
    },
    cite: { jurisdiction: 'DE', statuteRef: 'BGB', section: '§549', year: 2002 },
  },
  {
    id: 'tenancy.deposit',
    en: 'security deposit',
    def: 'A sum held by the landlord to secure performance of the tenant’s obligations, refundable on lawful termination.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'TZ', 'UG', 'US', 'DE', 'FR', 'KR', 'JP', 'SG', 'AU', 'IN', 'CA', 'AE', 'BR', 'ZA'],
    t: {
      sw: 'dhamana',
      ar: 'تأمين الإيجار',
      fr: 'dépôt de garantie',
      de: 'Kaution',
      ko: '보증금',
      ja: '敷金',
      pt: 'caução',
      es: 'depósito de garantía',
      zh: '押金',
      hi: 'जमानत राशि',
    },
    cite: { jurisdiction: 'DE', statuteRef: 'BGB', section: '§551', year: 2002 },
  },
  {
    id: 'tenancy.keymoney',
    en: 'key money',
    def: 'Lump sum paid on grant of a lease beyond rent and deposit, traditional in JP / KR / FR.',
    cat: 'tenancy',
    juris: ['JP', 'KR', 'FR', 'DE'],
    t: {
      sw: 'pesa ya ufunguo',
      ar: 'بدل مفتاح',
      fr: 'pas-de-porte',
      de: 'Abstandszahlung',
      ko: '권리금',
      ja: '礼金',
      pt: 'luvas',
      es: 'derecho de llave',
      zh: '礼金',
      hi: 'चाबी पैसा',
    },
    notes: 'In Japan: 礼金 (reikin), generally non-refundable. In Korea: 권리금 (gwolligeum).',
  },
  {
    id: 'tenancy.jeonse',
    en: 'jeonse',
    def: 'Korean housing lease where tenant deposits a large lump sum (30-70% of property value) in lieu of periodic rent; deposit refunded at end of term.',
    cat: 'tenancy',
    juris: ['KR'],
    t: {
      sw: 'jeonse (Korea)',
      ar: 'عقد جونسي الكوري',
      fr: 'jeonse coréen',
      de: 'Jeonse (Korea)',
      ko: '전세',
      ja: 'チョンセ',
      pt: 'jeonse coreano',
      es: 'jeonse coreano',
      zh: '传贳',
      hi: 'जोन्से',
    },
    cite: { jurisdiction: 'KR', statuteRef: '주택임대차보호법', section: '§3-2', year: 1981 },
  },
  {
    id: 'tenancy.wolse',
    en: 'wolse',
    def: 'Korean monthly-rent lease with a smaller deposit than jeonse.',
    cat: 'tenancy',
    juris: ['KR'],
    t: {
      ko: '월세',
      ja: '月貰',
      zh: '月租',
    },
  },
  {
    id: 'tenancy.shikikin',
    en: 'shikikin',
    def: 'Japanese refundable security deposit under 借地借家法; deducted against damages and unpaid rent.',
    cat: 'tenancy',
    juris: ['JP'],
    t: {
      ja: '敷金',
      ko: '시키킹',
      zh: '敷金',
      de: 'Shikikin (Japan)',
    },
    cite: { jurisdiction: 'JP', statuteRef: '民法', section: '§622-2', year: 2020 },
  },
  {
    id: 'tenancy.pepper_corn_rent',
    en: 'peppercorn rent',
    def: 'Nominal rent (traditionally a peppercorn) payable to evidence consideration on a long ground lease.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'SG', 'AU'],
    t: {
      sw: 'kodi ya ishara',
      ar: 'إيجار رمزي',
      fr: 'loyer symbolique',
      de: 'Anerkennungszins',
      ko: '명목임대료',
      ja: '名目賃料',
      pt: 'renda simbólica',
      es: 'renta simbólica',
      zh: '象征性租金',
      hi: 'प्रतीकात्मक किराया',
    },
  },
  {
    id: 'tenancy.rent_free_period',
    en: 'rent-free period',
    def: 'Period at the start of a lease during which no rent is payable, typically granted as an inducement.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'US', 'SG', 'AU', 'AE'],
    t: {
      sw: 'kipindi bila kodi',
      ar: 'فترة إعفاء من الإيجار',
      fr: 'franchise de loyer',
      de: 'mietfreie Zeit',
      ko: '무상임대기간',
      ja: 'フリーレント期間',
      pt: 'período de carência',
      es: 'período libre de renta',
      zh: '免租期',
      hi: 'किराया मुक्त अवधि',
    },
  },
  {
    id: 'tenancy.vacant_possession',
    en: 'vacant possession',
    def: 'Delivery of possession free of occupants, chattels and adverse third-party rights.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'SG', 'AU'],
    t: {
      sw: 'umiliki tupu',
      ar: 'تسليم خال من الشواغل',
      fr: 'libre de toute occupation',
      de: 'geräumte Übergabe',
      ko: '명도',
      ja: '空渡し',
      pt: 'entrega livre',
      es: 'entrega libre',
      zh: '腾空交付',
      hi: 'खाली कब्जा',
    },
  },
  {
    id: 'tenancy.controlled_tenancy',
    en: 'controlled tenancy',
    def: 'A statutorily protected residential tenancy under the Kenyan Rent Restriction Act Cap 296 (below prescribed rent threshold).',
    cat: 'tenancy',
    juris: ['KE'],
    t: {
      sw: 'upangaji uliodhibitiwa',
      ar: 'إيجار خاضع للرقابة',
      fr: 'location réglementée',
      de: 'rentenreglementierte Miete',
      ko: '통제임대차',
      ja: '統制賃貸借',
      pt: 'arrendamento controlado',
      es: 'arriendo controlado',
      zh: '受控租赁',
      hi: 'नियंत्रित किरायेदारी',
    },
    cite: { jurisdiction: 'KE', statuteRef: 'Cap 296', section: 's.2', year: 1959 },
  },
  {
    id: 'tenancy.protected_tenancy',
    en: 'protected tenancy',
    def: 'Kenyan business tenancy of ≤5 years under Cap 301, statutorily protected from unilateral termination.',
    cat: 'tenancy',
    juris: ['KE'],
    t: {
      sw: 'upangaji unaolindwa',
      ar: 'إيجار محمي',
      fr: 'bail protégé',
      de: 'geschützte Miete',
      ko: '보호임대차',
      ja: '保護賃貸借',
      pt: 'arrendamento protegido',
      es: 'arriendo protegido',
      zh: '受保护租赁',
      hi: 'संरक्षित किरायेदारी',
    },
    cite: { jurisdiction: 'KE', statuteRef: 'Cap 301', section: 's.2', year: 1965 },
  },
  {
    id: 'tenancy.repairing_covenant',
    en: 'repairing covenant',
    def: 'Obligation on a party (landlord or tenant) to keep the premises in repair.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'SG', 'AU'],
    t: {
      sw: 'wajibu wa matengenezo',
      ar: 'التزام الإصلاح',
      fr: 'obligation de réparation',
      de: 'Instandhaltungspflicht',
      ko: '수선의무',
      ja: '修繕義務',
      pt: 'obrigação de conservação',
      es: 'obligación de reparación',
      zh: '维修义务',
      hi: 'मरम्मत अनुबंध',
    },
    cite: { jurisdiction: 'GB', statuteRef: 'Landlord and Tenant Act', section: 's.11', year: 1985 },
  },
  {
    id: 'tenancy.alienation',
    en: 'alienation',
    def: 'Any assignment, underletting, charging or parting with possession of the demised premises.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'SG'],
    t: {
      sw: 'uhamishaji wa ukodishaji',
      ar: 'تصرف في الإيجار',
      fr: 'cession ou sous-location',
      de: 'Vermietung oder Übertragung',
      ko: '임차권의 양도·전대',
      ja: '賃借権の譲渡・転貸',
      pt: 'transmissão do arrendamento',
      es: 'cesión o subarriendo',
      zh: '租赁权处分',
      hi: 'पट्टा अंतरण',
    },
  },
  {
    id: 'tenancy.user_clause',
    en: 'user clause',
    def: 'Contractual restriction on the permitted use of the premises.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'SG', 'AU'],
    t: {
      sw: 'kipengele cha matumizi',
      ar: 'شرط الاستعمال',
      fr: 'clause d’usage',
      de: 'Nutzungsklausel',
      ko: '용도제한 조항',
      ja: '用途制限条項',
      pt: 'cláusula de uso',
      es: 'cláusula de uso',
      zh: '用途条款',
      hi: 'उपयोग धारा',
    },
  },
  {
    id: 'tenancy.dilapidations',
    en: 'dilapidations',
    def: 'Claim by landlord for breach of repair / reinstatement covenants, typically at lease end.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'SG', 'AU'],
    t: {
      sw: 'madai ya uchakavu',
      ar: 'مطالبات الإهلاك',
      fr: 'réparations locatives',
      de: 'Schönheitsreparaturen',
      ko: '원상회복',
      ja: '原状回復費用',
      pt: 'reparações locativas',
      es: 'reparaciones locativas',
      zh: '修复义务索赔',
      hi: 'जीर्णोद्धार दावा',
    },
  },
  {
    id: 'tenancy.reinstatement',
    en: 'reinstatement',
    def: 'Tenant’s obligation to restore the premises to their pre-lease condition, removing alterations.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'SG', 'AU'],
    t: {
      sw: 'kurejesha hali ya awali',
      ar: 'إعادة الوضع السابق',
      fr: 'remise en état',
      de: 'Rückbauverpflichtung',
      ko: '원상회복',
      ja: '原状回復',
      pt: 'reposição do estado original',
      es: 'reposición al estado original',
      zh: '恢复原状',
      hi: 'पूर्वस्थिति में वापसी',
    },
  },
  {
    id: 'tenancy.privity_of_contract',
    en: 'privity of contract',
    def: 'Doctrine that only parties to a contract are bound by its terms; formerly retained liability for original tenants post-assignment.',
    cat: 'tenancy',
    juris: ['GB', 'KE', 'SG', 'AU'],
    t: {
      sw: 'uhusiano wa mkataba',
      ar: 'نسبية أثر العقد',
      fr: 'effet relatif du contrat',
      de: 'Vertragsverhältnis inter partes',
      ko: '계약당사자주의',
      ja: '契約の相対効',
      pt: 'efeito relativo dos contratos',
      es: 'efecto relativo de los contratos',
      zh: '合同相对性',
      hi: 'अनुबंध की निकटता',
    },
  },
];

/**
 * English-only extension entries — the balance of the 300-term target.
 *
 * Kept purposely terse to allow reviewers to scan long lists. Locale
 * translations marked `// TODO-L18N` are filled in by the curation team
 * in later waves.
 */
const EXTRA_ROWS: ReadonlyArray<
  readonly [string, string, string, ReadonlyArray<string>?]
> = [
  // --- Lease lifecycle / variants ---
  ['tenancy.oral_tenancy', 'oral tenancy', 'A tenancy created without written instrument.', ['GB', 'KE', 'US']],
  ['tenancy.written_tenancy', 'written tenancy', 'A tenancy evidenced in a signed writing.', ['GB', 'KE', 'US']],
  ['tenancy.deed', 'deed', 'A formal written instrument executed under seal.', ['GB', 'KE', 'US']],
  ['tenancy.memorandum', 'memorandum of lease', 'Short-form registrable note of a lease.', ['KE', 'UG', 'TZ']],
  ['tenancy.execution', 'execution of lease', 'Formal signing and delivery of a lease.', ['GB', 'KE', 'US']],
  ['tenancy.commencement_date', 'commencement date', 'Date from which the lease term runs.', ['GB', 'KE', 'US']],
  ['tenancy.effective_date', 'effective date', 'Date on which obligations under the lease begin to accrue.', ['GB', 'KE', 'US']],
  ['tenancy.term_date', 'term date', 'Date the lease term ends.', ['GB', 'KE']],
  ['tenancy.expiry_date', 'expiry date', 'Date on which the lease terminates by effluxion of time.', ['GB', 'KE']],
  ['tenancy.effluxion_of_time', 'effluxion of time', 'Automatic termination of a lease by expiry.', ['GB', 'KE', 'SG']],
  ['tenancy.option_to_renew', 'option to renew', 'Tenant’s contractual right to extend the lease.', ['GB', 'KE', 'SG', 'US']],
  ['tenancy.option_to_purchase', 'option to purchase', 'Tenant’s contractual right to buy the reversion.', ['GB', 'KE', 'US']],
  ['tenancy.right_of_first_refusal', 'right of first refusal', 'Right to match a third party offer on the reversion.', ['GB', 'KE', 'US']],
  ['tenancy.subletting_consent', 'subletting consent', 'Landlord consent required to sublet.', ['GB', 'KE', 'SG']],
  ['tenancy.assignment_consent', 'assignment consent', 'Landlord consent required to assign.', ['GB', 'KE', 'SG']],
  ['tenancy.unreasonable_refusal', 'unreasonable refusal', 'Landlord’s wrongful withholding of consent to deal.', ['GB', 'KE']],
  ['tenancy.waiver', 'waiver of breach', 'Landlord conduct that may waive right to forfeit for breach.', ['GB', 'KE']],
  ['tenancy.relief_from_forfeiture', 'relief from forfeiture', 'Equitable remedy reinstating lease after forfeiture.', ['GB', 'KE']],
  ['tenancy.breach', 'breach of covenant', 'Failure to perform a contractual lease obligation.', ['GB', 'KE', 'US']],
  ['tenancy.mitigation', 'duty to mitigate', 'Obligation to reduce loss after a breach.', ['GB', 'KE', 'US']],
  ['tenancy.liquidated_damages', 'liquidated damages', 'Pre-agreed sum payable on breach.', ['GB', 'KE', 'US']],
  ['tenancy.penalty_clause', 'penalty clause', 'Excessive sum payable on breach; generally unenforceable.', ['GB', 'KE']],
  ['tenancy.tenant_representations', 'tenant representations', 'Statements of fact made by the tenant at inception.', ['GB', 'KE', 'US']],
  ['tenancy.landlord_warranties', 'landlord warranties', 'Promises by the landlord as to title and condition.', ['GB', 'KE', 'US']],
  // --- Common-law doctrines ---
  ['tenancy.frustration', 'frustration of lease', 'Automatic discharge of a lease through supervening impossibility.', ['GB', 'KE']],
  ['tenancy.rescission', 'rescission', 'Unwinding of a lease ab initio for vitiating factor.', ['GB', 'KE']],
  ['tenancy.novation', 'novation', 'Substitution of a new contract / party with consent of all.', ['GB', 'KE', 'US']],
  ['tenancy.merger', 'merger of lease', 'Extinction of lease when tenant acquires reversion.', ['GB', 'KE']],
  ['tenancy.unity_of_possession', 'unity of possession', 'Coincidence of leasehold and reversion in one person.', ['GB', 'KE']],
  ['tenancy.estoppel', 'tenancy by estoppel', 'Tenancy binding on a landlord who lacks good title.', ['GB', 'KE', 'US']],
  ['tenancy.concurrent_lease', 'concurrent lease', 'Lease of the reversion granted to a third party.', ['GB', 'KE']],
  ['tenancy.overriding_lease', 'overriding lease', 'Lease granted to a former tenant under statutory right.', ['GB']],
  ['tenancy.reversionary_lease', 'reversionary lease', 'Lease taking effect in possession on a future date.', ['GB', 'KE']],
  ['tenancy.agreement_for_lease', 'agreement for lease', 'Contract to grant a lease at a future date.', ['GB', 'KE']],
  ['tenancy.heads_of_terms', 'heads of terms', 'Pre-contract summary of commercial lease terms.', ['GB', 'KE']],
  ['tenancy.letter_of_intent', 'letter of intent', 'Non-binding expression of willingness to contract.', ['GB', 'KE', 'US']],
  // --- Residential specific ---
  ['tenancy.hmo', 'house in multiple occupation', 'UK licensed dwelling occupied by ≥3 unrelated persons forming more than one household.', ['GB']],
  ['tenancy.bedsit', 'bedsit', 'Single-room rented dwelling, typically with shared facilities.', ['GB']],
  ['tenancy.studio_flat', 'studio flat', 'Self-contained single-room dwelling.', ['GB', 'KE', 'US']],
  ['tenancy.bedsitter_ke', 'bedsitter (KE)', 'Kenyan single-room self-contained dwelling.', ['KE']],
  ['tenancy.single_room', 'single room', 'One-room rented accommodation, commonly with shared sanitation.', ['KE', 'TZ', 'UG']],
  ['tenancy.chumba', 'chumba', 'Swahili: room or single-room dwelling.', ['KE', 'TZ']],
  ['tenancy.boarding_house', 'boarding house', 'Premises providing lodging and meals to paying residents.', ['GB', 'KE']],
  ['tenancy.lodger', 'lodger', 'Person occupying rooms in another’s dwelling without exclusive possession.', ['GB', 'KE', 'US']],
  ['tenancy.flatmate', 'flatmate', 'Co-occupier of shared residential premises.', ['GB', 'KE', 'AU']],
  ['tenancy.roommate', 'roommate', 'Co-occupier of a shared room or flat.', ['US', 'CA', 'KE']],
  ['tenancy.joint_tenants', 'joint tenants', 'Two or more tenants holding the same leasehold interest as one.', ['GB', 'KE', 'US', 'AU']],
  ['tenancy.tenants_in_common', 'tenants in common', 'Two or more holders of undivided interests without survivorship.', ['GB', 'KE', 'US']],
  ['tenancy.cohabitation', 'cohabitation', 'Living together in shared premises without formal tenancy status.', ['GB', 'KE']],
  // --- Commercial specific ---
  ['tenancy.anchor_tenant', 'anchor tenant', 'Principal tenant attracting footfall to a retail centre.', ['GB', 'KE', 'US', 'SG']],
  ['tenancy.mall_tenant', 'mall tenant', 'Tenant occupying space in a shopping centre.', ['KE', 'US', 'SG']],
  ['tenancy.food_court_unit', 'food court unit', 'Premises in a grouped food service area.', ['GB', 'KE', 'SG']],
  ['tenancy.office_suite', 'office suite', 'Self-contained office space within a larger building.', ['GB', 'KE', 'US']],
  ['tenancy.cowork_seat', 'co-working seat', 'Dedicated desk licensed in a shared workspace.', ['GB', 'KE', 'US']],
  ['tenancy.serviced_office', 'serviced office', 'Office let with utilities, reception and facilities included.', ['GB', 'KE', 'US']],
  ['tenancy.warehouse_lease', 'warehouse lease', 'Lease of storage / industrial premises.', ['GB', 'KE', 'US']],
  ['tenancy.industrial_lease', 'industrial lease', 'Lease of premises used for manufacturing or processing.', ['GB', 'KE', 'US']],
  ['tenancy.agricultural_tenancy', 'agricultural tenancy', 'Lease of land used for husbandry or farming.', ['GB', 'KE', 'US']],
  ['tenancy.kiosk_tenancy', 'kiosk tenancy', 'Short-form licence/lease for a small retail kiosk.', ['KE', 'TZ', 'UG']],
  ['tenancy.pop_up_lease', 'pop-up lease', 'Short-term lease for temporary retail or events.', ['GB', 'KE', 'US']],
  // --- Delivery & handover ---
  ['tenancy.handover', 'handover', 'Physical delivery of the premises to the tenant.', ['GB', 'KE', 'AE', 'SG']],
  ['tenancy.snagging', 'snagging', 'Pre-handover list of defects to be remedied by landlord/developer.', ['GB', 'KE', 'AE']],
  ['tenancy.punch_list', 'punch list', 'US equivalent of snagging: defects still to be completed.', ['US']],
  ['tenancy.walkthrough', 'walkthrough', 'Inspection of premises prior to handover or return.', ['US', 'KE']],
  ['tenancy.condition_report', 'condition report', 'Photographic inventory of premises condition at move-in.', ['GB', 'KE', 'AU', 'US']],
  ['tenancy.inventory', 'inventory', 'Schedule of contents and condition at the start of the tenancy.', ['GB', 'KE', 'US']],
  ['tenancy.check_in', 'check-in', 'Process of documenting the tenant’s arrival and premises condition.', ['GB', 'KE']],
  ['tenancy.check_out', 'check-out', 'Process of documenting the tenant’s departure and premises condition.', ['GB', 'KE']],
  ['tenancy.move_in', 'move-in', 'Physical act of taking possession.', ['GB', 'KE', 'US']],
  ['tenancy.move_out', 'move-out', 'Physical act of vacating.', ['GB', 'KE', 'US']],
  ['tenancy.vacation_notice', 'notice of vacation', 'Tenant’s notice that premises are being vacated.', ['GB', 'KE', 'US']],
  // --- Possession claims ---
  ['tenancy.possession_claim', 'possession claim', 'Court proceedings to recover possession of premises.', ['GB', 'KE']],
  ['tenancy.warrant_of_possession', 'warrant of possession', 'Court order authorising bailiff enforcement.', ['GB', 'KE']],
  ['tenancy.writ_of_possession', 'writ of possession', 'US/common-law enforcement order for possession.', ['US', 'KE']],
  ['tenancy.eviction_notice', 'eviction notice', 'Written notice requiring vacation of premises.', ['GB', 'KE', 'US']],
  ['tenancy.s21_notice', 'section 21 notice', 'UK AST notice seeking possession without fault.', ['GB']],
  ['tenancy.s8_notice', 'section 8 notice', 'UK AST notice seeking possession for fault.', ['GB']],
  ['tenancy.accelerated_possession', 'accelerated possession', 'UK expedited possession procedure for s.21 notices.', ['GB']],
  ['tenancy.three_day_notice', 'three-day notice', 'US short-form pay-or-quit notice (CA et al.).', ['US']],
  ['tenancy.unlawful_detainer_proceeding', 'unlawful detainer proceeding', 'US summary action to recover possession.', ['US']],
  ['tenancy.bailiff', 'bailiff / court messenger', 'Officer of the court enforcing possession orders.', ['GB', 'KE']],
  ['tenancy.auctioneer', 'auctioneer', 'Licensed agent executing distress or auction.', ['KE', 'UG', 'TZ']],
  // --- Sub-tenancies and chains ---
  ['tenancy.sublet_consent', 'subletting consent fee', 'Fee demanded by landlord to consent to sublet.', ['GB', 'KE', 'US']],
  ['tenancy.mesne_profits', 'mesne profits', 'Damages equal to rental value during unlawful occupation.', ['GB', 'KE']],
  ['tenancy.trespass', 'trespass to premises', 'Unlawful entry onto leased or owned premises.', ['GB', 'KE', 'US']],
  ['tenancy.squatting', 'squatting', 'Occupation without consent or legal right.', ['GB', 'KE', 'US']],
  ['tenancy.adverse_possession', 'adverse possession', 'Doctrine by which long occupation can defeat paper title.', ['GB', 'KE', 'US']],
  // --- Statutory notices / rights ---
  ['tenancy.rent_increase_notice', 'rent increase notice', 'Formal notice of intended increase in rent.', ['GB', 'KE', 'US']],
  ['tenancy.notice_period', 'notice period', 'Minimum time required before a notice takes effect.', ['GB', 'KE', 'US']],
  ['tenancy.service_of_notice', 'service of notice', 'Formal delivery of a notice on the counterparty.', ['GB', 'KE']],
  ['tenancy.deemed_service', 'deemed service', 'Legal fiction treating notice as served on a specified date.', ['GB', 'KE']],
  ['tenancy.statutory_right', 'statutory right', 'Right conferred on a tenant by primary legislation.', ['GB', 'KE', 'US']],
  ['tenancy.contractual_right', 'contractual right', 'Right arising from the lease instrument itself.', ['GB', 'KE', 'US']],
  // --- Special tenancies ---
  ['tenancy.long_lease', 'long lease', 'Residential lease of >21 years, often with ground rent.', ['GB']],
  ['tenancy.leasehold_flat', 'leasehold flat', 'Apartment held under a long lease.', ['GB']],
  ['tenancy.freehold', 'freehold', 'Estate in land held indefinitely (not a lease).', ['GB', 'KE']],
  ['tenancy.commonhold', 'commonhold', 'UK form of ownership for multi-unit buildings without landlord.', ['GB']],
  ['tenancy.strata_title', 'strata title', 'Multi-unit title granting individual ownership + shared common areas.', ['AU', 'SG', 'HK']],
  ['tenancy.condominium_title', 'condominium title', 'Individual apartment ownership with shared common property.', ['US', 'AE', 'BR']],
  ['tenancy.sectional_title', 'sectional title', 'South African form of condominium ownership.', ['ZA']],
  ['tenancy.coop_tenancy', 'co-operative tenancy', 'Proprietary lease granted by a housing co-operative.', ['US']],
  ['tenancy.public_housing', 'public housing', 'Social or government-provided rental housing.', ['US', 'SG', 'KE', 'GB']],
  ['tenancy.subsidised_housing', 'subsidised housing', 'Housing with rent reduced by public subsidy.', ['US', 'GB', 'SG', 'KE']],
  // --- Tenant obligations ---
  ['tenancy.pay_rent', 'obligation to pay rent', 'Primary tenant covenant to pay the reserved rent.', ['GB', 'KE', 'US']],
  ['tenancy.use_as_permitted', 'use as permitted', 'Covenant to use premises only for permitted purpose.', ['GB', 'KE']],
  ['tenancy.no_nuisance', 'no nuisance covenant', 'Covenant not to cause nuisance to neighbours.', ['GB', 'KE']],
  ['tenancy.no_alterations', 'no alterations', 'Covenant not to alter premises without consent.', ['GB', 'KE']],
  ['tenancy.insurance_obligation', 'tenant insurance obligation', 'Covenant to insure contents or third-party liability.', ['GB', 'KE', 'US']],
  ['tenancy.outgoings', 'outgoings', 'Sums payable in respect of premises other than rent (rates, service charge, utilities).', ['GB', 'KE', 'AU', 'SG']],
  ['tenancy.vat_on_rent', 'VAT on rent', 'Value added tax chargeable on commercial rent (KE, GB).', ['GB', 'KE']],
  // --- Landlord obligations ---
  ['tenancy.landlord_repair', 'landlord repair obligation', 'Duty to keep structure and exterior in repair.', ['GB', 'KE', 'US']],
  ['tenancy.landlord_insurance', 'landlord building insurance', 'Duty to insure the structure of the premises.', ['GB', 'KE']],
  ['tenancy.landlord_access', 'landlord access right', 'Reserved right of entry for inspection and repair.', ['GB', 'KE', 'US']],
  ['tenancy.right_of_entry', 'right of entry', 'Contractual right to enter on notice.', ['GB', 'KE']],
  ['tenancy.notice_of_entry', 'notice of entry', 'Written notice of the landlord’s intent to enter.', ['GB', 'KE']],
  // --- Misc ---
  ['tenancy.caveat_tenant', 'caveat by tenant', 'Registered notice of a tenant’s interest on the title.', ['KE', 'UG', 'TZ']],
  ['tenancy.land_registry', 'land registry', 'Public register of land titles.', ['GB', 'KE', 'UG', 'TZ']],
  ['tenancy.title_deed', 'title deed', 'Instrument evidencing ownership of land.', ['KE', 'UG', 'TZ']],
  ['tenancy.leasehold_title', 'leasehold title', 'Registered title to a leasehold estate.', ['GB', 'KE']],
  ['tenancy.encumbrance', 'encumbrance', 'Charge, lien or other right affecting title.', ['GB', 'KE', 'US']],
  ['tenancy.restrictive_covenant', 'restrictive covenant', 'Negative obligation running with the land.', ['GB', 'KE', 'US']],
  ['tenancy.positive_covenant', 'positive covenant', 'Affirmative obligation to do something on the land.', ['GB', 'KE']],
  ['tenancy.easement', 'easement', 'Right enjoyed over another’s land (right of way, support, light).', ['GB', 'KE', 'US']],
  ['tenancy.right_of_way', 'right of way', 'Easement of passage over land.', ['GB', 'KE', 'US']],
  ['tenancy.wayleave', 'wayleave', 'Permission to lay or cross with utility infrastructure.', ['GB', 'KE']],
  // --- Tenancy management lifecycle ---
  ['tenancy.onboarding', 'tenant onboarding', 'Administrative process of registering a new tenant.', ['GB', 'KE', 'US']],
  ['tenancy.offboarding', 'tenant offboarding', 'Process of concluding a tenancy and reconciling balances.', ['GB', 'KE', 'US']],
  ['tenancy.reletting', 'reletting', 'Grant of a new tenancy following an early termination.', ['GB', 'KE', 'US']],
  ['tenancy.void_period', 'void period', 'Period between tenancies when unit is unoccupied.', ['GB', 'KE', 'US']],
  ['tenancy.vacancy', 'vacancy', 'State of a unit being unlet.', ['GB', 'KE', 'US']],
  ['tenancy.waitlist', 'waitlist', 'Queue of prospective tenants awaiting availability.', ['US', 'SG']],
  ['tenancy.application', 'rental application', 'Form submitted by a prospective tenant for assessment.', ['US', 'KE', 'GB']],
  ['tenancy.reference_check', 'reference check', 'Verification of a prospective tenant’s prior landlord or employer.', ['GB', 'KE', 'US']],
  ['tenancy.credit_check', 'credit check', 'Review of a prospective tenant’s credit record.', ['GB', 'KE', 'US']],
  ['tenancy.id_verification', 'ID verification', 'Confirmation of a tenant’s legal identity.', ['GB', 'KE', 'US']],
  ['tenancy.right_to_rent', 'right to rent (UK)', 'UK statutory immigration check on prospective tenants.', ['GB']],
  ['tenancy.proof_of_income', 'proof of income', 'Documentary evidence of prospective tenant’s earnings.', ['GB', 'KE', 'US']],
  ['tenancy.payslip', 'payslip', 'Employer-issued record of wages.', ['GB', 'KE', 'US']],
  ['tenancy.p60', 'P60', 'UK annual statement of tax and earnings from employer.', ['GB']],
  ['tenancy.kra_pin', 'KRA PIN', 'Kenyan taxpayer identification number, required for lease registration.', ['KE']],
  ['tenancy.ura_tin', 'URA TIN', 'Ugandan taxpayer identification number.', ['UG']],
  ['tenancy.tra_tin', 'TRA TIN', 'Tanzanian taxpayer identification number.', ['TZ']],
  // --- Dispute / resolution ---
  ['tenancy.mediation', 'mediation (tenancy)', 'Voluntary ADR process between landlord and tenant.', ['GB', 'KE', 'US']],
  ['tenancy.arbitration', 'arbitration (tenancy)', 'Private adjudication of a tenancy dispute.', ['GB', 'KE', 'US']],
  ['tenancy.tribunal', 'tenancy tribunal', 'Specialist statutory forum for tenancy disputes.', ['GB', 'KE', 'AU', 'NZ']],
  ['tenancy.bpt_tribunal_ke', 'Business Premises Tribunal (KE)', 'Kenyan statutory tribunal under Cap 301.', ['KE']],
  ['tenancy.rent_tribunal_ke', 'Rent Restriction Tribunal (KE)', 'Kenyan statutory tribunal under Cap 296.', ['KE']],
  ['tenancy.first_tier_tribunal', 'First-tier Tribunal (Property Chamber)', 'UK tribunal for residential leasehold disputes.', ['GB']],
  // --- Rent payment forms ---
  ['tenancy.rent_in_advance', 'rent in advance', 'Rent payable before the period to which it relates.', ['GB', 'KE', 'US']],
  ['tenancy.rent_in_arrears', 'rent in arrears', 'Rent payable after the period to which it relates.', ['GB', 'KE', 'US']],
  ['tenancy.rent_collection_method', 'rent collection method', 'Channel by which rent is paid (M-Pesa, direct debit, etc.).', ['KE', 'GB', 'US']],
  ['tenancy.standing_order', 'standing order', 'Instruction to bank to make recurring payments.', ['GB', 'KE']],
  ['tenancy.direct_debit', 'direct debit', 'Recurring bank-initiated collection on payee instruction.', ['GB', 'KE', 'US']],
  ['tenancy.mpesa', 'M-Pesa rent payment', 'Mobile-money rent collection channel in Kenya.', ['KE']],
  ['tenancy.paybill', 'Paybill number', 'M-Pesa business collection identifier.', ['KE']],
  ['tenancy.tigo_pesa', 'Tigo Pesa', 'Tanzanian mobile money rent channel.', ['TZ']],
  ['tenancy.mtn_momo', 'MTN Mobile Money', 'Ugandan/Rwandan mobile money rent channel.', ['UG', 'RW']],
  // --- 60+ more to hit 300 ---
  ['tenancy.statutory_tenancy_uk', 'statutory tenancy (UK Rent Act)', 'Residual tenancy arising under Rent Acts.', ['GB']],
  ['tenancy.regulated_tenancy_uk', 'regulated tenancy (UK)', 'Pre-1989 protected UK tenancy.', ['GB']],
  ['tenancy.shorthold_tenancy', 'shorthold tenancy', 'Pre-AST fixed-term UK tenancy.', ['GB']],
  ['tenancy.nycha_lease', 'NYCHA lease', 'New York City public housing lease.', ['US']],
  ['tenancy.section_8_voucher', 'Section 8 voucher tenancy', 'US federal rental assistance tenancy.', ['US']],
  ['tenancy.lihtc_unit', 'LIHTC unit', 'US low-income housing tax-credit rental unit.', ['US']],
  ['tenancy.rent_stabilized_unit', 'rent-stabilized unit', 'NYC regulated rent unit.', ['US']],
  ['tenancy.rent_controlled_unit', 'rent-controlled unit', 'US pre-1947 regulated rent unit.', ['US']],
  ['tenancy.ellis_act', 'Ellis Act (CA)', 'California statute allowing landlord to exit rental business.', ['US']],
  ['tenancy.just_cause_eviction', 'just-cause eviction', 'Eviction grounded in defined statutory reason.', ['US', 'CA', 'DE']],
  ['tenancy.tenant_relocation', 'tenant relocation assistance', 'Payment to displaced tenant under local ordinance.', ['US']],
  ['tenancy.at_fault_termination', 'at-fault termination', 'Termination for tenant breach.', ['US']],
  ['tenancy.no_fault_termination', 'no-fault termination', 'Termination without tenant breach.', ['US']],
  ['tenancy.tribunal_de_grande_instance', 'tribunal judiciaire (FR)', 'French civil court hearing tenancy matters.', ['FR']],
  ['tenancy.commission_conciliation_fr', 'commission de conciliation (FR)', 'French ADR body for tenancy disputes.', ['FR']],
  ['tenancy.lc_justice_lac_uk', 'Leasehold Advisory Service (UK)', 'UK advice body on long leasehold issues.', ['GB']],
  ['tenancy.guarantor', 'guarantor', 'Third party guaranteeing tenant’s obligations.', ['GB', 'KE', 'US', 'JP']],
  ['tenancy.surety_bond', 'surety bond', 'Bond posted by a surety in lieu of deposit.', ['US']],
  ['tenancy.rent_guarantee', 'rent guarantee', 'Insurance or contract guaranteeing rent payment.', ['GB', 'KE', 'US']],
  ['tenancy.corporate_tenant', 'corporate tenant', 'Tenant that is an incorporated body.', ['GB', 'KE', 'US']],
  ['tenancy.diplomatic_tenant', 'diplomatic tenant', 'Tenant enjoying diplomatic immunities.', ['GB', 'KE', 'US']],
  ['tenancy.ngo_tenant', 'NGO tenant', 'Non-governmental organisation as tenant.', ['KE', 'UG', 'TZ']],
  ['tenancy.student_tenant', 'student tenant', 'Tenant in full-time education.', ['GB', 'KE', 'US']],
  ['tenancy.student_accommodation', 'student accommodation', 'Purpose-built or licensed student housing.', ['GB', 'KE', 'US']],
  ['tenancy.purpose_built_rental', 'purpose-built rental', 'Building constructed for multifamily rental.', ['US', 'CA', 'GB']],
  ['tenancy.buy_to_let', 'buy-to-let', 'UK investment property bought for rental income.', ['GB']],
  ['tenancy.rent_to_own', 'rent-to-own', 'Arrangement allowing tenant to acquire property over time.', ['US', 'KE']],
  ['tenancy.rent_to_rent', 'rent-to-rent', 'Arrangement where tenant sublets to third parties commercially.', ['GB', 'KE']],
  ['tenancy.serviced_apartment', 'serviced apartment', 'Short-stay apartment with hotel-style services.', ['GB', 'KE', 'US', 'SG']],
  ['tenancy.air_rights', 'air rights lease', 'Lease of air space above a property.', ['US', 'JP']],
  ['tenancy.subsoil_rights', 'subsoil rights lease', 'Lease of space beneath a property.', ['US', 'KE']],
  ['tenancy.parking_licence', 'parking licence', 'Permission to use parking space without exclusive possession.', ['GB', 'KE', 'US']],
  ['tenancy.parking_lease', 'parking lease', 'Lease of a designated parking bay.', ['GB', 'KE', 'US']],
  ['tenancy.storage_lease', 'storage lease', 'Lease of dedicated storage space.', ['GB', 'KE', 'US']],
  ['tenancy.signage_licence', 'signage licence', 'Permission to affix external signage.', ['GB', 'KE', 'US']],
  ['tenancy.antenna_lease', 'antenna / mast lease', 'Lease of rooftop space for telecommunications.', ['GB', 'KE', 'US']],
  ['tenancy.rooftop_lease', 'rooftop lease', 'Lease of roof surface (solar, antenna, garden).', ['GB', 'KE', 'US']],
  ['tenancy.greenleaf_lease', 'green lease clauses', 'Sustainability-linked lease provisions.', ['GB', 'KE', 'US']],
  ['tenancy.esg_clause', 'ESG clause', 'Environmental, social, governance obligation in lease.', ['GB', 'KE', 'US']],
  ['tenancy.data_sharing_clause', 'data-sharing clause', 'Clause regulating tenant data sharing with landlord.', ['GB', 'KE', 'US']],
  ['tenancy.cpi_adjustment', 'CPI adjustment', 'Rent indexation to consumer price index.', ['GB', 'KE', 'US', 'AU']],
  ['tenancy.stepped_rent', 'stepped rent', 'Rent that escalates on fixed dates.', ['GB', 'KE', 'US']],
  ['tenancy.fair_market_rent', 'fair market rent', 'Rent attainable in an open market.', ['GB', 'KE', 'US']],
  ['tenancy.open_market_rent', 'open market rent', 'Rent a willing tenant would pay to a willing landlord.', ['GB', 'KE']],
  ['tenancy.turnover_rent', 'turnover rent', 'Rent calculated as a percentage of tenant turnover.', ['GB', 'KE', 'US']],
  ['tenancy.percentage_rent', 'percentage rent', 'US equivalent of turnover rent for retail leases.', ['US']],
  ['tenancy.base_rent', 'base rent', 'Fixed component of rent before variable elements.', ['GB', 'KE', 'US']],
  ['tenancy.additional_rent', 'additional rent', 'Variable component of rent (outgoings, turnover).', ['GB', 'KE', 'US']],
  ['tenancy.effective_rent', 'effective rent', 'Rent net of incentives, spread over the term.', ['GB', 'KE', 'US']],
  ['tenancy.headline_rent', 'headline rent', 'Nominal rent before incentives.', ['GB', 'KE', 'US']],
  ['tenancy.all_inclusive_rent', 'all-inclusive rent', 'Rent bundled with utilities and outgoings.', ['GB', 'KE', 'US']],
  ['tenancy.utilities_included', 'utilities included', 'Letting where rent covers utility charges.', ['GB', 'KE', 'US']],
  ['tenancy.metered_utilities', 'metered utilities', 'Utilities billed to the tenant by consumption.', ['GB', 'KE', 'US']],
  ['tenancy.communal_utilities', 'communal utilities', 'Utilities supplied to shared areas, apportioned.', ['GB', 'KE', 'US']],
  ['tenancy.utility_reconciliation', 'utility reconciliation', 'Periodic true-up of utility charges against consumption.', ['GB', 'KE', 'US']],
  ['tenancy.force_majeure', 'force majeure (tenancy)', 'Clause excusing performance on extraordinary events.', ['GB', 'KE', 'US', 'FR']],
  ['tenancy.act_of_god', 'act of God', 'Natural event excusing performance.', ['GB', 'KE', 'US']],
  ['tenancy.rent_holiday', 'rent holiday', 'Period during which rent is abated.', ['GB', 'KE', 'US']],
  ['tenancy.rent_abatement', 'rent abatement', 'Reduction of rent, often on supply interruption.', ['GB', 'KE', 'US']],
  ['tenancy.frustrated_purpose', 'frustration of purpose', 'Doctrine discharging lease where purpose is destroyed.', ['GB', 'US', 'KE']],
  ['tenancy.eviction_moratorium', 'eviction moratorium', 'Statutory pause on evictions (e.g. COVID-era).', ['GB', 'US', 'KE']],
  ['tenancy.covid_forbearance', 'COVID rent forbearance', 'Temporary relief from rent enforcement.', ['GB', 'US', 'KE']],
  ['tenancy.force_rental_stay', 'force-rental stay', 'Court-ordered delay of eviction proceedings.', ['US', 'KE']],
  ['tenancy.pet_clause', 'pet clause', 'Provisions regulating tenant pets.', ['GB', 'KE', 'US']],
  ['tenancy.smoking_clause', 'smoking clause', 'Provisions prohibiting or regulating smoking.', ['GB', 'KE', 'US']],
  ['tenancy.guest_clause', 'guest clause', 'Limits on duration and frequency of tenant guests.', ['GB', 'KE', 'US']],
  ['tenancy.short_term_letting', 'short-term letting', 'Letting for <6 months; often regulated (Airbnb).', ['GB', 'KE', 'US', 'SG']],
  ['tenancy.airbnb_ban', 'Airbnb / STR ban', 'Local prohibition on short-term lettings.', ['GB', 'US', 'SG']],
  ['tenancy.sublet_platform', 'sublet platform listing', 'Advertisement of premises on a sublet site.', ['GB', 'US']],
  ['tenancy.furnished', 'furnished tenancy', 'Lease of premises with movable furniture included.', ['GB', 'KE', 'US', 'FR', 'JP', 'KR']],
  ['tenancy.unfurnished', 'unfurnished tenancy', 'Lease of premises without furniture.', ['GB', 'KE', 'US', 'FR']],
  ['tenancy.part_furnished', 'part-furnished tenancy', 'Lease with limited furniture included.', ['GB', 'KE']],
  ['tenancy.white_goods', 'white goods', 'Large kitchen appliances provided with the premises.', ['GB', 'KE']],
  ['tenancy.fixture', 'fixture', 'Item so annexed to the premises as to become part of them.', ['GB', 'KE', 'US']],
  ['tenancy.chattel', 'chattel', 'Movable property not annexed to the land.', ['GB', 'KE', 'US']],
  ['tenancy.tenant_fixture', 'tenant fixture', 'Fixture installed by the tenant, removable on termination.', ['GB', 'KE']],
  ['tenancy.trade_fixture', 'trade fixture', 'Commercial fixture installed for business use, removable.', ['GB', 'KE', 'US']],
  ['tenancy.occupancy_certificate', 'certificate of occupancy', 'Authority confirming premises fit for occupation.', ['US', 'KE', 'NG', 'AE']],
  ['tenancy.fitness_for_habitation', 'fitness for human habitation', 'Statutory standard for residential premises.', ['GB']],
  ['tenancy.habitability_warranty', 'warranty of habitability', 'US implied warranty that dwelling is safe and sanitary.', ['US']],
  ['tenancy.constructive_eviction', 'constructive eviction', 'Tenant vacates because premises rendered uninhabitable by landlord.', ['US', 'GB', 'KE']],
  ['tenancy.retaliatory_eviction', 'retaliatory eviction', 'Landlord eviction in retaliation for tenant complaint.', ['US', 'GB']],
  ['tenancy.self_help_eviction', 'self-help eviction', 'Landlord changing locks without court order (generally unlawful).', ['GB', 'KE', 'US']],
  ['tenancy.lockout', 'lockout', 'Exclusion of tenant from the premises.', ['US', 'GB', 'KE']],
  ['tenancy.peaceful_reentry', 'peaceful re-entry', 'Landlord regaining possession without breach of peace.', ['KE', 'GB']],
  ['tenancy.abandoned_goods', 'abandoned goods', 'Chattels left on premises after tenant departs.', ['GB', 'KE', 'US']],
  ['tenancy.distress_notice_ke', 'distress notice (KE)', 'Statutory 14-day notice before distress under Cap 293.', ['KE']],
  ['tenancy.proclamation', 'proclamation of distress', 'Public notice preceding sale under distress.', ['KE', 'UG']],
  ['tenancy.attachment', 'attachment of chattels', 'Judicial seizure of tenant property to satisfy rent.', ['KE', 'GB']],
  ['tenancy.condominium_rules', 'condominium rules', 'Rules binding unit owners/occupiers in a condominium.', ['US', 'BR', 'AE']],
  ['tenancy.house_rules', 'house rules', 'Building-level code of conduct.', ['GB', 'KE', 'US', 'JP']],
  ['tenancy.estate_rules', 'estate rules', 'Rules applying within a gated estate or compound.', ['KE', 'UG', 'TZ', 'ZA']],
  ['tenancy.occupancy_limit', 'occupancy limit', 'Max number of persons permitted to occupy a unit.', ['GB', 'KE', 'US']],
  ['tenancy.quiet_hours', 'quiet hours', 'Hours during which noise is restricted.', ['GB', 'KE', 'US', 'JP']],
  ['tenancy.balcony_usage', 'balcony usage restrictions', 'Limits on use/storage on balconies.', ['GB', 'KE', 'US']],
  ['tenancy.parking_allocation', 'parking allocation', 'Assignment of parking bays to units.', ['GB', 'KE', 'US']],
  ['tenancy.visitor_parking', 'visitor parking', 'Parking reserved for visitors to the estate.', ['GB', 'KE', 'US']],
  ['tenancy.access_control', 'access control', 'System regulating entry (cards, biometric).', ['GB', 'KE', 'US']],
  ['tenancy.smart_lock', 'smart lock', 'Electronic lock with remote access management.', ['GB', 'KE', 'US', 'SG']],
  ['tenancy.intercom', 'intercom / audio-video entry', 'System allowing remote visitor screening.', ['GB', 'KE', 'US', 'JP']],
  ['tenancy.cctv', 'CCTV obligations', 'Duties around operating closed-circuit television.', ['GB', 'KE', 'US']],
  ['tenancy.data_privacy_lease', 'data privacy clause (lease)', 'Clause regulating processing of tenant personal data.', ['GB', 'KE', 'US']],
  ['tenancy.biometric_consent', 'biometric consent', 'Tenant consent to fingerprint/face-print access systems.', ['KE', 'US', 'GB']],
  ['tenancy.digital_lease', 'digital lease', 'Lease executed via qualified e-signature.', ['GB', 'KE', 'US']],
  ['tenancy.esign', 'e-signature clause', 'Clause authorising electronic execution.', ['GB', 'KE', 'US']],
  ['tenancy.physical_signature', 'wet-ink signature', 'Traditional pen-and-paper signature.', ['GB', 'KE', 'US']],
  ['tenancy.witness_requirement', 'witness requirement', 'Statutory requirement of witnesses to lease execution.', ['KE', 'UG', 'TZ']],
  ['tenancy.notarisation', 'notarisation', 'Certification by a notary public.', ['DE', 'FR', 'BR', 'KR', 'JP']],
  ['tenancy.stamp_duty', 'stamp duty on lease', 'Transfer tax on lease instruments.', ['GB', 'KE', 'IN', 'SG']],
  ['tenancy.registration_fee', 'lease registration fee', 'Fee on registering a lease at the land registry.', ['KE', 'UG', 'TZ']],
  ['tenancy.registrable_lease', 'registrable lease', 'Lease of term requiring registration (>12m KE).', ['KE', 'GB']],
  ['tenancy.unregistered_lease', 'unregistered lease', 'Lease not entered on the land register.', ['KE', 'GB']],
  ['tenancy.overriding_interest', 'overriding interest', 'Short lease binding without registration.', ['GB', 'KE']],
  ['tenancy.beneficial_tenant', 'beneficial tenant', 'Person entitled to benefit of tenancy though not registered.', ['GB', 'KE']],
  ['tenancy.nominee_tenant', 'nominee tenant', 'Holder of tenancy on behalf of another.', ['GB', 'KE']],
  ['tenancy.group_company_occupier', 'group company occupier', 'Affiliate occupying under tenant’s licence.', ['GB', 'KE', 'US']],
  ['tenancy.subsidiary_occupation', 'subsidiary occupation clause', 'Clause permitting group-company sharing.', ['GB', 'KE']],
  ['tenancy.signing_authority', 'signing authority', 'Evidence that signatory has power to bind a party.', ['GB', 'KE', 'US']],
  ['tenancy.power_of_attorney', 'power of attorney', 'Authority to act in another’s name on lease matters.', ['GB', 'KE', 'US']],
  ['tenancy.execution_by_company', 'execution by company', 'Formalities for body-corporate signing.', ['GB', 'KE', 'US']],
  ['tenancy.execution_by_individual', 'execution by individual', 'Formalities for natural-person signing.', ['GB', 'KE', 'US']],
  ['tenancy.joint_and_several_liability', 'joint and several liability', 'Each co-tenant liable for whole of obligations.', ['GB', 'KE', 'US']],
  ['tenancy.several_liability', 'several liability', 'Each co-tenant liable only for own share.', ['GB', 'KE']],
  ['tenancy.collective_tenancy', 'collective tenancy', 'Tenancy granted to a group with shared obligations.', ['GB', 'KE', 'US']],
  ['tenancy.tenancy_handover_report', 'handover inspection report', 'Signed condition report at start of tenancy.', ['GB', 'KE', 'US']],
  ['tenancy.exit_condition_report', 'exit condition report', 'Signed condition report at end of tenancy.', ['GB', 'KE', 'US']],
  ['tenancy.depreciation_schedule', 'tenant depreciation schedule', 'Expected decline of tenant assets inside premises.', ['GB', 'KE', 'US']],
  ['tenancy.key_handover', 'key handover', 'Physical delivery of keys and access credentials.', ['GB', 'KE', 'US']],
  ['tenancy.key_deposit', 'key deposit', 'Refundable deposit for access keys/fobs.', ['GB', 'KE', 'US']],
  ['tenancy.keyholder', 'keyholder', 'Person with a set of premises keys.', ['GB', 'KE', 'US']],
  ['tenancy.lock_change', 'lock change', 'Replacement of locks (often at tenancy end).', ['GB', 'KE', 'US']],
];

export const TENANCY_ENTRIES: readonly GlossaryEntry[] = Object.freeze([
  ...buildEntries(CORE_SPECS),
  ...enOnlyBatch(
    'tenancy',
    ['GB', 'KE', 'US'],
    EXTRA_ROWS,
  ),
]);
