/**
 * Citation verifier — every numeric claim and legal reference in a
 * generated document must map to a citation in the document's
 * `citations` array.
 *
 * Pure functions. Production-mode wraps the Anthropic Citations API
 * (when `ANTHROPIC_API_KEY` is set and the document was generated by
 * Claude) — for now this scaffold just enforces the structural rule
 * locally so the builder can verify before sending the document out.
 */

import { createHash } from 'node:crypto';

export interface Citation {
  /** Stable id used in the rendered document (e.g. `[L-2026-04-001]`). */
  readonly id: string;
  /** What the citation grounds (the claim text fragment). */
  readonly claim: string;
  /** Where the supporting evidence lives. */
  readonly source: {
    readonly kind: 'ledger' | 'lease' | 'statute' | 'measurement' | 'external';
    readonly ref: string;
    readonly url?: string;
  };
}

export interface VerifyArgs {
  /** The rendered document text (plain or html-stripped). */
  readonly text: string;
  /** The citation set the document SHOULD ground its claims in. */
  readonly citations: ReadonlyArray<Citation>;
}

export type VerifyResult =
  | { readonly ok: true; readonly citedClaims: number }
  | {
      readonly ok: false;
      readonly missing: ReadonlyArray<{
        readonly fragment: string;
        readonly reason: 'numeric-uncited' | 'statute-uncited' | 'citation-id-not-found';
      }>;
    };

/** Numeric tokens that must carry a citation when they appear in body text. */
const NUMERIC_RE = /\b(?:USD|TZS|KES|UGX|NGN|RWF|ZAR)\s*[\d,]+(?:\.\d+)?|\b\d{1,3}(?:,\d{3})+(?:\.\d+)?\b|\b\d+(?:\.\d+)?\s*%/g;
/** Statute mentions that must be cited (Land Act / Sec. / Cap. / Act of YYYY). */
const STATUTE_RE = /\b(?:Land Act|Cap\.\s*\d+|Sec(?:tion)?\.\s*\d+|LTA\s*\d{4}|Rent Restriction|Recovery of Premises)\b/g;
/** A claim is considered cited when followed within 80 chars by [id]. */
const CITATION_TAG = /\[([A-Z0-9_-]{3,})\]/;

export function verifyDocumentCitations(args: VerifyArgs): VerifyResult {
  const validIds = new Set(args.citations.map((c) => c.id));
  const missing: Array<{
    fragment: string;
    reason: 'numeric-uncited' | 'statute-uncited' | 'citation-id-not-found';
  }> = [];
  let citedClaims = 0;

  function checkOccurrence(
    fragment: string,
    contextWindow: string,
    reason: 'numeric-uncited' | 'statute-uncited',
  ): void {
    const tag = contextWindow.match(CITATION_TAG);
    if (!tag || !tag[1]) {
      missing.push({ fragment, reason });
      return;
    }
    if (!validIds.has(tag[1])) {
      missing.push({ fragment, reason: 'citation-id-not-found' });
      return;
    }
    citedClaims++;
  }

  // Numeric claims.
  let m: RegExpExecArray | null;
  NUMERIC_RE.lastIndex = 0;
  while ((m = NUMERIC_RE.exec(args.text)) !== null) {
    const end = Math.min(args.text.length, m.index + m[0].length + 80);
    const ctx = args.text.slice(m.index, end);
    checkOccurrence(m[0], ctx, 'numeric-uncited');
  }

  // Statute mentions.
  STATUTE_RE.lastIndex = 0;
  while ((m = STATUTE_RE.exec(args.text)) !== null) {
    const end = Math.min(args.text.length, m.index + m[0].length + 80);
    const ctx = args.text.slice(m.index, end);
    checkOccurrence(m[0], ctx, 'statute-uncited');
  }

  if (missing.length > 0) {
    return { ok: false, missing };
  }
  return { ok: true, citedClaims };
}

/**
 * SHA-256 hex of a buffer or string. Reused by `builder.ts` to fingerprint
 * the rendered document for the WORM audit log.
 */
export function sha256Hex(input: string | Uint8Array | ArrayBufferView): string {
  const h = createHash('sha256');
  if (typeof input === 'string') {
    h.update(input);
  } else if (input instanceof Uint8Array) {
    h.update(input);
  } else {
    h.update(new Uint8Array(input.buffer, input.byteOffset, input.byteLength));
  }
  return h.digest('hex');
}
