/**
 * compile.ts — Deterministic compiler from a validated ModuleSpec to
 * (a) safe Drizzle-compatible migration SQL and (b) serialised Zod
 * validators.
 *
 * Design contract:
 *
 *   1. Pure: same input ALWAYS produces same output (no Date.now(),
 *      no random ids, no env reads). Enables caching the compile
 *      result by hash of (tenantId + spec).
 *
 *   2. Safe: every identifier emitted into SQL is either:
 *        - A constant string we control (table prefix, column type)
 *        - A slug that already passed Zod regex `^[a-z][a-z0-9_]{0,47}$`
 *      Therefore the output cannot host SQL injection.
 *
 *   3. Tenant-scoped at the schema level. Each entity table is named
 *      `module_{tenantId}_{entitySlug}` and includes its own
 *      `tenant_id` and `module_id` columns + RLS policies + REVOKE
 *      FROM anon. The compiler does NOT emit a table for entities
 *      it determines should be backed by `core_entity` (in v1 — every
 *      entity gets a dedicated extension table; the routing through
 *      core_entity for the polymorphic root happens at the
 *      orchestrator layer when it inserts the matching `core_entity`
 *      row).
 *
 *   4. Idempotent. Every emitted statement uses `IF NOT EXISTS` or
 *      DO-block guards.
 *
 *   5. No money mutation. The compiler refuses to back any money
 *      column with an actual table column — it emits a
 *      `MONEY_FIELDS_VIA_LEDGER` comment instead, forcing the
 *      handler code to route through `LedgerService.post()`.
 */

import {
  type ModuleSpec,
  type FieldDecl,
  type CompileResult,
  type ZodValidatorTree,
  type ZodFieldTree,
  SLUG_REGEX,
} from './types.js';
import { validateSpec } from './validate.js';

/**
 * Compile a spec for tenant {tenantId} into migration SQL + Zod
 * validators. Throws if the spec is grammatically invalid (caller
 * should validateSpec first to surface errors gracefully).
 */
export function compileSpec(
  spec: ModuleSpec,
  tenantId: string,
): CompileResult {
  if (!isValidTenantSlug(tenantId)) {
    return {
      ok: false,
      migrationSql: '',
      zodValidators: {},
      uiLayout: { sections: [] },
      errors: [`unsafe tenantId: ${tenantId}`],
    };
  }

  // Re-validate the spec — defence in depth. A caller that hands us
  // an unvalidated spec gets a structured error, never raw SQL.
  const v = validateSpec(spec);
  if (!v.ok || !v.spec) {
    return {
      ok: false,
      migrationSql: '',
      zodValidators: {},
      uiLayout: { sections: [] },
      errors: v.errors,
    };
  }

  const sqlParts: string[] = [];
  sqlParts.push(buildHeaderComment(tenantId));

  const zodValidators: Record<string, ZodValidatorTree> = {};

  for (const entity of v.spec.entities) {
    sqlParts.push(buildEntityTableSql(entity, tenantId));
    zodValidators[entity.slug] = buildZodValidatorTree(entity);
  }

  sqlParts.push(buildWorkflowSeed(v.spec, tenantId));
  sqlParts.push(buildRlsBlock(v.spec, tenantId));

  const uiLayout = buildUiLayout(v.spec);

  return {
    ok: true,
    migrationSql: sqlParts.join('\n\n'),
    zodValidators: Object.freeze(zodValidators),
    uiLayout,
    errors: [],
  };
}

// ─────────────────────────────────────────────────────────────────────
// Building blocks
// ─────────────────────────────────────────────────────────────────────

function buildHeaderComment(tenantId: string): string {
  return [
    `-- ============================================================================`,
    `-- Generated by @bossnyumba/module-spec-engine.`,
    `-- tenant_id: ${tenantId}`,
    `-- Generator version: 0.1.0`,
    `--`,
    `-- Every table created here:`,
    `--   * lives in the public schema with prefix module_${tenantId}_`,
    `--   * carries tenant_id + module_id as the first two columns`,
    `--   * ENABLE + FORCE ROW LEVEL SECURITY with tenant_isolation_select`,
    `--     and tenant_isolation_modify policies bound to`,
    `--     public.current_app_tenant_id()`,
    `--   * REVOKE ALL ON ... FROM anon`,
    `--`,
    `-- Money fields are NEVER stored as columns. The compiler emits a`,
    `-- comment marker only — the module handler routes money through`,
    `-- LedgerService.post() per the master invariant.`,
    `-- ============================================================================`,
  ].join('\n');
}

function buildEntityTableSql(
  entity: ReturnType<typeof spec_entity>,
  tenantId: string,
): string {
  const tableName = entityTableName(tenantId, entity.slug);

  // Columns common to every module entity table.
  const columns: string[] = [
    `id                  TEXT PRIMARY KEY`,
    `tenant_id           TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE`,
    `module_id           TEXT NOT NULL REFERENCES modules(id) ON DELETE CASCADE`,
    `display_name        TEXT NOT NULL`,
    `lifecycle_state     TEXT NOT NULL DEFAULT 'active'`,
    `created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()`,
    `updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()`,
    `deleted_at          TIMESTAMPTZ`,
  ];

  const moneyMarkers: string[] = [];

  for (const f of entity.fields) {
    if (f.kind === 'money') {
      // Money is NEVER a column. Emit a marker comment.
      moneyMarkers.push(
        `-- money field '${f.name}' on '${entity.slug}' routes via LedgerService.post() — no column emitted`,
      );
      continue;
    }
    columns.push(`${f.name.padEnd(20)} ${fieldKindToSqlType(f)}`);
  }

  const indexes: string[] = [];
  indexes.push(
    `CREATE INDEX IF NOT EXISTS ${tableName}_tenant_idx ON ${tableName} (tenant_id) WHERE deleted_at IS NULL;`,
  );
  indexes.push(
    `CREATE INDEX IF NOT EXISTS ${tableName}_module_idx ON ${tableName} (module_id, tenant_id) WHERE deleted_at IS NULL;`,
  );
  for (const f of entity.fields) {
    if (f.kind !== 'money' && 'index' in f && f.index === true) {
      indexes.push(
        `CREATE INDEX IF NOT EXISTS ${tableName}_${f.name}_idx ON ${tableName} (${f.name});`,
      );
    }
  }

  return [
    `-- ─────────────────────────────────────────────────────────`,
    `-- Entity: ${entity.slug}  (display: ${entity.display_name_en})`,
    `-- ─────────────────────────────────────────────────────────`,
    ...moneyMarkers,
    `CREATE TABLE IF NOT EXISTS ${tableName} (`,
    columns.map((c) => `  ${c}`).join(',\n'),
    `);`,
    ...indexes,
  ].join('\n');
}

function buildRlsBlock(spec: ModuleSpec, tenantId: string): string {
  const tables = spec.entities.map((e) => entityTableName(tenantId, e.slug));
  const tableArray = tables.map((t) => `    '${t}'`).join(',\n');
  return [
    `-- ─────────────────────────────────────────────────────────`,
    `-- Gold-standard RLS pattern — ENABLE + FORCE + REVOKE FROM anon`,
    `-- ─────────────────────────────────────────────────────────`,
    `DO $$`,
    `DECLARE`,
    `  tbl text;`,
    `  tenant_tables text[] := ARRAY[`,
    tableArray,
    `  ];`,
    `BEGIN`,
    `  FOREACH tbl IN ARRAY tenant_tables LOOP`,
    `    IF EXISTS (`,
    `      SELECT 1 FROM information_schema.tables`,
    `      WHERE table_schema = 'public' AND table_name = tbl`,
    `    ) THEN`,
    `      EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', tbl);`,
    `      EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY;', tbl);`,
    `      EXECUTE format('DROP POLICY IF EXISTS tenant_isolation_select ON public.%I;', tbl);`,
    `      EXECUTE format('DROP POLICY IF EXISTS tenant_isolation_modify ON public.%I;', tbl);`,
    `      EXECUTE format($pol$`,
    `        CREATE POLICY tenant_isolation_select ON public.%I`,
    `        FOR SELECT TO authenticated`,
    `        USING (tenant_id = public.current_app_tenant_id());`,
    `      $pol$, tbl);`,
    `      EXECUTE format($pol$`,
    `        CREATE POLICY tenant_isolation_modify ON public.%I`,
    `        FOR ALL TO authenticated`,
    `        USING (tenant_id = public.current_app_tenant_id())`,
    `        WITH CHECK (tenant_id = public.current_app_tenant_id());`,
    `      $pol$, tbl);`,
    `      EXECUTE format('REVOKE ALL ON public.%I FROM anon;', tbl);`,
    `    END IF;`,
    `  END LOOP;`,
    `END`,
    `$$;`,
  ].join('\n');
}

function buildWorkflowSeed(spec: ModuleSpec, tenantId: string): string {
  if (spec.workflows.length === 0) {
    return `-- no workflows declared in this spec.`;
  }
  // The spec engine emits a comment manifest — actual workflow
  // execution happens through the kernel's plan-decomposer using
  // these slugs as canonical labels.
  const lines: string[] = [
    `-- ─────────────────────────────────────────────────────────`,
    `-- Workflow manifest (tenant: ${tenantId})`,
    `-- ─────────────────────────────────────────────────────────`,
  ];
  for (const w of spec.workflows) {
    lines.push(
      `--   workflow ${w.slug}: ${w.title}`,
      `--     trigger: ${w.trigger_entity} on ${w.trigger_event}`,
      `--     steps:   ${w.steps.join(' → ')}`,
    );
  }
  return lines.join('\n');
}

function buildUiLayout(spec: ModuleSpec): CompileResult['uiLayout'] {
  const sections = spec.ui_sections.map((s) =>
    s.kind === 'table'
      ? {
          kind: 'table' as const,
          entity: s.entity,
          columns: Object.freeze([...s.columns]),
        }
      : s.kind === 'form'
        ? {
            kind: 'form' as const,
            entity: s.entity,
          }
        : {
            kind: 'kpi_tile' as const,
            title: s.title,
            query: s.query,
          },
  );
  return Object.freeze({ sections: Object.freeze(sections) });
}

function buildZodValidatorTree(
  entity: ReturnType<typeof spec_entity>,
): ZodValidatorTree {
  const fields: Record<string, ZodFieldTree> = {};
  for (const f of entity.fields) {
    fields[f.name] = serialiseFieldToZodTree(f);
  }
  return Object.freeze({
    kind: 'object',
    fields: Object.freeze(fields),
  });
}

function serialiseFieldToZodTree(f: FieldDecl): ZodFieldTree {
  // Build deterministically so the JSON matches across compile runs.
  switch (f.kind) {
    case 'text':
      return {
        kind: 'text',
        required: f.required,
        ...(f.max_length !== undefined ? { max_length: f.max_length } : {}),
      };
    case 'int':
      return {
        kind: 'int',
        required: f.required,
        ...(f.min !== undefined ? { min: f.min } : {}),
        ...(f.max !== undefined ? { max: f.max } : {}),
      };
    case 'numeric':
      return {
        kind: 'numeric',
        required: f.required,
        ...(f.precision !== undefined ? { precision: f.precision } : {}),
        ...(f.scale !== undefined ? { scale: f.scale } : {}),
        ...(f.min !== undefined ? { min: f.min } : {}),
        ...(f.max !== undefined ? { max: f.max } : {}),
      };
    case 'money':
      return { kind: 'money', required: f.required };
    case 'date':
      return { kind: 'date', required: f.required };
    case 'datetime':
      return { kind: 'datetime', required: f.required };
    case 'boolean':
      return { kind: 'boolean', required: f.required };
    case 'fk':
      return { kind: 'fk', required: f.required, references: f.references };
    case 'enum':
      return {
        kind: 'enum',
        required: f.required,
        values: Object.freeze([...f.values]),
      };
    default: {
      // Exhaustiveness guard.
      const exhaust: never = f;
      throw new Error(`unhandled field kind: ${String(exhaust)}`);
    }
  }
}

function fieldKindToSqlType(f: FieldDecl): string {
  const notNull = f.required ? ' NOT NULL' : '';
  switch (f.kind) {
    case 'text':
      return f.max_length !== undefined
        ? `VARCHAR(${f.max_length})${notNull}`
        : `TEXT${notNull}`;
    case 'int':
      return `INTEGER${notNull}`;
    case 'numeric': {
      const p = f.precision ?? 18;
      const s = f.scale ?? 4;
      return `NUMERIC(${p}, ${s})${notNull}`;
    }
    case 'money':
      // Should never reach here — money fields are skipped above.
      return `TEXT /* money fallback */${notNull}`;
    case 'date':
      return `DATE${notNull}`;
    case 'datetime':
      return `TIMESTAMPTZ${notNull}`;
    case 'boolean':
      return `BOOLEAN${notNull}`;
    case 'fk':
      // We emit a soft TEXT pointer — the compiler can't know the
      // target table at codegen time without doing a second pass; the
      // orchestrator validates referential integrity at insert time.
      return `TEXT${notNull}`;
    case 'enum': {
      const values = f.values.map((v) => `'${v}'`).join(', ');
      return `TEXT${notNull} CHECK (${f.name} IN (${values}))`;
    }
    default: {
      const exhaust: never = f;
      throw new Error(`unhandled field kind for SQL emission: ${String(exhaust)}`);
    }
  }
}

function entityTableName(tenantId: string, entitySlug: string): string {
  return `module_${tenantId}_${entitySlug}`;
}

/**
 * Reject anything that isn't a strict slug-shaped tenant_id. tenant_id
 * is FK-validated upstream but we still defend in depth — a malicious
 * caller cannot land arbitrary text in the generated table name.
 */
function isValidTenantSlug(tenantId: string): boolean {
  return SLUG_REGEX.test(tenantId);
}

// Type helper — exposes the entity decl shape without re-importing.
type Entity = ModuleSpec['entities'][number];
function spec_entity(): Entity {
  throw new Error('type-only helper');
}
