-- =============================================================================
-- 0205: ui_artifacts — Piece G GenUI canonical store.
--
-- The brain emits typed UI artifacts via an `ui_artifact` SSE event; the chat
-- surface renders them inline; the SSR pipeline rasterises them to PNG / PDF /
-- SVG for WhatsApp + email previews. This table is the canonical store for
-- every artifact emitted by the kernel, deduplicated by id and addressable
-- by `(tenant_id, id)` from any host (chat-ui, owner-portal, customer-app,
-- estate-manager-app, admin-platform-portal).
--
-- Distinct from `conversation_artifacts` (which is a thin link from a chat
-- message → an artifact) — that table now points at `ui_artifacts.id`.
--
-- The canonical primitive vocabulary lives in `packages/genui/src/catalog.ts`
-- (≥30 component types each with a Zod schema). The kernel may only emit
-- `component_type` values that appear in the catalog; anything else is
-- rejected at the render boundary and surfaced as `UnknownKindCard`.
--
-- Schema:
--   id                    : ULID/text PRIMARY KEY (generated by the emitter)
--   tenant_id             : tenant context, FK → tenants(id), cascade-on-delete
--   thread_id             : optional chat thread the artifact lives in
--   created_by_user_id    : optional user attribution (NULL = brain-emitted)
--   component_type        : one of the ~30 catalog keys (kpi_tile, bar_chart, …)
--   props_jsonb           : Zod-validated component props (visual config)
--   data_jsonb            : Zod-validated payload (rows, series, etc.)
--   version               : artifact version, incremented on each revise pass
--   parent_version_id     : self-FK for revision lineage
--   title / description   : optional human-facing labels (rendered in chat)
--   locale                : 'en' | 'sw' (artifact-level i18n)
--   theme_token_set_id    : optional brand theme override (added by 0206)
--   created_at            : write timestamp
--
-- RLS:
--   * ENABLE + FORCE ROW LEVEL SECURITY (every tenant-scoped row)
--   * tenant_isolation_select (USING current_app_tenant_id())
--   * tenant_isolation_modify (FOR ALL, USING + WITH CHECK)
--   * REVOKE ALL FROM anon (defence-in-depth)
--
-- Idempotent; safe to re-run.
-- =============================================================================

-- ─────────────────────────────────────────────────────────────────────────
-- 1. ui_artifacts table.
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS ui_artifacts (
  id                  TEXT PRIMARY KEY,
  tenant_id           TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  thread_id           TEXT,
  created_by_user_id  TEXT,
  /**
   * Canonical catalog key. See `packages/genui/src/catalog.ts` for the list.
   * Stored as TEXT (not pgEnum) so the catalog can grow without a migration.
   * Common values include: 'kpi_tile', 'bar_chart', 'line_chart',
   * 'pie_chart', 'data_table', 'form', 'deck_slide', 'doc_section',
   * 'map_view', 'heatmap', 'timeline', 'kanban', 'gantt', 'funnel',
   * 'metric_grid', 'image', 'video', 'code_block', 'markdown', 'callout',
   * 'comparison', 'pivot_table', 'sparkline', 'treemap', 'sankey',
   * 'scatter', 'gauge', 'radar', 'box_plot', 'histogram', 'org_chart'.
   */
  component_type      TEXT NOT NULL,
  /** Zod-validated component props (visual config). */
  props_jsonb         JSONB NOT NULL DEFAULT '{}'::jsonb,
  /** Zod-validated payload (rows, series, etc.). */
  data_jsonb          JSONB NOT NULL DEFAULT '{}'::jsonb,
  version             SMALLINT NOT NULL DEFAULT 1,
  parent_version_id   TEXT REFERENCES ui_artifacts(id),
  title               TEXT,
  description         TEXT,
  /** Artifact-level locale; portals fall back to user locale when absent. */
  locale              TEXT NOT NULL DEFAULT 'en',
  /**
   * Optional brand-theme override; FK added in 0206 once the
   * `tenant_brand_themes` table exists. NULL = inherit tenant default.
   */
  theme_token_set_id  TEXT,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ui_artifacts_tenant_created_idx
  ON ui_artifacts (tenant_id, created_at DESC);

CREATE INDEX IF NOT EXISTS ui_artifacts_tenant_thread_idx
  ON ui_artifacts (tenant_id, thread_id, created_at DESC);

CREATE INDEX IF NOT EXISTS ui_artifacts_tenant_component_idx
  ON ui_artifacts (tenant_id, component_type);

CREATE INDEX IF NOT EXISTS ui_artifacts_parent_version_idx
  ON ui_artifacts (parent_version_id) WHERE parent_version_id IS NOT NULL;

COMMENT ON TABLE ui_artifacts IS
  'Piece-G canonical store for typed UI artifacts emitted by the kernel and rendered inline by chat-ui / portals. Tenant-scoped via RLS.';

COMMENT ON COLUMN ui_artifacts.component_type IS
  'Catalog key from packages/genui/src/catalog.ts. Brain may only emit catalog members; render boundary rejects anything else.';

COMMENT ON COLUMN ui_artifacts.props_jsonb IS
  'Visual config props (e.g. axis labels, colors). Validated by the Zod schema for the component_type before write and again at render.';

COMMENT ON COLUMN ui_artifacts.data_jsonb IS
  'Renderable payload (rows, series, markers). Validated by the Zod schema for the component_type before write and again at render.';

COMMENT ON COLUMN ui_artifacts.locale IS
  'Artifact-level locale ("en" | "sw"). Charts pick locale-aware number / date formatters; markdown card uses translation table.';

-- ─────────────────────────────────────────────────────────────────────────
-- 2. Gold-standard RLS pattern (matches 0181-0185).
-- ─────────────────────────────────────────────────────────────────────────

DO $$
DECLARE
  tbl text;
  tenant_tables text[] := ARRAY[
    'ui_artifacts'
  ];
BEGIN
  FOREACH tbl IN ARRAY tenant_tables LOOP
    IF EXISTS (
      SELECT 1 FROM information_schema.tables
      WHERE table_schema = 'public' AND table_name = tbl
    ) THEN
      EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', tbl);
      EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY;', tbl);

      EXECUTE format(
        'DROP POLICY IF EXISTS tenant_isolation_select ON public.%I;', tbl
      );
      EXECUTE format(
        'DROP POLICY IF EXISTS tenant_isolation_modify ON public.%I;', tbl
      );

      EXECUTE format($pol$
        CREATE POLICY tenant_isolation_select ON public.%I
        FOR SELECT
        TO authenticated
        USING (tenant_id = public.current_app_tenant_id());
      $pol$, tbl);

      EXECUTE format($pol$
        CREATE POLICY tenant_isolation_modify ON public.%I
        FOR ALL
        TO authenticated
        USING (tenant_id = public.current_app_tenant_id())
        WITH CHECK (tenant_id = public.current_app_tenant_id());
      $pol$, tbl);

      EXECUTE format('REVOKE ALL ON public.%I FROM anon;', tbl);
    END IF;
  END LOOP;
END
$$;

-- Operator note: ui_artifacts is the canonical store. The brain writes via a
-- service-role Supabase client (RLS bypass); reads from the application path
-- (chat-ui, owner-portal, etc.) flow through the authenticated role and the
-- RLS policies above. Cross-tenant reads are impossible at the database
-- level — verified by `packages/database/src/__tests__/rls-ui-artifacts.test`.
