-- ============================================================================
-- Migration 0317 — add 'NEEDS_REVERSAL' to the disbursement_status enum.
--
-- WHY
-- ───
-- The disbursement money-path posts the ledger debit FIRST, then initiates the
-- outbound provider transfer. If the transfer fails AFTER the ledger post — or
-- times out with NO result callback — the money is DEBITED, UNDELIVERED, and
-- must not be tallied as a clean success nor blind-re-transferred. The
-- disbursement is parked in a distinct, retryable NEEDS_REVERSAL state that the
-- disbursement reconciliation job (services/payments-ledger/src/jobs/
-- disbursement-reconciliation.job.ts) consumes: it re-drives the transfer under
-- the SAME idempotency key (confirmed non-delivery) or posts a compensating
-- reversal — never a blind re-transfer. This mirrors the proven Borjie pattern.
--
-- The canonical Drizzle enum (packages/database/src/schemas/ledger.schema.ts)
-- now lists NEEDS_REVERSAL; the DB enum shipped by migration 0166 / reconciled
-- by 0167b does not. This file adds the missing member.
--
-- `ALTER TYPE ... ADD VALUE` is run as a bare top-level statement (NOT inside a
-- DO/PL-pgSQL block — Postgres forbids using a value added by ADD VALUE inside
-- the same transaction that adds it). The migration runner
-- (packages/database/src/run-migrations.ts) wraps each file in its own
-- `sql.begin()` and commits it before the next file runs, so a later file may
-- safely default to / compare against this label. `ADD VALUE IF NOT EXISTS` is
-- natively idempotent, so re-running this file (or applying it to a DB already
-- healed by drizzle-kit) is a clean no-op.
-- ============================================================================

ALTER TYPE "public"."disbursement_status" ADD VALUE IF NOT EXISTS 'NEEDS_REVERSAL';
