-- =============================================================================
-- Migration 0335 — co_owner_invites: pending owner-portal team invitations.
--
-- WHY THIS MIGRATION EXISTS
-- -------------------------
-- The owner-portal Settings → Users tab (apps/owner-portal/src/pages/
-- SettingsPage.tsx) used to FAKE invitations: `handleInviteUser` pushed a row
-- into local React state and flashed "Invitation sent" WITHOUT touching a
-- backend or actually notifying anyone; "Resend" was a pure toast; "Remove"
-- only spliced the array. This migration creates the durable invite store the
-- new owner-account router writes to (POST /owner/account/co-owners/invite,
-- GET list, DELETE /:id revoke, POST /:id/resend) — each of which enqueues a
-- REAL email invite via the notifications engine (notification_dispatch_log,
-- the durable at-least-once dispatch queue the dispatcher-worker drains).
--
-- ONE TABLE
--   * co_owner_invites — one row per pending invitation. Tenant-scoped
--     (tenant_id, RLS isolation). Carries an opaque single-use `token` (the
--     accept link) and the `role` the invitee will be granted. `invited_by`
--     records the owner who issued it (audit). Soft-revoke via `revoked_at`.
--
-- TOKEN (security): a 32-byte url-safe random token generated by the route
-- layer (node:crypto). UNIQUE so the accept endpoint can resolve it. Stored in
-- full here (single-use, short-lived via expires_at); rotated on resend.
--
-- ROLE (CLAUDE.md — server-side ABAC): constrained to the co-owner-grantable
-- subset ('CO_OWNER' | 'VIEWER'). The route additionally requires the CALLER
-- to be OWNER/TENANT_ADMIN/ADMIN/SUPER_ADMIN (requireRole) — an invite can
-- never escalate to OWNER/admin from this surface.
--
-- TENANT SCOPE (CLAUDE.md hard rule): tenant-scoped (`tenant_id` TEXT; no FK,
-- matching the tenant_id-as-text convention used by 0316/0317/0322/0331/0334).
-- FORCE-enables RLS with a tenant-isolation policy on the canonical
-- `app.current_tenant_id` GUC plus a service-role bypass and a guarded anon
-- REVOKE, mirroring 0331/0334.
--
-- FRESH-DB SAFETY / IDEMPOTENCY (CLAUDE.md hard rule): every object uses
-- CREATE ... IF NOT EXISTS + guarded DO-blocks + a pg_roles guard around the
-- anon REVOKE. On a fully-migrated DB this is a pure no-op.
--
-- Companion files:
--   * services/api-gateway/src/routes/owner/owner-account.hono.ts (routes)
--   * services/api-gateway/src/routes/owner/owner-account-repo.ts  (repo)
--   * apps/owner-portal/src/pages/SettingsPage.tsx                 (FE)
--   * packages/database/src/migrations/down/0335_down_co_owner_invites.sql
-- =============================================================================

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- -----------------------------------------------------------------------------
-- co_owner_invites — pending owner-portal team invitations.
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS co_owner_invites (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id          text NOT NULL,

  -- Invitee identity.
  email              text NOT NULL,
  first_name         text NOT NULL DEFAULT '',
  last_name          text NOT NULL DEFAULT '',
  -- Co-owner-grantable role only. NEVER OWNER/ADMIN from this surface.
  role               text NOT NULL DEFAULT 'VIEWER',
  -- Property scope the invitee will receive access to (JSON array of names/ids).
  property_access    jsonb NOT NULL DEFAULT '[]'::jsonb,

  -- Accept link token — opaque, single-use, rotated on resend.
  token              text NOT NULL,

  -- Issuer (audit) — ALWAYS resolved from the JWT, never client input.
  invited_by         text NOT NULL,

  -- Lifecycle.
  status             text NOT NULL DEFAULT 'pending',
  resend_count       integer NOT NULL DEFAULT 0,

  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now(),
  -- Default 14-day acceptance window.
  expires_at         timestamptz NOT NULL DEFAULT (now() + interval '14 days'),
  accepted_at        timestamptz,
  revoked_at         timestamptz,

  CONSTRAINT co_owner_invites_role_chk
    CHECK (role IN ('CO_OWNER', 'VIEWER')),
  CONSTRAINT co_owner_invites_status_chk
    CHECK (status IN ('pending', 'accepted', 'revoked', 'expired'))
);

-- Opaque accept token must be globally unique so the accept endpoint resolves
-- it without a tenant predicate (the token itself carries the tenant binding).
CREATE UNIQUE INDEX IF NOT EXISTS uniq_co_owner_invites_token
  ON co_owner_invites (token);

-- Hot path: the tenant's pending-invite list, newest first.
CREATE INDEX IF NOT EXISTS idx_co_owner_invites_tenant_status
  ON co_owner_invites (tenant_id, status, created_at DESC);

-- -----------------------------------------------------------------------------
-- RLS — FORCE + tenant isolation on the canonical GUC + service-role bypass +
-- guarded anon REVOKE. Mirrors the 0331/0334 shape.
-- -----------------------------------------------------------------------------

DO $$
DECLARE
  tbl text;
  tenant_tables text[] := ARRAY[
    'co_owner_invites'
  ];
BEGIN
  FOREACH tbl IN ARRAY tenant_tables LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY;', tbl);
    EXECUTE format('ALTER TABLE %I FORCE  ROW LEVEL SECURITY;', tbl);

    IF NOT EXISTS (
      SELECT 1 FROM pg_policies
       WHERE schemaname = 'public'
         AND tablename  = tbl
         AND policyname = 'tenant_isolation_' || tbl
    ) THEN
      EXECUTE format(
        'CREATE POLICY %I ON %I FOR ALL '
        || 'USING (tenant_id = current_setting(''app.current_tenant_id'', true)) '
        || 'WITH CHECK (tenant_id = current_setting(''app.current_tenant_id'', true));',
        'tenant_isolation_' || tbl, tbl
      );
    END IF;

    IF NOT EXISTS (
      SELECT 1 FROM pg_policies
       WHERE schemaname = 'public'
         AND tablename  = tbl
         AND policyname = tbl || '_service_role_bypass'
    ) THEN
      EXECUTE format(
        'CREATE POLICY %I ON %I FOR ALL '
        || 'USING (current_setting(''app.is_service_role'', true) = ''true'') '
        || 'WITH CHECK (current_setting(''app.is_service_role'', true) = ''true'');',
        tbl || '_service_role_bypass', tbl
      );
    END IF;

    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
      EXECUTE format('REVOKE ALL ON public.%I FROM anon;', tbl);
    END IF;
  END LOOP;
END $$;

COMMENT ON TABLE co_owner_invites IS
  'Pending owner-portal team invitations. Tenant-scoped (tenant_id, RLS). '
  'Carries an opaque single-use accept token + the co-owner-grantable role '
  '(CO_OWNER|VIEWER — never OWNER/admin from this surface). invited_by is the '
  'issuing owner (audit, JWT-resolved). Each invite/resend enqueues a real '
  'email via notification_dispatch_log. Soft-revoke via revoked_at. RLS FORCE '
  'on app.current_tenant_id + service-role bypass. Added in 0335.';

COMMENT ON COLUMN co_owner_invites.token IS
  'Opaque single-use accept-link token (node:crypto, url-safe). UNIQUE so the '
  'accept endpoint resolves it. Rotated on resend; cleared semantics on revoke.';

COMMENT ON COLUMN co_owner_invites.invited_by IS
  'The owner who issued the invite. ALWAYS resolved from the JWT (never client '
  'input). Audit trail for who granted access.';

COMMIT;
