export {
  publishCockpitEvent,
  subscribeCockpitEvents,
  __resetCockpitBusForTests,
} from './bus.js';
export type {
  CockpitEvent,
  CockpitEventKind,
  DecisionRecordedEvent,
  ReminderFiredEvent,
  OpportunityScanCompletedEvent,
  RiskChangedEvent,
  StaffShiftEvent,
  ComplianceDeadlineApproachingEvent,
  PersonaActedEvent,
  PersonaProposesEvent,
  RentCollectedEvent,
  LeaseSignedEvent,
  LeaseRenewedEvent,
  LeaseTerminatedEvent,
  MaintenanceCompletedEvent,
  MaintenanceRequestedEvent,
  InspectionCompletedEvent,
  InspectionScheduledEvent,
  ApplicationSubmittedEvent,
  ApplicationApprovedEvent,
  ApplicationRejectedEvent,
  ViewingScheduledEvent,
  ViewingCompletedEvent,
  RegulatorRequestReceivedEvent,
  RegulatorRequestStatusChangedEvent,
  RfaDispatchedEvent,
  TaskAssignedEvent,
  SafetyIncidentEvent,
  RentPayoutInitiatedEvent,
  PayrollCommittedEvent,
  LicenceRenewedEvent,
  ChatHandoffEvent,
  ManagerApprovedEvent,
  BidPlacedEvent,
  IncidentEscalatedEvent,
  CockpitTabSpawnedEvent,
  CockpitTabUpdatedEvent,
  CockpitTabRemovedEvent,
  CockpitTabProposedEvent,
  PropertyCelebrateEvent,
} from './types.js';
export { COCKPIT_EVENT_KINDS } from './types.js';

export {
  publishDecisionRecorded,
  publishReminderFired,
  publishComplianceDeadlineApproaching,
  publishStaffShiftEvent,
  publishLeaseSigned,
  publishLeaseTerminated,
  // DIM-B port — 6 lifecycle publishers.
  publishRentCollected,
  publishMaintenanceCompleted,
  publishInspectionCompleted,
  publishApplicationApproved,
  publishBidPlaced,
  publishRentPayoutInitiated,
  publishSafetyIncidentReported,
  publishLicenceRenewed,
  type PublishDecisionRecordedInput,
  type PublishReminderFiredInput,
  type PublishComplianceDeadlineInput,
  type PublishStaffShiftInput,
  type PublishLeaseSignedInput,
  type PublishLeaseTerminatedInput,
  type PublishRentCollectedInput,
  type PublishMaintenanceCompletedInput,
  type PublishInspectionCompletedInput,
  type PublishApplicationApprovedInput,
  type PublishBidPlacedInput,
  type PublishRentPayoutInitiatedInput,
  type PublishSafetyIncidentInput,
  type PublishLicenceRenewedInput,
} from './publishers.js';
