/**
 * Default timezone for every non-African ISO-3166-1 alpha-2 jurisdiction.
 *
 * For multi-zone countries (US, RU, AU, CA, BR, MX, CN-de-facto-single,
 * KZ) the entry uses the canonical capital-city zone — apps SHOULD
 * prefer browser / IP detection in those regions, since the capital-city
 * default is wrong for >40% of users.
 *
 * DST flags reflect the 2026 status: EU + UK + USA + most of Australia
 * observe; Russia + China + India + most of Africa do not.
 */

import type { JurisdictionDefault } from '../types.js';

export const REST_OF_WORLD_DEFAULTS: ReadonlyArray<JurisdictionDefault> = [
  // -------------------------------- Europe --------------------------------
  { jurisdiction: 'AD', timezone: 'Europe/Andorra', canonicalCity: 'Andorra la Vella', isMultiZone: false, observesDST: true },
  { jurisdiction: 'AL', timezone: 'Europe/Tirane', canonicalCity: 'Tirana', isMultiZone: false, observesDST: true },
  { jurisdiction: 'AT', timezone: 'Europe/Vienna', canonicalCity: 'Vienna', isMultiZone: false, observesDST: true },
  { jurisdiction: 'BA', timezone: 'Europe/Sarajevo', canonicalCity: 'Sarajevo', isMultiZone: false, observesDST: true },
  { jurisdiction: 'BE', timezone: 'Europe/Brussels', canonicalCity: 'Brussels', isMultiZone: false, observesDST: true },
  { jurisdiction: 'BG', timezone: 'Europe/Sofia', canonicalCity: 'Sofia', isMultiZone: false, observesDST: true },
  { jurisdiction: 'BY', timezone: 'Europe/Minsk', canonicalCity: 'Minsk', isMultiZone: false, observesDST: false },
  { jurisdiction: 'CH', timezone: 'Europe/Zurich', canonicalCity: 'Bern', isMultiZone: false, observesDST: true },
  { jurisdiction: 'CY', timezone: 'Asia/Nicosia', canonicalCity: 'Nicosia', isMultiZone: false, observesDST: true },
  { jurisdiction: 'CZ', timezone: 'Europe/Prague', canonicalCity: 'Prague', isMultiZone: false, observesDST: true },
  { jurisdiction: 'DE', timezone: 'Europe/Berlin', canonicalCity: 'Berlin', isMultiZone: false, observesDST: true },
  { jurisdiction: 'DK', timezone: 'Europe/Copenhagen', canonicalCity: 'Copenhagen', isMultiZone: false, observesDST: true },
  { jurisdiction: 'EE', timezone: 'Europe/Tallinn', canonicalCity: 'Tallinn', isMultiZone: false, observesDST: true },
  { jurisdiction: 'ES', timezone: 'Europe/Madrid', canonicalCity: 'Madrid', isMultiZone: true, observesDST: true },
  { jurisdiction: 'FI', timezone: 'Europe/Helsinki', canonicalCity: 'Helsinki', isMultiZone: false, observesDST: true },
  { jurisdiction: 'FR', timezone: 'Europe/Paris', canonicalCity: 'Paris', isMultiZone: false, observesDST: true },
  { jurisdiction: 'GB', timezone: 'Europe/London', canonicalCity: 'London', isMultiZone: false, observesDST: true },
  { jurisdiction: 'GR', timezone: 'Europe/Athens', canonicalCity: 'Athens', isMultiZone: false, observesDST: true },
  { jurisdiction: 'HR', timezone: 'Europe/Zagreb', canonicalCity: 'Zagreb', isMultiZone: false, observesDST: true },
  { jurisdiction: 'HU', timezone: 'Europe/Budapest', canonicalCity: 'Budapest', isMultiZone: false, observesDST: true },
  { jurisdiction: 'IE', timezone: 'Europe/Dublin', canonicalCity: 'Dublin', isMultiZone: false, observesDST: true },
  { jurisdiction: 'IS', timezone: 'Atlantic/Reykjavik', canonicalCity: 'Reykjavik', isMultiZone: false, observesDST: false },
  { jurisdiction: 'IT', timezone: 'Europe/Rome', canonicalCity: 'Rome', isMultiZone: false, observesDST: true },
  { jurisdiction: 'LI', timezone: 'Europe/Vaduz', canonicalCity: 'Vaduz', isMultiZone: false, observesDST: true },
  { jurisdiction: 'LT', timezone: 'Europe/Vilnius', canonicalCity: 'Vilnius', isMultiZone: false, observesDST: true },
  { jurisdiction: 'LU', timezone: 'Europe/Luxembourg', canonicalCity: 'Luxembourg', isMultiZone: false, observesDST: true },
  { jurisdiction: 'LV', timezone: 'Europe/Riga', canonicalCity: 'Riga', isMultiZone: false, observesDST: true },
  { jurisdiction: 'MC', timezone: 'Europe/Monaco', canonicalCity: 'Monaco', isMultiZone: false, observesDST: true },
  { jurisdiction: 'MD', timezone: 'Europe/Chisinau', canonicalCity: 'Chisinau', isMultiZone: false, observesDST: true },
  { jurisdiction: 'ME', timezone: 'Europe/Podgorica', canonicalCity: 'Podgorica', isMultiZone: false, observesDST: true },
  { jurisdiction: 'MK', timezone: 'Europe/Skopje', canonicalCity: 'Skopje', isMultiZone: false, observesDST: true },
  { jurisdiction: 'MT', timezone: 'Europe/Malta', canonicalCity: 'Valletta', isMultiZone: false, observesDST: true },
  { jurisdiction: 'NL', timezone: 'Europe/Amsterdam', canonicalCity: 'Amsterdam', isMultiZone: false, observesDST: true },
  { jurisdiction: 'NO', timezone: 'Europe/Oslo', canonicalCity: 'Oslo', isMultiZone: false, observesDST: true },
  { jurisdiction: 'PL', timezone: 'Europe/Warsaw', canonicalCity: 'Warsaw', isMultiZone: false, observesDST: true },
  { jurisdiction: 'PT', timezone: 'Europe/Lisbon', canonicalCity: 'Lisbon', isMultiZone: true, observesDST: true },
  { jurisdiction: 'RO', timezone: 'Europe/Bucharest', canonicalCity: 'Bucharest', isMultiZone: false, observesDST: true },
  { jurisdiction: 'RS', timezone: 'Europe/Belgrade', canonicalCity: 'Belgrade', isMultiZone: false, observesDST: true },
  { jurisdiction: 'RU', timezone: 'Europe/Moscow', canonicalCity: 'Moscow', isMultiZone: true, observesDST: false },
  { jurisdiction: 'SE', timezone: 'Europe/Stockholm', canonicalCity: 'Stockholm', isMultiZone: false, observesDST: true },
  { jurisdiction: 'SI', timezone: 'Europe/Ljubljana', canonicalCity: 'Ljubljana', isMultiZone: false, observesDST: true },
  { jurisdiction: 'SK', timezone: 'Europe/Bratislava', canonicalCity: 'Bratislava', isMultiZone: false, observesDST: true },
  { jurisdiction: 'SM', timezone: 'Europe/San_Marino', canonicalCity: 'San Marino', isMultiZone: false, observesDST: true },
  { jurisdiction: 'TR', timezone: 'Europe/Istanbul', canonicalCity: 'Ankara', isMultiZone: false, observesDST: false },
  { jurisdiction: 'UA', timezone: 'Europe/Kyiv', canonicalCity: 'Kyiv', isMultiZone: false, observesDST: true },
  { jurisdiction: 'VA', timezone: 'Europe/Vatican', canonicalCity: 'Vatican City', isMultiZone: false, observesDST: true },
  { jurisdiction: 'XK', timezone: 'Europe/Belgrade', canonicalCity: 'Pristina', isMultiZone: false, observesDST: true },

  // -------------------------------- Americas ------------------------------
  { jurisdiction: 'AG', timezone: 'America/Antigua', canonicalCity: "St. John's", isMultiZone: false, observesDST: false },
  { jurisdiction: 'AR', timezone: 'America/Argentina/Buenos_Aires', canonicalCity: 'Buenos Aires', isMultiZone: true, observesDST: false },
  { jurisdiction: 'BB', timezone: 'America/Barbados', canonicalCity: 'Bridgetown', isMultiZone: false, observesDST: false },
  { jurisdiction: 'BO', timezone: 'America/La_Paz', canonicalCity: 'La Paz', isMultiZone: false, observesDST: false },
  { jurisdiction: 'BR', timezone: 'America/Sao_Paulo', canonicalCity: 'Brasilia', isMultiZone: true, observesDST: false },
  { jurisdiction: 'BS', timezone: 'America/Nassau', canonicalCity: 'Nassau', isMultiZone: false, observesDST: true },
  { jurisdiction: 'BZ', timezone: 'America/Belize', canonicalCity: 'Belmopan', isMultiZone: false, observesDST: false },
  { jurisdiction: 'CA', timezone: 'America/Toronto', canonicalCity: 'Ottawa', isMultiZone: true, observesDST: true },
  { jurisdiction: 'CL', timezone: 'America/Santiago', canonicalCity: 'Santiago', isMultiZone: true, observesDST: true },
  { jurisdiction: 'CO', timezone: 'America/Bogota', canonicalCity: 'Bogota', isMultiZone: false, observesDST: false },
  { jurisdiction: 'CR', timezone: 'America/Costa_Rica', canonicalCity: 'San Jose', isMultiZone: false, observesDST: false },
  { jurisdiction: 'CU', timezone: 'America/Havana', canonicalCity: 'Havana', isMultiZone: false, observesDST: true },
  { jurisdiction: 'DM', timezone: 'America/Dominica', canonicalCity: 'Roseau', isMultiZone: false, observesDST: false },
  { jurisdiction: 'DO', timezone: 'America/Santo_Domingo', canonicalCity: 'Santo Domingo', isMultiZone: false, observesDST: false },
  { jurisdiction: 'EC', timezone: 'America/Guayaquil', canonicalCity: 'Quito', isMultiZone: true, observesDST: false },
  { jurisdiction: 'GD', timezone: 'America/Grenada', canonicalCity: "St. George's", isMultiZone: false, observesDST: false },
  { jurisdiction: 'GT', timezone: 'America/Guatemala', canonicalCity: 'Guatemala City', isMultiZone: false, observesDST: false },
  { jurisdiction: 'GY', timezone: 'America/Guyana', canonicalCity: 'Georgetown', isMultiZone: false, observesDST: false },
  { jurisdiction: 'HN', timezone: 'America/Tegucigalpa', canonicalCity: 'Tegucigalpa', isMultiZone: false, observesDST: false },
  { jurisdiction: 'HT', timezone: 'America/Port-au-Prince', canonicalCity: 'Port-au-Prince', isMultiZone: false, observesDST: true },
  { jurisdiction: 'JM', timezone: 'America/Jamaica', canonicalCity: 'Kingston', isMultiZone: false, observesDST: false },
  { jurisdiction: 'KN', timezone: 'America/St_Kitts', canonicalCity: 'Basseterre', isMultiZone: false, observesDST: false },
  { jurisdiction: 'LC', timezone: 'America/St_Lucia', canonicalCity: 'Castries', isMultiZone: false, observesDST: false },
  { jurisdiction: 'MX', timezone: 'America/Mexico_City', canonicalCity: 'Mexico City', isMultiZone: true, observesDST: false },
  { jurisdiction: 'NI', timezone: 'America/Managua', canonicalCity: 'Managua', isMultiZone: false, observesDST: false },
  { jurisdiction: 'PA', timezone: 'America/Panama', canonicalCity: 'Panama City', isMultiZone: false, observesDST: false },
  { jurisdiction: 'PE', timezone: 'America/Lima', canonicalCity: 'Lima', isMultiZone: false, observesDST: false },
  { jurisdiction: 'PY', timezone: 'America/Asuncion', canonicalCity: 'Asuncion', isMultiZone: false, observesDST: true },
  { jurisdiction: 'SR', timezone: 'America/Paramaribo', canonicalCity: 'Paramaribo', isMultiZone: false, observesDST: false },
  { jurisdiction: 'SV', timezone: 'America/El_Salvador', canonicalCity: 'San Salvador', isMultiZone: false, observesDST: false },
  { jurisdiction: 'TT', timezone: 'America/Port_of_Spain', canonicalCity: 'Port of Spain', isMultiZone: false, observesDST: false },
  { jurisdiction: 'US', timezone: 'America/New_York', canonicalCity: 'Washington D.C.', isMultiZone: true, observesDST: true },
  { jurisdiction: 'UY', timezone: 'America/Montevideo', canonicalCity: 'Montevideo', isMultiZone: false, observesDST: false },
  { jurisdiction: 'VC', timezone: 'America/St_Vincent', canonicalCity: 'Kingstown', isMultiZone: false, observesDST: false },
  { jurisdiction: 'VE', timezone: 'America/Caracas', canonicalCity: 'Caracas', isMultiZone: false, observesDST: false },

  // ---------------------------------- Asia --------------------------------
  { jurisdiction: 'AE', timezone: 'Asia/Dubai', canonicalCity: 'Abu Dhabi', isMultiZone: false, observesDST: false },
  { jurisdiction: 'AF', timezone: 'Asia/Kabul', canonicalCity: 'Kabul', isMultiZone: false, observesDST: false },
  { jurisdiction: 'AM', timezone: 'Asia/Yerevan', canonicalCity: 'Yerevan', isMultiZone: false, observesDST: false },
  { jurisdiction: 'AZ', timezone: 'Asia/Baku', canonicalCity: 'Baku', isMultiZone: false, observesDST: false },
  { jurisdiction: 'BD', timezone: 'Asia/Dhaka', canonicalCity: 'Dhaka', isMultiZone: false, observesDST: false },
  { jurisdiction: 'BH', timezone: 'Asia/Bahrain', canonicalCity: 'Manama', isMultiZone: false, observesDST: false },
  { jurisdiction: 'BN', timezone: 'Asia/Brunei', canonicalCity: 'Bandar Seri Begawan', isMultiZone: false, observesDST: false },
  { jurisdiction: 'BT', timezone: 'Asia/Thimphu', canonicalCity: 'Thimphu', isMultiZone: false, observesDST: false },
  { jurisdiction: 'CN', timezone: 'Asia/Shanghai', canonicalCity: 'Beijing', isMultiZone: false, observesDST: false },
  { jurisdiction: 'GE', timezone: 'Asia/Tbilisi', canonicalCity: 'Tbilisi', isMultiZone: false, observesDST: false },
  { jurisdiction: 'HK', timezone: 'Asia/Hong_Kong', canonicalCity: 'Hong Kong', isMultiZone: false, observesDST: false },
  { jurisdiction: 'ID', timezone: 'Asia/Jakarta', canonicalCity: 'Jakarta', isMultiZone: true, observesDST: false },
  { jurisdiction: 'IL', timezone: 'Asia/Jerusalem', canonicalCity: 'Jerusalem', isMultiZone: false, observesDST: true },
  { jurisdiction: 'IN', timezone: 'Asia/Kolkata', canonicalCity: 'New Delhi', isMultiZone: false, observesDST: false },
  { jurisdiction: 'IQ', timezone: 'Asia/Baghdad', canonicalCity: 'Baghdad', isMultiZone: false, observesDST: false },
  { jurisdiction: 'IR', timezone: 'Asia/Tehran', canonicalCity: 'Tehran', isMultiZone: false, observesDST: false },
  { jurisdiction: 'JO', timezone: 'Asia/Amman', canonicalCity: 'Amman', isMultiZone: false, observesDST: false },
  { jurisdiction: 'JP', timezone: 'Asia/Tokyo', canonicalCity: 'Tokyo', isMultiZone: false, observesDST: false },
  { jurisdiction: 'KG', timezone: 'Asia/Bishkek', canonicalCity: 'Bishkek', isMultiZone: false, observesDST: false },
  { jurisdiction: 'KH', timezone: 'Asia/Phnom_Penh', canonicalCity: 'Phnom Penh', isMultiZone: false, observesDST: false },
  { jurisdiction: 'KP', timezone: 'Asia/Pyongyang', canonicalCity: 'Pyongyang', isMultiZone: false, observesDST: false },
  { jurisdiction: 'KR', timezone: 'Asia/Seoul', canonicalCity: 'Seoul', isMultiZone: false, observesDST: false },
  { jurisdiction: 'KW', timezone: 'Asia/Kuwait', canonicalCity: 'Kuwait City', isMultiZone: false, observesDST: false },
  { jurisdiction: 'KZ', timezone: 'Asia/Almaty', canonicalCity: 'Astana', isMultiZone: true, observesDST: false },
  { jurisdiction: 'LA', timezone: 'Asia/Vientiane', canonicalCity: 'Vientiane', isMultiZone: false, observesDST: false },
  { jurisdiction: 'LB', timezone: 'Asia/Beirut', canonicalCity: 'Beirut', isMultiZone: false, observesDST: true },
  { jurisdiction: 'LK', timezone: 'Asia/Colombo', canonicalCity: 'Colombo', isMultiZone: false, observesDST: false },
  { jurisdiction: 'MM', timezone: 'Asia/Yangon', canonicalCity: 'Naypyidaw', isMultiZone: false, observesDST: false },
  { jurisdiction: 'MN', timezone: 'Asia/Ulaanbaatar', canonicalCity: 'Ulaanbaatar', isMultiZone: false, observesDST: false },
  { jurisdiction: 'MO', timezone: 'Asia/Macau', canonicalCity: 'Macau', isMultiZone: false, observesDST: false },
  { jurisdiction: 'MV', timezone: 'Indian/Maldives', canonicalCity: 'Male', isMultiZone: false, observesDST: false },
  { jurisdiction: 'MY', timezone: 'Asia/Kuala_Lumpur', canonicalCity: 'Putrajaya', isMultiZone: false, observesDST: false },
  { jurisdiction: 'NP', timezone: 'Asia/Kathmandu', canonicalCity: 'Kathmandu', isMultiZone: false, observesDST: false },
  { jurisdiction: 'OM', timezone: 'Asia/Muscat', canonicalCity: 'Muscat', isMultiZone: false, observesDST: false },
  { jurisdiction: 'PH', timezone: 'Asia/Manila', canonicalCity: 'Manila', isMultiZone: false, observesDST: false },
  { jurisdiction: 'PK', timezone: 'Asia/Karachi', canonicalCity: 'Islamabad', isMultiZone: false, observesDST: false },
  { jurisdiction: 'PS', timezone: 'Asia/Gaza', canonicalCity: 'Ramallah', isMultiZone: false, observesDST: true },
  { jurisdiction: 'QA', timezone: 'Asia/Qatar', canonicalCity: 'Doha', isMultiZone: false, observesDST: false },
  { jurisdiction: 'SA', timezone: 'Asia/Riyadh', canonicalCity: 'Riyadh', isMultiZone: false, observesDST: false },
  { jurisdiction: 'SG', timezone: 'Asia/Singapore', canonicalCity: 'Singapore', isMultiZone: false, observesDST: false },
  { jurisdiction: 'SY', timezone: 'Asia/Damascus', canonicalCity: 'Damascus', isMultiZone: false, observesDST: false },
  { jurisdiction: 'TH', timezone: 'Asia/Bangkok', canonicalCity: 'Bangkok', isMultiZone: false, observesDST: false },
  { jurisdiction: 'TJ', timezone: 'Asia/Dushanbe', canonicalCity: 'Dushanbe', isMultiZone: false, observesDST: false },
  { jurisdiction: 'TM', timezone: 'Asia/Ashgabat', canonicalCity: 'Ashgabat', isMultiZone: false, observesDST: false },
  { jurisdiction: 'TW', timezone: 'Asia/Taipei', canonicalCity: 'Taipei', isMultiZone: false, observesDST: false },
  { jurisdiction: 'UZ', timezone: 'Asia/Tashkent', canonicalCity: 'Tashkent', isMultiZone: false, observesDST: false },
  { jurisdiction: 'VN', timezone: 'Asia/Ho_Chi_Minh', canonicalCity: 'Hanoi', isMultiZone: false, observesDST: false },
  { jurisdiction: 'YE', timezone: 'Asia/Aden', canonicalCity: "Sana'a", isMultiZone: false, observesDST: false },

  // -------------------------------- Oceania -------------------------------
  { jurisdiction: 'AU', timezone: 'Australia/Sydney', canonicalCity: 'Canberra', isMultiZone: true, observesDST: true },
  { jurisdiction: 'FJ', timezone: 'Pacific/Fiji', canonicalCity: 'Suva', isMultiZone: false, observesDST: false },
  { jurisdiction: 'KI', timezone: 'Pacific/Tarawa', canonicalCity: 'South Tarawa', isMultiZone: true, observesDST: false },
  { jurisdiction: 'MH', timezone: 'Pacific/Majuro', canonicalCity: 'Majuro', isMultiZone: false, observesDST: false },
  { jurisdiction: 'NR', timezone: 'Pacific/Nauru', canonicalCity: 'Yaren', isMultiZone: false, observesDST: false },
  { jurisdiction: 'NZ', timezone: 'Pacific/Auckland', canonicalCity: 'Wellington', isMultiZone: true, observesDST: true },
  { jurisdiction: 'PG', timezone: 'Pacific/Port_Moresby', canonicalCity: 'Port Moresby', isMultiZone: true, observesDST: false },
  { jurisdiction: 'PW', timezone: 'Pacific/Palau', canonicalCity: 'Ngerulmud', isMultiZone: false, observesDST: false },
  { jurisdiction: 'SB', timezone: 'Pacific/Guadalcanal', canonicalCity: 'Honiara', isMultiZone: false, observesDST: false },
  { jurisdiction: 'TO', timezone: 'Pacific/Tongatapu', canonicalCity: "Nuku'alofa", isMultiZone: false, observesDST: false },
  { jurisdiction: 'TV', timezone: 'Pacific/Funafuti', canonicalCity: 'Funafuti', isMultiZone: false, observesDST: false },
  { jurisdiction: 'VU', timezone: 'Pacific/Efate', canonicalCity: 'Port Vila', isMultiZone: false, observesDST: false },
  { jurisdiction: 'WS', timezone: 'Pacific/Apia', canonicalCity: 'Apia', isMultiZone: false, observesDST: false },
  { jurisdiction: 'FM', timezone: 'Pacific/Pohnpei', canonicalCity: 'Palikir', isMultiZone: true, observesDST: false },
];
