apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bossnyumba-jobs

resources:
  - ../../base

images:
  - name: ghcr.io/bossnyumba/brain-evolution-worker
    newTag: ${IMAGE_TAG}

patches:
  - target:
      kind: CronJob
      name: brain-evolution-worker
    patch: |-
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "4"
            memory: "8Gi"
