/**
 * @bossnyumba/action-runtime — types.
 *
 * Zod schemas for ActionPlan, ActionStep, Precondition, Compensation. The
 * runtime never mutates these; it always derives the next state from
 * the current state + the step handler's result.
 *
 * Status machines:
 *
 *   ActionPlan: DRAFT → ROUTED_FOR_APPROVAL → APPROVED → EXECUTING →
 *               COMPLETED | PARTIAL | FAILED | COMPENSATED |
 *               COMPENSATION_FAILED | EXPIRED | CANCELLED
 *
 *   ActionStep: PENDING → RUNNING → SUCCEEDED | FAILED →
 *               COMPENSATING → COMPENSATED | SKIPPED
 */

import { z } from 'zod';
import { STEP_KINDS, type StepKind } from '@bossnyumba/approval-matrix-dsl';

export { STEP_KINDS };
export type { StepKind };

// ─────────────────────────────────────────────────────────────────────
// Status enums
// ─────────────────────────────────────────────────────────────────────

export const PLAN_STATUSES = [
  'DRAFT',
  'ROUTED_FOR_APPROVAL',
  'APPROVED',
  'EXECUTING',
  'PARTIAL',
  'COMPLETED',
  'FAILED',
  'COMPENSATED',
  'COMPENSATION_FAILED',
  'EXPIRED',
  'CANCELLED',
] as const;
export const PlanStatusSchema = z.enum(PLAN_STATUSES);
export type PlanStatus = z.infer<typeof PlanStatusSchema>;

export const STEP_STATUSES = [
  'PENDING',
  'RUNNING',
  'SUCCEEDED',
  'FAILED',
  'COMPENSATING',
  'COMPENSATED',
  'SKIPPED',
] as const;
export const StepStatusSchema = z.enum(STEP_STATUSES);
export type StepStatus = z.infer<typeof StepStatusSchema>;

// ─────────────────────────────────────────────────────────────────────
// Precondition — re-checked at execute time
// ─────────────────────────────────────────────────────────────────────

export const PRECONDITION_KINDS = [
  'kill_switch_open',
  'autonomy_cap_within_limit',
  'persona_still_bound',
  'budget_remaining',
  'idempotency_unconsumed',
  'parent_step_succeeded',
  'expression',
] as const;

export const PreconditionSchema = z.object({
  kind: z.enum(PRECONDITION_KINDS),
  /**
   * For `expression`: a tiny JSON shape the preconditions module
   * evaluates against the live context. Keys vary by kind; the runtime
   * passes the WHOLE object to the precondition handler.
   */
  params: z.record(z.string(), z.unknown()).optional(),
  /**
   * Human-readable failure message for HITL UI / audit chain.
   */
  failureMessage: z.string().optional(),
});
export type Precondition = z.infer<typeof PreconditionSchema>;

// ─────────────────────────────────────────────────────────────────────
// Compensation spec — drives the per-step rollback registry
// ─────────────────────────────────────────────────────────────────────

export const CompensationSpecSchema = z.object({
  /**
   * The compensation handler key. Default = `${stepKind}.reverse` —
   * the registry resolves this to a function that reverses the effect
   * of the original step.
   */
  handlerKey: z.string().optional(),
  /**
   * Extra payload merged into the original step payload at
   * compensation time (e.g. a retraction reason).
   */
  payloadOverride: z.record(z.string(), z.unknown()).optional(),
  /**
   * If true, compensation failures fail the plan with
   * COMPENSATION_FAILED. If false, they're logged + skipped.
   */
  hardCompensation: z.boolean().default(true),
});
export type CompensationSpec = z.infer<typeof CompensationSpecSchema>;

// ─────────────────────────────────────────────────────────────────────
// ActionStep
// ─────────────────────────────────────────────────────────────────────

export const StepKindSchema = z.enum(STEP_KINDS);

/**
 * Free-form payload — passed through to the step handler. We keep this
 * as a plain Record so callers can type-narrow with confidence and the
 * step-handler files don't have to defensively cast each key.
 */
export const PayloadSchema = z
  .record(z.string(), z.unknown())
  .default({}) as unknown as z.ZodType<Record<string, unknown>, z.ZodTypeDef, Record<string, unknown> | undefined>;

export const ActionStepSchema = z.object({
  /** Stable id; generated by compile() if absent. */
  id: z.string().optional(),
  stepIndex: z.number().int().nonnegative(),
  kind: StepKindSchema,
  payload: PayloadSchema,
  /** Preconditions checked at execute time (in order). */
  preconditions: z.array(PreconditionSchema).default([]),
  /**
   * Action prefix that the policy-gate uses to find a literal rule.
   * For SOVEREIGN / kill-switch / four-eye / policy-rollout the
   * runtime DEMANDS a matching policy; no resolver generalisation.
   */
  policyActionPrefix: z.string().optional(),
  /** If true, blocks the saga until an external approval signal arrives. */
  hitlCheckpoint: z.boolean().default(false),
  /**
   * If set, plug this step into the approval-matrix-dsl evaluator with
   * these attributes overlaid (used for cases where the payload doesn't
   * directly expose the routing-relevant attributes).
   */
  routingAttributes: z.record(z.string(), z.unknown()).optional(),
  /** Compensation spec for this step. */
  compensation: CompensationSpecSchema.optional(),
  /** Idempotency key for at-least-once delivery (generated if absent). */
  toolCallRef: z.string().optional(),
});
/**
 * Manually-narrowed ActionStep so the runtime sees `payload` as a
 * proper `Record<string, unknown>`. Zod 3.25's record + default
 * inference widens to `unknown` which breaks the per-key access in
 * each step handler.
 */
export type ActionStep = Omit<z.infer<typeof ActionStepSchema>, 'payload'> & {
  payload: Record<string, unknown>;
};

// ─────────────────────────────────────────────────────────────────────
// ActionPlan
// ─────────────────────────────────────────────────────────────────────

export const ActionPlanSchema = z.object({
  /** Stable id; generated by compile() if absent. */
  id: z.string().optional(),
  tenantId: z.string(),
  personaId: z.string(),
  /** Module-id (estate / finance / hr / …). */
  moduleId: z.string().optional(),
  /** High-level goal slug. */
  intent: z.string(),
  /** Step graph in execution order. */
  steps: z.array(ActionStepSchema).min(1),
  /** Per-plan budget cap (micro-USD). */
  budgetMicros: z.number().int().nonnegative(),
  /** Source provenance. */
  source: z
    .object({
      captureId: z.string().optional(),
      briefId: z.string().optional(),
      documentId: z.string().optional(),
    })
    .optional(),
  /** Expiry ISO timestamp. */
  expiresAt: z.string().datetime().optional(),
});
export type ActionPlan = z.infer<typeof ActionPlanSchema>;

// ─────────────────────────────────────────────────────────────────────
// Persisted row shapes (mirror DB schema)
// ─────────────────────────────────────────────────────────────────────

export interface PersistedActionPlan {
  readonly id: string;
  readonly tenantId: string;
  readonly personaId: string;
  readonly moduleId: string | null;
  readonly intent: string;
  readonly planJsonb: ActionPlan;
  readonly status: PlanStatus;
  readonly auditChainLink: string | null;
  readonly budgetMicros: number;
  readonly budgetUsedMicros: number;
  readonly sourceCaptureId: string | null;
  readonly sourceBriefId: string | null;
  readonly sourceDocumentId: string | null;
  readonly createdAt: Date;
  readonly updatedAt: Date;
  readonly expiresAt: Date;
}

export interface PersistedActionStep {
  readonly id: string;
  readonly planId: string;
  readonly tenantId: string;
  readonly stepIndex: number;
  readonly kind: StepKind;
  readonly payloadJsonb: Readonly<Record<string, unknown>>;
  readonly toolCallRef: string | null;
  readonly otelSpanId: string | null;
  readonly auditChainId: string | null;
  readonly status: StepStatus;
  readonly attempts: number;
  readonly lastError: string | null;
  readonly compensationStepIndex: number | null;
  readonly startedAt: Date | null;
  readonly finishedAt: Date | null;
  readonly createdAt: Date;
}

// ─────────────────────────────────────────────────────────────────────
// Quota types
// ─────────────────────────────────────────────────────────────────────

export interface ActionQuotaState {
  readonly tenantId: string;
  readonly personaId: string | null;
  readonly periodDate: string; // ISO date
  readonly plansCreated: number;
  readonly plansApproved: number;
  readonly plansExecuted: number;
  readonly moneyMicros: number;
  readonly budgetMicrosUsed: number;
}

// ─────────────────────────────────────────────────────────────────────
// Error model
// ─────────────────────────────────────────────────────────────────────

export type ActionRuntimeErrorCode =
  | 'BUDGET_EXCEEDED'
  | 'QUOTA_EXCEEDED'
  | 'KILL_SWITCH_OPEN'
  | 'PERSONA_NOT_BOUND'
  | 'AUTONOMY_CAP_EXCEEDED'
  | 'PRECONDITION_FAILED'
  | 'PLAN_EXPIRED'
  | 'IDEMPOTENT_REPLAY'
  | 'STEP_HANDLER_ERROR'
  | 'COMPENSATION_FAILED'
  | 'APPROVAL_BLOCKED'
  | 'INVALID_PLAN';

export class ActionRuntimeError extends Error {
  constructor(
    public readonly code: ActionRuntimeErrorCode,
    message: string,
    public readonly details?: Readonly<Record<string, unknown>>,
  ) {
    super(message);
    this.name = 'ActionRuntimeError';
  }
}
