apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: parcel-service
  labels:
    app.kubernetes.io/name: parcel-service
    app.kubernetes.io/part-of: bossnyumba
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: parcel-service
