apiVersion: v1
kind: Service
metadata:
  name: parcel-service
  labels:
    app.kubernetes.io/name: parcel-service
    app.kubernetes.io/part-of: bossnyumba
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: parcel-service
  ports:
    - name: http
      port: 80
      targetPort: 3017
      protocol: TCP
    - name: metrics
      port: 9464
      targetPort: 9464
      protocol: TCP
