apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bossnyumba.fullname" . }}-config
  labels:
    {{- include "bossnyumba.labels" . | nindent 4 }}
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  SENTRY_ENVIRONMENT: "production"
  POSTHOG_HOST: "https://eu.posthog.com"
  CORS_ALLOWED_ORIGINS: "https://bossnyumba.com,https://admin.bossnyumba.com,https://owners.bossnyumba.com,https://manage.bossnyumba.com"
