{{- if not .Values.secrets.externalSecrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: bossnyumba-secrets
  labels:
    {{- include "bossnyumba.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets.inline }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- else -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bossnyumba-secrets
  labels:
    {{- include "bossnyumba.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: {{ .Values.secrets.externalSecrets.secretStoreRef.kind }}
    name: {{ .Values.secrets.externalSecrets.secretStoreRef.name }}
  target:
    name: bossnyumba-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: bossnyumba/prod
{{- end -}}
