{{- if .Values.monitoring.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "bossnyumba.fullname" . }}
  labels:
    {{- include "bossnyumba.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "bossnyumba.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: gateway
  endpoints:
    - port: http
      path: {{ .Values.monitoring.serviceMonitor.path }}
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
{{- end -}}
