{{- $root := . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bossnyumba.fullname" . }}-gateway
  labels:
    {{- include "bossnyumba.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: http
      name: http
  selector:
    {{- include "bossnyumba.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
---
{{- range $name, $app := .Values.apps }}
{{- if $app.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bossnyumba.fullname" $root }}-{{ $name | kebabcase }}
  labels:
    {{- include "bossnyumba.labels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ $name | kebabcase }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $app.port }}
      targetPort: http
      name: http
  selector:
    {{- include "bossnyumba.selectorLabels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ $name | kebabcase }}
---
{{- end }}
{{- end }}
