/**
 * Provenance-stamp tests.
 */

import { describe, expect, it } from 'vitest';
import { hashBytes, stampProvenance } from '../provenance/provenance-stamp.js';
import type { ProvenanceSigner } from '../types.js';

const BODY = Uint8Array.from([1, 2, 3, 4, 5]);

describe('provenance stamp', () => {
  it('always attaches a visible watermark plan', () => {
    const stamp = stampProvenance({
      kind: 'marketplace_listing_hero',
      body: BODY,
      synthIdPresent: false,
      watermarkLabel: 'Generated by Borjie',
      stampedAt: '2026-06-08T00:00:00.000Z',
    });
    expect(stamp.watermark).toBeDefined();
    expect(stamp.watermark.text).toBe('Generated by Borjie');
    expect(stamp.watermark.opacity).toBeGreaterThan(0);
  });

  it('binds the content hash to the bytes (hard binding)', () => {
    const stamp = stampProvenance({
      kind: 'property_hero',
      body: BODY,
      synthIdPresent: false,
      watermarkLabel: 'Generated by BN',
      stampedAt: '2026-06-08T00:00:00.000Z',
    });
    expect(stamp.contentHash).toBe(hashBytes(BODY));
    expect(stamp.contentHash).toHaveLength(64);
  });

  it('marks the stamp unsigned when no signer is injected (never fakes a signature)', () => {
    const stamp = stampProvenance({
      kind: 'mining_site_map',
      body: BODY,
      synthIdPresent: false,
      watermarkLabel: 'Generated by Borjie',
      stampedAt: '2026-06-08T00:00:00.000Z',
    });
    expect(stamp.signer).toBe('unsigned');
    expect(stamp.manifestDigest).toHaveLength(64);
  });

  it('uses an injected signer for the manifest digest', () => {
    const signer: ProvenanceSigner = {
      subject: 'CN=Borjie Brand Cert',
      sign: (payload) => `SIG(${payload.length})`,
    };
    const stamp = stampProvenance({
      kind: 'investor_brand_video',
      body: BODY,
      synthIdPresent: true,
      watermarkLabel: 'Generated by Borjie',
      stampedAt: '2026-06-08T00:00:00.000Z',
      signer,
    });
    expect(stamp.signer).toBe('CN=Borjie Brand Cert');
    expect(stamp.manifestDigest.startsWith('SIG(')).toBe(true);
    expect(stamp.synthIdPresent).toBe(true);
  });

  it('records the SynthID-present flag', () => {
    const stamp = stampProvenance({
      kind: 'investor_brand_video',
      body: BODY,
      synthIdPresent: true,
      watermarkLabel: 'Generated by Borjie',
      stampedAt: '2026-06-08T00:00:00.000Z',
    });
    expect(stamp.synthIdPresent).toBe(true);
  });
});
