import Link from 'next/link';
import { Wordmark } from '@bossnyumba/design-system';

export function Footer() {
  return (
    <footer className="border-t border-border bg-surface-sunken">
      <div className="mx-auto max-w-7xl px-6 py-16 lg:px-8">
        <div className="grid gap-12 lg:grid-cols-[1.5fr_3fr]">
          {/* Left: brand block */}
          <div>
            <Wordmark size="md" premium />
            <p className="mt-6 max-w-sm text-sm leading-relaxed text-neutral-500">
              The autonomous operating system for property portfolios.
              Calm intelligence. Institutional trust.
            </p>
            <p className="mt-8 font-mono text-[0.65rem] uppercase tracking-widest text-neutral-600">
              Nairobi · London · Dubai · Singapore
            </p>
          </div>

          {/* Right: link columns. Hrefs are explicit so they match the
              actual routes shipped under src/app/, not autogenerated. */}
          <div className="grid grid-cols-2 gap-8 sm:grid-cols-4">
            {[
              {
                title: 'Audiences',
                links: [
                  { label: 'Individual landlord',  href: '/for-individual-landlord' },
                  { label: 'Portfolio landlord',   href: '/for-portfolio-landlord' },
                  { label: 'Tenant',               href: '/for-tenant' },
                  { label: 'Leasing agency',       href: '/for-leasing-agency' },
                  { label: 'Housing cooperative',  href: '/for-housing-cooperative' },
                ],
              },
              {
                title: 'Company',
                links: [
                  { label: 'About',         href: '/about' },
                  { label: 'Careers',       href: '/careers' },
                  { label: 'Contact',       href: '/contact' },
                  { label: 'Blog',          href: '/blog' },
                  { label: 'Pilot',         href: '/pilot' },
                ],
              },
              {
                title: 'Resources',
                links: [
                  { label: 'Docs',          href: '/docs' },
                  { label: 'Pricing',       href: '/pricing' },
                  { label: 'Trust centre',  href: '/trust' },
                  { label: 'Status',        href: '/status' },
                  { label: 'Support',       href: '/support' },
                ],
              },
              {
                title: 'Legal',
                links: [
                  { label: 'Terms',         href: '/terms' },
                  { label: 'Privacy',       href: '/privacy' },
                  { label: 'DPA',           href: '/dpa' },
                  { label: 'Legal index',   href: '/legal' },
                  { label: 'Trust centre',  href: '/trust' },
                ],
              },
            ].map((col) => (
              <nav key={col.title} aria-label={col.title}>
                <h3 className="font-mono text-[0.65rem] uppercase tracking-widest text-neutral-500">
                  {col.title}
                </h3>
                <ul className="mt-4 space-y-2.5">
                  {col.links.map((l) => (
                    <li key={l.href}>
                      <Link
                        href={l.href}
                        className="text-sm text-neutral-500 transition-colors duration-fast hover:text-foreground"
                      >
                        {l.label}
                      </Link>
                    </li>
                  ))}
                </ul>
              </nav>
            ))}
          </div>
        </div>

        <div className="mt-16 flex flex-col items-start justify-between gap-4 border-t border-border pt-8 sm:flex-row sm:items-center">
          <p className="font-mono text-[0.68rem] text-neutral-500">
            © 2026 Boss Nyumba. All rights reserved.
          </p>
          <div className="flex items-center gap-4 font-mono text-[0.68rem] uppercase tracking-widest text-neutral-500">
            <span className="flex items-center gap-1.5">
              <span className="h-1.5 w-1.5 rounded-full bg-success" /> All systems operational
            </span>
            <span className="h-3 w-px bg-border" />
            <span>SOC 2 Type II</span>
            <span className="h-3 w-px bg-border" />
            <span>ISO 27001</span>
          </div>
        </div>
      </div>
    </footer>
  );
}
