apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bossnyumba-prod

resources:
  - ../../base

images:
  - name: ghcr.io/georgemwiki/bossnyumba-payments-ledger
    newTag: ${IMAGE_TAG}

patches:
  - target:
      kind: Deployment
      name: payments-ledger
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "500m"
            memory: "768Mi"
          limits:
            cpu: "4"
            memory: "4Gi"
      - op: replace
        path: /spec/template/spec/affinity/podAntiAffinity
        value:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: payments-ledger
              topologyKey: kubernetes.io/hostname
