import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../../core/api_client.dart';

/// Morning briefing screen — the "Your day" summary pushed at 7am.
/// Opens from a push-notification deep-link or from the home dashboard.
class MorningBriefingScreen extends StatefulWidget {
  final String? briefingDate; // YYYY-MM-DD, defaults to today

  const MorningBriefingScreen({super.key, this.briefingDate});

  @override
  State<MorningBriefingScreen> createState() => _MorningBriefingScreenState();
}

class _MorningBriefingScreenState extends State<MorningBriefingScreen> {
  Future<Map<String, dynamic>?>? _future;

  @override
  void initState() {
    super.initState();
    _future = _fetch();
  }

  Future<Map<String, dynamic>?> _fetch() async {
    final date = widget.briefingDate ?? DateFormat('yyyy-MM-dd').format(DateTime.now());
    final resp = await ApiClient.instance.get<dynamic>('/ai/briefing', queryParams: {'date': date});
    if (resp.isOk && resp.data is Map<String, dynamic>) return resp.data as Map<String, dynamic>;
    return null;
  }

  @override
  Widget build(BuildContext context) {
    final dateStr = widget.briefingDate ?? DateFormat('EEEE, d MMMM y').format(DateTime.now());

    return Scaffold(
      appBar: AppBar(title: Text(dateStr)),
      body: RefreshIndicator(
        onRefresh: () async {
          final f = _fetch();
          setState(() => _future = f);
          await f;
        },
        child: FutureBuilder<Map<String, dynamic>?>(
          future: _future,
          builder: (context, snap) {
            if (snap.connectionState == ConnectionState.waiting) {
              return const Center(child: CircularProgressIndicator());
            }
            final data = snap.data;
            if (data == null) {
              return ListView(children: const [
                SizedBox(height: 100),
                Center(child: Text('Unable to load briefing. Pull to retry.')),
              ]);
            }

            final summary = data['summary']?.toString() ?? 'Your daily briefing is ready.';
            final sections = data['sections'] is List ? data['sections'] as List : [];

            return ListView(
              padding: const EdgeInsets.all(20),
              children: [
                // Hero summary
                Card(
                  color: Theme.of(context).colorScheme.primaryContainer,
                  child: Padding(
                    padding: const EdgeInsets.all(20),
                    child: Column(
                      children: [
                        const Icon(Icons.auto_awesome, size: 32),
                        const SizedBox(height: 8),
                        Text(
                          summary,
                          style: Theme.of(context).textTheme.titleMedium?.copyWith(fontWeight: FontWeight.w600),
                          textAlign: TextAlign.center,
                        ),
                      ],
                    ),
                  ),
                ),
                const SizedBox(height: 16),
                // Dynamic sections
                ...sections.map((s) {
                  final section = s is Map<String, dynamic> ? s : <String, dynamic>{};
                  final title = section['title']?.toString() ?? '';
                  final headline = section['headline']?.toString() ?? '';
                  final icon = _sectionIcon(section['type']?.toString() ?? '');

                  return Card(
                    margin: const EdgeInsets.only(bottom: 8),
                    child: ListTile(
                      leading: Icon(icon, color: Theme.of(context).colorScheme.primary),
                      title: Text(title, style: const TextStyle(fontWeight: FontWeight.w600)),
                      subtitle: Text(headline),
                      trailing: const Icon(Icons.chevron_right, size: 18),
                      onTap: () {
                        final route = section['deepLink']?.toString();
                        if (route != null && route.isNotEmpty) {
                          // context.go(route);
                        }
                      },
                    ),
                  );
                }),
                const SizedBox(height: 24),
                Text(
                  'Generated by Boss AI. Tap to refresh.',
                  style: TextStyle(color: Colors.grey[400], fontSize: 11),
                  textAlign: TextAlign.center,
                ),
              ],
            );
          },
        ),
      ),
    );
  }

  IconData _sectionIcon(String type) {
    switch (type) {
      case 'money': return Icons.payments;
      case 'occupancy': return Icons.people;
      case 'pending': return Icons.pending_actions;
      case 'maintenance': return Icons.build;
      case 'tax': return Icons.receipt_long;
      case 'risk': return Icons.warning;
      default: return Icons.info_outline;
    }
  }
}
