/**
 * Persona-aware opener copy for the chat-first home tab.
 *
 * Swahili-first per the BossNyumba CLAUDE.md hard rule. The English line
 * sits underneath each chip so bilingual pilots can read either layer
 * without a language switch. Tap a chip → the composer auto-fills with
 * the Swahili variant and submits — the orchestrator handles language
 * routing server-side.
 *
 * The map is frozen so callers can pass tuples around without copy-on-
 * write fear.
 */
import type { Role } from '../roles/types'

export interface ChatSuggestion {
  readonly id: string
  readonly sw: string
  readonly en: string
}

export interface HomeChatOpener {
  readonly greetingSw: string
  readonly greetingEn: string
  readonly suggestions: ReadonlyArray<ChatSuggestion>
}

const OWNER_OPENER: HomeChatOpener = Object.freeze({
  greetingSw: 'Karibu, Bwana Mkubwa. Niambie kuhusu mali zako leo.',
  greetingEn: 'Welcome, Owner. Tell me about your properties today.',
  suggestions: Object.freeze([
    Object.freeze({ id: 'owner-brief', sw: 'Onyesha muhtasari', en: 'Show daily brief' }),
    Object.freeze({ id: 'owner-cash', sw: 'Hela na muda', en: 'Cash and runway' }),
    Object.freeze({ id: 'owner-decisions', sw: 'Maamuzi yanayosubiri', en: 'Pending decisions' })
  ]) as ReadonlyArray<ChatSuggestion>
}) as HomeChatOpener

const MANAGER_OPENER: HomeChatOpener = Object.freeze({
  greetingSw: 'Karibu, Meneja. Tukasaidia timu yako leo.',
  greetingEn: 'Welcome, Manager. Let me help your crew today.',
  suggestions: Object.freeze([
    Object.freeze({ id: 'manager-crew', sw: 'Hali ya timu', en: 'Crew status' }),
    Object.freeze({ id: 'manager-exceptions', sw: 'Mizigo iliyochelewa', en: 'Late equipment' }),
    Object.freeze({ id: 'manager-approvals', sw: 'Idhinisho zinazosubiri', en: 'Pending approvals' })
  ]) as ReadonlyArray<ChatSuggestion>
}) as HomeChatOpener

const EMPLOYEE_OPENER: HomeChatOpener = Object.freeze({
  greetingSw: 'Karibu, Mfanyakazi. Nina kazi gani leo?',
  greetingEn: 'Welcome, Worker. What is my shift today?',
  suggestions: Object.freeze([
    Object.freeze({ id: 'employee-shift', sw: 'Shifti yangu leo', en: 'My shift today' }),
    Object.freeze({ id: 'employee-tasks', sw: 'Kazi zangu', en: 'My tasks' }),
    Object.freeze({ id: 'employee-perf', sw: 'Ripoti ya mwisho', en: 'Latest report' })
  ]) as ReadonlyArray<ChatSuggestion>
}) as HomeChatOpener

export const HOME_CHAT_OPENERS: Readonly<Record<Role, HomeChatOpener>> = Object.freeze({
  owner: OWNER_OPENER,
  manager: MANAGER_OPENER,
  employee: EMPLOYEE_OPENER
})

export function openerFor(role: Role): HomeChatOpener {
  return HOME_CHAT_OPENERS[role]
}

/**
 * Generic bilingual chat labels — reused by the composer + bubble headers.
 * Kept inline (not in the JSON catalogue) because the JSON files are owned
 * by the i18n agent this wave; we'll merge once that catalogue lands.
 *
 * The shape is a tight named record (not Record<string, …>) so direct
 * `HOME_CHAT_LABELS.errorRetry.sw` access is provably defined under
 * `noUncheckedIndexedAccess` — no `?.` ladder needed at call sites.
 */
export interface BilingualString {
  readonly sw: string
  readonly en: string
}

export interface HomeChatLabels {
  readonly composerPlaceholder: BilingualString
  readonly send: BilingualString
  readonly voice: BilingualString
  readonly attach: BilingualString
  readonly thinking: BilingualString
  readonly errorRetry: BilingualString
  readonly suggestionsTitle: BilingualString
  readonly toolCardHeader: BilingualString
  readonly proposedAction: BilingualString
  readonly riskHigh: BilingualString
  readonly riskMedium: BilingualString
  readonly riskLow: BilingualString
  readonly riskCritical: BilingualString
}

export const HOME_CHAT_LABELS: HomeChatLabels = Object.freeze({
  composerPlaceholder: { sw: 'Andika ujumbe wako…', en: 'Write your message…' },
  send: { sw: 'Tuma', en: 'Send' },
  voice: { sw: 'Sauti', en: 'Voice' },
  attach: { sw: 'Ambatisha', en: 'Attach' },
  thinking: { sw: 'BossNyumba anafikiri…', en: 'BossNyumba is thinking…' },
  errorRetry: { sw: 'Hatukuweza kufikia ubongo. Jaribu tena.', en: 'Could not reach the brain. Try again.' },
  suggestionsTitle: { sw: 'Maswali ya haraka', en: 'Quick prompts' },
  toolCardHeader: { sw: 'Imeandaliwa na BossNyumba', en: 'Generated by BossNyumba' },
  proposedAction: { sw: 'BossNyumba inapendekeza', en: 'BossNyumba suggests' },
  riskHigh: { sw: 'Hatari kubwa', en: 'High risk' },
  riskMedium: { sw: 'Hatari ya wastani', en: 'Medium risk' },
  riskLow: { sw: 'Hatari ndogo', en: 'Low risk' },
  riskCritical: { sw: 'Hatari ya juu sana', en: 'Critical risk' }
})

export type LangChoice = 'sw' | 'en'

export function pickLabel(key: keyof HomeChatLabels, lang: LangChoice): string {
  const entry = HOME_CHAT_LABELS[key]
  return entry[lang]
}
