apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bossnyumba-prod

resources:
  - ../../base

images:
  - name: ghcr.io/georgemwiki/bossnyumba-outbox-processor
    newTag: ${IMAGE_TAG}

patches:
  - target:
      kind: Deployment
      name: outbox-processor
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "200m"
            memory: "384Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
