import type { WorkOrderCardData } from '@/components/maintenance';

export const KANBAN_COLUMNS = [
  { id: 'submitted', title: 'Submitted' },
  { id: 'triaged', title: 'Triaged' },
  { id: 'assigned', title: 'Assigned' },
  { id: 'in_progress', title: 'In Progress' },
  { id: 'completed', title: 'Completed' },
] as const;

export type KanbanColumnId = (typeof KANBAN_COLUMNS)[number]['id'];

export const mockWorkOrders: WorkOrderCardData[] = [
  {
    id: '1',
    workOrderNumber: 'WO-2024-0052',
    title: 'Water heater not working',
    category: 'Plumbing',
    unit: 'C-405',
    property: 'Sunset Apartments',
    status: 'submitted',
    priority: 'emergency',
    assignedTo: null,
    createdAt: '2024-02-25T06:30:00Z',
    scheduledDate: null,
    sla: {
      responseRemaining: 15,
      resolutionRemaining: 210,
      responseBreached: false,
      resolutionBreached: false,
    },
  },
  {
    id: '2',
    workOrderNumber: 'WO-2024-0051',
    title: 'Broken window in bedroom',
    category: 'Structural',
    unit: 'B-201',
    property: 'Sunset Apartments',
    status: 'triaged',
    priority: 'high',
    assignedTo: null,
    createdAt: '2024-02-25T08:00:00Z',
    scheduledDate: null,
    sla: {
      responseRemaining: null,
      resolutionRemaining: 1380,
      responseBreached: false,
      resolutionBreached: false,
    },
  },
  {
    id: '3',
    workOrderNumber: 'WO-2024-0048',
    title: 'Door lock replacement',
    category: 'Security',
    unit: 'C-301',
    property: 'Sunset Apartments',
    status: 'assigned',
    priority: 'high',
    assignedTo: 'James Mwangi',
    createdAt: '2024-02-24T10:00:00Z',
    scheduledDate: '2024-02-25T14:00:00Z',
    sla: {
      responseRemaining: null,
      resolutionRemaining: 480,
      responseBreached: false,
      resolutionBreached: false,
    },
  },
  {
    id: '4',
    workOrderNumber: 'WO-2024-0045',
    title: 'AC not cooling properly',
    category: 'HVAC',
    unit: 'B-102',
    property: 'Sunset Apartments',
    status: 'in_progress',
    priority: 'medium',
    assignedTo: 'James Mwangi',
    createdAt: '2024-02-23T14:30:00Z',
    scheduledDate: '2024-02-25T11:00:00Z',
    sla: {
      responseRemaining: null,
      resolutionRemaining: 120,
      responseBreached: false,
      resolutionBreached: false,
    },
  },
  {
    id: '5',
    workOrderNumber: 'WO-2024-0042',
    title: 'Kitchen sink leaking',
    category: 'Plumbing',
    unit: 'A-204',
    property: 'Sunset Apartments',
    status: 'assigned',
    priority: 'high',
    assignedTo: 'James Mwangi',
    createdAt: '2024-02-20T10:30:00Z',
    scheduledDate: '2024-02-25T09:00:00Z',
    sla: {
      responseRemaining: null,
      resolutionRemaining: 240,
      responseBreached: false,
      resolutionBreached: false,
    },
  },
  {
    id: '6',
    workOrderNumber: 'WO-2024-0039',
    title: 'Light fixture flickering',
    category: 'Electrical',
    unit: 'A-105',
    property: 'Sunset Apartments',
    status: 'completed',
    priority: 'low',
    assignedTo: 'External Vendor',
    createdAt: '2024-02-18T09:00:00Z',
    scheduledDate: null,
    sla: {
      responseRemaining: null,
      resolutionRemaining: -120,
      responseBreached: true,
      resolutionBreached: true,
    },
  },
];
